"use client";
import {useMemo,useState} from "react";
import Link from "next/link";

const records=[
 {type:"Contact",title:"Contact RN",summary:"Start a nonconfidential conversation about a recurring problem, consequential decision, or piece of work that needs to become clearer and more usable.",status:"Public LinkedIn route",problem:"Discuss possible work with RN",href:"/contact",terms:"RN Collins project inquiry contact work"},
 {type:"Start",title:"Start Here",summary:"Choose a course, free tool, or way to work with RN based on the situation you face.",status:"Available",problem:"Find a starting point",href:"/start",terms:"route choose situation"},
 {type:"Tool",title:"Opportunity Studio",summary:"A browser-local 23-prompt prototype for examining whether to test AI, repair a process, keep work human-led, or investigate further.",status:"Guided prototype",problem:"AI fit and workflow readiness",href:"/studio",terms:"rule based decision aid local"},
 {type:"Tool",title:"Decision Record Builder",summary:"Preserve the owner, alternatives, evidence, affected people, uncertainty, stop conditions, fallback, and review date.",status:"Working public builder",problem:"One accountable decision",href:"/tools/decision-record",terms:"markdown json local record"},
 {type:"Tool",title:"Tool & Vendor Comparison Builder",summary:"Compare the current process and two candidates against self-recorded gates and weighted criteria.",status:"Working public builder",problem:"Bounded option comparison",href:"/tools/vendor-comparison",terms:"vendor tool gate weights markdown json"},
 {type:"Tool",title:"Pilot Design Kit",summary:"Precommit a pilot hypothesis, baseline, measures, authority, stop conditions, rollback, and final decision.",status:"Working public builder",problem:"Bounded pilot planning",href:"/tools/pilot-design",terms:"pilot gates rollback markdown json"},
 {type:"Learning",title:"AI & Your Work Flagship Masterclass",summary:"The complete 105-minute, 24-chapter flagship using Define–Examine–Decide–Build, the Kōkua Studio case, Opportunity Map, four findings, intervention ladder, workbook, and Monday Plan.",status:"Complete flagship curriculum",problem:"Examine work before automation",href:"/learning/masterclass",terms:"free masterclass flagship Kōkua friction inputs judgment risk value"},
 {type:"Learning",title:"Citation Verifier Course",summary:"A complete 15-hour course with eighteen lessons and practices, lab kit, knowledge check, capstone, rubric, and local progress record.",status:"Complete open edition",problem:"Citation verification system design",href:"/learning/citation-verifier",terms:"course citation evidence trust safe capstone"},
 {type:"Program",title:"Decision Desk · Twelve-Month Program",summary:"A twelve-part learning plan for working through real AI decisions—from client intake through stopping or retiring a system—with issue-by-issue readiness shown honestly.",status:"Plan published · readiness varies",problem:"Year-long case-based decision learning",href:"/learning/decision-desk",terms:"annual 12 month issues masterclass clinic"},
 {type:"Program",title:"Decision Desk · Issue 01",summary:"The flagship issue on whether a small law firm should use AI to summarize prospective-client intake.",status:"Substantial package built · release gated",problem:"AI-assisted client intake",href:"/learning/decision-desk/issue-01",terms:"intake evaluation card law firm synthetic benchmark no product finding"},
 {type:"Program",title:"Decision Desk · Issue 02 · Before the Bot Joins the Meeting",summary:"A governed learning experience and Meeting Capture Permission and Record Map for deciding whether an AI meeting bot belongs in a defined meeting class.",status:"Complete public learning edition",problem:"AI meeting capture",href:"/learning/decision-desk/issue-02",terms:"meeting recording consent permission records"},
 {type:"Program",title:"Decision Desk · Issue 03 · Should AI Answer Your Customers?",summary:"A complete public course and Support Automation Authority Map for deciding what AI may classify, retrieve, draft, send, or act on in customer support.",status:"Complete public learning edition",problem:"Customer support authority",href:"/learning/decision-desk/issue-03",terms:"support agent authority classify retrieve draft send act"},
 {type:"Program",title:"Decision Desk · Issue 04 · Can Your AI Find the Right Answer?",summary:"A complete public course and Knowledge Answerability and Source-Authority Test for governing internal AI answers.",status:"Complete public learning edition",problem:"Internal knowledge authority",href:"/learning/decision-desk/issue-04",terms:"retrieval answerability source permission abstention"},
 {type:"Program",title:"Decision Desk · Issue 05 · Should AI Help Choose People?",summary:"A complete public course and Human Opportunity Decision Impact Map for governing AI in hiring, admissions, grants, fellowships, and other opportunities.",status:"Complete public learning edition",problem:"Human opportunity decisions",href:"/learning/decision-desk/issue-05",terms:"hiring admissions grants selection impact"},
 {type:"Program",title:"Decision Desk · Issue 06 · Can You Prove That AI-Written Claim?",summary:"A complete public course and Public-Claim Substantiation Gate for governing AI-drafted performance, scientific, sustainability, endorsement, outcome, and comparative claims.",status:"Complete public learning edition",problem:"Public claim substantiation",href:"/learning/decision-desk/issue-06",terms:"claim evidence scientific comparative endorsement"},
 {type:"Program",title:"Decision Desk · Issue 07 · Can People Trust This AI Explanation?",summary:"A complete public course and High-Stakes Explanation Fidelity Test for translating authoritative health, legal, financial, benefits, safety, and public-service information.",status:"Complete public learning edition",problem:"High-stakes explanation fidelity",href:"/learning/decision-desk/issue-07",terms:"explanation fidelity access uncertainty advice"},
 {type:"Program",title:"Decision Desk · Issue 08 · Can You Use Someone’s AI Voice or Image?",summary:"A complete public course and Synthetic Media Permission and Provenance Record for bounded uses of synthetic voice, likeness, performance, and documentary-style media.",status:"Complete public learning edition",problem:"Synthetic media permission",href:"/learning/decision-desk/issue-08",terms:"voice image likeness provenance consent"},
 {type:"Program",title:"Decision Desk · Issue 09 · What Should Your AI Agent Be Allowed to Do?",summary:"A complete public course and Agent Action Authority and Reversibility Matrix for bounded AI actions across messages, money, records, data, and connected systems.",status:"Complete public learning edition",problem:"AI agent authority",href:"/learning/decision-desk/issue-09",terms:"agent actions authority reversibility kill switch"},
 {type:"Program",title:"Decision Desk · Issue 10 · What to Check Before Buying an AI Tool",summary:"A complete public course and AI Vendor Evidence and Contract Dossier for small-organization AI procurement, implementation, contracting, exit, and continuity.",status:"Complete public learning edition",problem:"AI procurement and vendor evidence",href:"/learning/decision-desk/issue-10",terms:"vendor procurement contract exit continuity"},
 {type:"Program",title:"Decision Desk · Issue 11 · Should AI Review a Student’s Work?",summary:"A complete public course and Learner-Affecting AI Use Review for bounded educational feedback, assessment, personalization, and intervention uses.",status:"Complete public learning edition",problem:"Learner-affecting educational AI",href:"/learning/decision-desk/issue-11",terms:"student learning assessment feedback education"},
 {type:"Program",title:"Decision Desk · Issue 12 · Is It Time to Stop Using This AI?",summary:"A complete public course and AI Continuation and Retirement Decision Record for deciding whether to continue, pause, repair, roll back, replace, or retire one exact AI use.",status:"Complete public learning edition",problem:"AI continuation and retirement",href:"/learning/decision-desk/issue-12",terms:"continue pause repair rollback replace retire"},
 {type:"Service",title:"Opportunity Clinic",summary:"A defined 90-minute facilitated session for an existing team or private cohort of up to six people.",status:"Defined · no public checkout",problem:"Collaborative workflow inquiry",href:"/work/ai-opportunity-clinic",terms:"275 participant cohort cancellation refund reservation"},
 {type:"Service",title:"Decision Record Review",summary:"A candidate facilitated review for one bounded decision.",status:"Unavailable and unpriced",problem:"One consequential decision",href:"/work/ai-decision-review",terms:"private review candidate"},
 {type:"Service",title:"Workflow Conditions Inquiry",summary:"A candidate inquiry into one recurring workflow before technology is chosen.",status:"Unavailable and unpriced",problem:"Fragile or unclear workflow",href:"/work/workflow-diagnostic-redesign",terms:"workflow process candidate"},
 {type:"Service",title:"Requirements & Evidence Comparison",summary:"A candidate facilitated comparison for one defined use case and bounded option set.",status:"Unavailable and unpriced",problem:"Technology or vendor choice",href:"/work/ai-tool-vendor-decision",terms:"requirements procurement candidate"},
 {type:"Service",title:"Pilot Decision Protocol",summary:"A candidate service for designing one bounded test with measures, fallback, and stop conditions.",status:"Unavailable and unpriced",problem:"Pilot protocol",href:"/work/prototype-pilot-sprint",terms:"pilot test candidate"},
 {type:"Service",title:"AI Operating Partnership",summary:"A candidate continuing-advisory structure for a defined decision domain.",status:"Unavailable and unpriced",problem:"Continuing organizational AI work",href:"/work/ai-operating-partnership",terms:"portfolio governance candidate"},
 {type:"Service",title:"Custom Organizational Program",summary:"A candidate wrapper for coordinating two or more independently validated modules.",status:"Unavailable and unpriced",problem:"Institutional multi-module work",href:"/work/custom-organizational-program",terms:"organization institution candidate"},
 {type:"Organization",title:"Work with RN",summary:"Bring RN a recurring problem, consequential decision, or difficult body of work. She researches the situation, exposes the gaps, and helps make the right response concrete and usable.",status:"Conversation available",problem:"Organizational AI work",href:"/work",terms:"team buyer workflow research strategy build"},
 {type:"Organization",title:"Sponsored Public Program",summary:"A proposed sponsorship model with integrity rules that prevent purchase of participant data or instructional control.",status:"Prospectus inactive",problem:"Public-benefit sponsorship",href:"/sponsor",terms:"15000 sponsor integrity"},
 {type:"Evidence",title:"Source Desk",summary:"A maintained register mapping twelve public method claims and all twelve Decision Desk issues to seventeen official records, with each source’s use, limit, and review trigger.",status:"Published evidence register",problem:"Evidence-led AI decisions",href:"/insights",terms:"source desk NIST GAO WCAG CISA ABA claim map"},
 {type:"Public record",title:"Questions",summary:"Publication rules for possible future public answers; no answer records exist yet.",status:"Empty by design",problem:"Public questions and answers",href:"/questions",terms:"answers publication privacy"},
 {type:"Buyer info",title:"Procurement",summary:"Preliminary capability, scope, privacy, accessibility, AI-use, and buying-state information.",status:"Evaluation only",problem:"Institutional due diligence",href:"/procurement",terms:"buyer insurance tax security"},
 {type:"Standard",title:"Policies",summary:"Plain-language boundaries for local tool data, Clinic inquiries, evidence, accessibility, advice, and commerce.",status:"Current public boundaries",problem:"Rules and privacy",href:"/policies",terms:"terms privacy data professional advice"},
 {type:"Support",title:"Support and Accessibility",summary:"Current keyboard, zoom, motion, privacy, recovery, accommodation, and emergency boundaries.",status:"Information only",problem:"Access or site support",href:"/support",terms:"help accessibility recovery incident"},
 {type:"About",title:"About RN Collins and Aloha AI",summary:"The practice method, selected public work, and current professional boundaries.",status:"Published profile",problem:"Who built the practice",href:"/about",terms:"RN Collins research biography Honolulu"},
];

const types=["All",...Array.from(new Set(records.map(record=>record.type)))];

export function PublicSearch(){
 const [query,setQuery]=useState("");
 const [type,setType]=useState("All");
 const results=useMemo(()=>{const words=query.toLowerCase().trim().split(/\s+/).filter(Boolean);return records.filter(record=>(type==="All"||record.type===type)&&words.every(word=>`${record.title} ${record.summary} ${record.problem} ${record.terms} ${record.status}`.toLowerCase().includes(word)))},[query,type]);
 return <section className="wrap search-workspace">
  <form role="search" onSubmit={event=>event.preventDefault()}><label htmlFor="site-query">What are you trying to find?</label><div className="search-row"><input id="site-query" type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Try “workflow,” “course,” “vendor,” or “privacy”"/><button type="button" onClick={()=>{setQuery("");setType("All")}}>Clear</button></div></form>
  <fieldset><legend>Filter by record type</legend><div className="filter-row">{types.map(item=><button key={item} type="button" aria-pressed={type===item} onClick={()=>setType(item)}>{item}</button>)}</div></fieldset>
  <div className="search-count" aria-live="polite">{results.length} {results.length===1?"record":"records"}</div>
  {results.length?<div className="search-results">{results.map(record=><article key={record.href}><div><span className="state-label">{record.type}</span><span className="search-status">{record.status}</span></div><h2><Link href={record.href}>{record.title}</Link></h2><p>{record.summary}</p><p className="search-problem"><strong>Relevant to:</strong> {record.problem}</p><Link className="text-link" href={record.href}>Open this page →</Link></article>)}</div>:<div className="quiet-note"><h2>No public page matches that search.</h2><p>Try fewer words, clear the type filter, <Link href="/start">start from your situation</Link>, or <Link href="/contact">contact RN</Link>.</p></div>}
 </section>
}
