"use client";
import {useMemo,useState} from "react";
import Link from "next/link";

const records=[
 {type:"Tool",title:"Opportunity Studio",summary:"A private-by-default 23-step pathway for deciding whether to test AI, repair a process, keep work human-led, or investigate further.",status:"Available",problem:"AI fit, workflow readiness, risk",href:"/studio",terms:"assessment decision aid human review private local"},
 {type:"Learning",title:"Hawaiʻi Tech Week learning program",summary:"A candidate evidence-grounded program: What Should We Actually Use AI For?",status:"Format and registration under review",problem:"Learn how to decide where AI belongs",href:"/events/hawaii-tech-week",terms:"public learning education hawaii tech week"},
 {type:"Resource",title:"Hawaiʻi Tech Week Attendee Desk",summary:"Sources, access, handout, replay, transcript, and follow-on clinic status.",status:"Activation in progress",problem:"Prepare for or revisit the masterclass",href:"/events/hawaii-tech-week/resources",terms:"source desk replay transcript accessibility resources"},
 {type:"Service",title:"AI Opportunity Clinic",summary:"A facilitated working-session candidate under evidence and operating review.",status:"Unavailable and unpriced",problem:"Live collaborative problem-solving",href:"/work/ai-opportunity-clinic",terms:"small group facilitated inquiry"},
 {type:"Service",title:"AI Decision Review",summary:"A private decision-record service candidate under evidence and operating review.",status:"Unavailable and unpriced",problem:"One consequential decision",href:"/work/ai-decision-review",terms:"private written judgment"},
 {type:"Service",title:"Workflow Diagnostic & Redesign",summary:"Understand and redesign one recurring workflow before choosing technology.",status:"Inquiry inactive",problem:"Broken or fragile workflow",href:"/work/workflow-diagnostic-redesign",terms:"4500 7500 process handoff SOP"},
 {type:"Service",title:"AI Tool & Vendor Decision",summary:"Make a defensible selection decision against requirements and dated evidence.",status:"Inquiry inactive",problem:"Technology or vendor choice",href:"/work/ai-tool-vendor-decision",terms:"4500 7500 procurement comparison"},
 {type:"Service",title:"Prototype & Pilot Sprint",summary:"Build and test one bounded intervention with acceptance criteria, controls, and handoff.",status:"Inquiry inactive",problem:"Prototype or implementation test",href:"/work/prototype-pilot-sprint",terms:"12500 code build experiment pilot"},
 {type:"Service",title:"AI Operating Partnership",summary:"Continuing senior judgment and implementation leadership for a defined AI portfolio or operating domain.",status:"Inquiry inactive",problem:"Continuing organizational AI work",href:"/work/ai-operating-partnership",terms:"5000 8500 monthly leadership governance"},
 {type:"Service",title:"Custom Organizational Program",summary:"A procurement wrapper coordinating two or more core modules around one institutional outcome.",status:"Inquiry inactive",problem:"Coordinated multi-module program",href:"/work/custom-organizational-program",terms:"15000 25000 institution training governance"},
 {type:"Organization",title:"Organizational work",summary:"Choose a workflow, evaluation, build, or program route with procurement and delivery boundaries.",status:"Evaluation available",problem:"Institutional AI work",href:"/organizations",terms:"team buyer procurement"},
 {type:"Organization",title:"Sponsored Public Program",summary:"Fund accessible public learning without purchasing participant data, instruction, findings, or guaranteed attendance.",status:"Prospectus inactive",problem:"Public-benefit sponsorship",href:"/sponsor",terms:"15000 sponsor integrity"},
 {type:"Evidence",title:"Do not begin with the tool",summary:"A durable explanation of why the workflow, human judgment, readiness conditions, and stop rules come first.",status:"Representative record",problem:"Evidence-led AI decisions",href:"/insights",terms:"source desk NIST risk human led"},
 {type:"Standard",title:"Policies",summary:"Controlled rules for privacy, purchases, events, accessibility, AI use, evidence, security, participant rights, and support.",status:"Review required",problem:"Rules and boundaries",href:"/policies",terms:"terms privacy cancellation data"},
 {type:"Support",title:"Support and accessibility",summary:"Routes for access, billing, events, accommodations, data choices, and security concerns.",status:"Submission inactive",problem:"Recovery or accommodation",href:"/support",terms:"help refund delete correction incident"},
 {type:"Buyer info",title:"Procurement",summary:"Capability, commercial scope, accessibility, AI use, privacy, security, and supported assurance facts.",status:"Evaluation available",problem:"Institutional due diligence",href:"/procurement",terms:"vendor buyer insurance tax"},
];
const types=["All",...Array.from(new Set(records.map(r=>r.type)))];
export function PublicSearch(){const [query,setQuery]=useState("");const [type,setType]=useState("All");const results=useMemo(()=>{const words=query.toLowerCase().trim().split(/\s+/).filter(Boolean);return records.filter(r=>(type==="All"||r.type===type)&&words.every(w=>`${r.title} ${r.summary} ${r.problem} ${r.terms}`.toLowerCase().includes(w)))},[query,type]);return <section className="wrap search-workspace"><form role="search" onSubmit={e=>e.preventDefault()}><label htmlFor="site-query">What are you trying to find?</label><div className="search-row"><input id="site-query" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try “workflow,” “vendor,” “privacy,” or “live help”"/><button type="button" onClick={()=>{setQuery("");setType("All")}}>Clear</button></div></form><fieldset><legend>Filter by record type</legend><div className="filter-row">{types.map(t=><button key={t} type="button" aria-pressed={type===t} onClick={()=>setType(t)}>{t}</button>)}</div></fieldset><div className="search-count" aria-live="polite">{results.length} {results.length===1?"record":"records"}</div>{results.length?<div className="search-results">{results.map(r=><article key={r.href}><div><span className="state-label">{r.type}</span><span className="search-status">{r.status}</span></div><h2><Link href={r.href}>{r.title}</Link></h2><p>{r.summary}</p><p className="search-problem"><strong>Relevant to:</strong> {r.problem}</p><Link className="text-link" href={r.href}>Open the canonical record →</Link></article>)}</div>:<div className="quiet-note"><h2>No active record matches that search.</h2><p>Try fewer words, clear the type filter, <Link href="/start">start from your situation</Link>, or use the <Link href="/studio">Opportunity Studio</Link>. No draft or deferred page will be substituted to avoid a zero result.</p></div>}</section>}
