import Link from "next/link";
import type {Metadata} from "next";
import {SiteShell} from "../site-shell";

export const metadata:Metadata={title:"For organizations",description:"Bring RN Collins a recurring problem, consequential decision, or difficult body of work and determine a useful, bounded response."};
const problems=[["The same work keeps breaking down","A process depends on hidden knowledge, repeated repair, or people compensating for a system that does not hold."],["A consequential decision is stuck","The evidence, authority, tradeoffs, affected people, or next move are unclear."],["Knowledge exists but is not usable","Research, law, policy, science, or institutional memory is not reaching the people who need it in a form they can use."],["AI is already entering the work","A team needs to understand where it belongs, what it requires, who remains accountable, and when to stop."]];

export default function Organizations(){return <SiteShell><main id="main">
 <section className="page-hero wrap"><p className="kicker">For organizations</p><h1>Start with what keeps recurring, <em>not with an AI shopping list.</em></h1><p className="lede">RN researches the organization, the work, the evidence, and the people around it. Together, that inquiry makes the real gap visible and determines whether the useful response is strategy, research, design, a build, facilitation, learning, or no new technology at all.</p><div className="actions"><Link className="button primary" href="/contact">Bring RN the problem</Link><Link className="button" href="/work/ai-opportunity-clinic">Review the defined Clinic</Link></div></section>
 <section className="trust-section wrap"><div className="section-head"><p className="section-label">Problems worth bringing</p><h2>You do not need to diagnose the solution first.</h2></div><div className="trust-grid">{problems.map((item,index)=><article key={item[0]}><span className="path-num">{String(index+1).padStart(2,"0")}</span><h3>{item[0]}</h3><p>{item[1]}</p></article>)}</div></section>
 <section className="boundary wrap"><p className="section-label">How an engagement begins</p><div><h2>Understand → frame → scope → deliver → hand off.</h2><p>A first nonconfidential conversation tests whether there is a useful fit. No project begins until the problem, boundaries, people, evidence needs, deliverables, responsibilities, terms, and price are separately defined and accepted.</p><Link className="text-link" href="/procurement">Review current procurement information →</Link></div></section>
 <section className="boundary wrap"><p className="section-label">Current availability</p><div><h2>No unnamed consulting package is silently for sale.</h2><p>The Opportunity Clinic is the only facilitated format with published scope and terms. Other service records remain developing, unavailable, and unpriced. Contacting RN does not reserve a session or create an engagement.</p></div></section>
 </main></SiteShell>}
