import Link from "next/link";
import type {Metadata} from "next";
import {SiteShell} from "../../site-shell";
import {ClinicInquiryForm} from "./clinic-inquiry-form";
import {clinicEnrollmentConfigured} from "./clinic-config";

export const metadata:Metadata={title:"AI Opportunity Clinic",description:"Review Aloha AI’s bounded 90-minute small-group clinic for examining one nonconfidential workflow before choosing technology."};
const flow=[["01","Frame","Name one bounded workflow, outcome, accountable owner, and consequence without disclosing confidential information."],["02","Examine","Map current conditions, exceptions, affected people, evidence, uncertainty, and non-AI alternatives."],["03","Test","Apply authority, data, access, review, fallback, measurement, and stop-condition gates."],["04","Record","Leave with a one-page opportunity record and one owner-selected next step; no recommendation or certification is issued."]];
export default function Clinic(){const inquiryEnabled=clinicEnrollmentConfigured();return <SiteShell><main id="main">
 <section className="page-hero wrap"><p className="kicker">Facilitated service · private cohorts</p><h1>Opportunity Clinic: <em>examine one workflow before choosing technology.</em></h1><p className="lede">A bounded small-group working session for turning one group-safe situation into an evidence-aware decision path—without treating a questionnaire as a diagnosis or an AI suggestion as a recommendation.</p><div className="actions"><a className="button primary" href="#clinic-inquiry">Start a cohort inquiry</a><Link className="button" href="/learning/masterclass">Start with the free masterclass</Link></div></section>
 <section className="event-status"><div className="wrap event-status-grid"><div><span>Format</span><strong>Remote · live</strong></div><div><span>Duration</span><strong>90 minutes</strong></div><div><span>Capacity</span><strong>Up to 6</strong></div><div><span>Price</span><strong>$275 / person</strong></div></div></section>
 <section className="wrap pathways"><div className="section-head"><div><p className="section-label">Clinic protocol</p><h2>One problem. Four moves. A usable record.</h2></div><p>Designed for an existing team or private cohort. Public mixed-cohort registration is not open.</p></div><div className="path-list">{flow.map(x=><article className="path-row" key={x[0]}><span className="path-num">{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div><span className="event-result">Clinic step</span></article>)}</div></section>
 <section className="offer-grid wrap"><article className="offer-card"><p className="section-label">Included</p><h2>Preparation, facilitation, and a portable result.</h2><ul className="scope-list"><li>Pre-session framing guide using nonconfidential information</li><li>90-minute facilitated remote session for up to six people</li><li>Accessible digital working materials supplied at least 48 hours before the session</li><li>One-page group-authored opportunity record and next-step checklist</li><li>Camera-optional participation, live captions where the platform supports them, and one planned break</li></ul><p>The listed price is per participant; a six-person cohort is $1,650. Any different scope requires a separate written agreement.</p></article><aside><p className="section-label">Not included</p><h2>No score, certification, confidential intake, or guaranteed outcome.</h2><p>The Clinic does not provide legal advice, vendor selection, compliance or security review, implementation, procurement, diagnosis, certification, or proof that AI is appropriate. Participants must not share privileged, regulated, security-sensitive, or other confidential material.</p><p className="quiet-note">An inquiry is not a booking. A date is not reserved and no payment is due until fit, access needs, availability, cancellation terms, and a secure payment path are confirmed in writing.</p></aside></section>
 <section className="wrap pathways" id="clinic-terms"><div className="section-head"><div><p className="section-label">Reservation, cancellation & refunds</p><h2>A dated slot, clear deadlines, and no hidden fees.</h2></div><p>These terms are supplied with every accepted scope and must be accepted before payment.</p></div><div className="path-list">
  <article className="path-row"><span className="path-num">01</span><div><h3>How a session becomes reserved</h3><p>After accepting an inquiry, Aloha AI offers a specific date, start time, time zone, cohort size, and total price. That slot is held for 48 hours. It becomes reserved only when the full stated total is paid. If payment is not completed during the hold, the slot may be released. An inquiry alone never reserves a date.</p></div><span className="event-result">48-hour hold</span></article>
  <article className="path-row"><span className="path-num">02</span><div><h3>Cancel 7 or more calendar days ahead</h3><p>Cancel at least seven calendar days before the scheduled start for a full refund to the original payment method.</p></div><span className="event-result">100% refund</span></article>
  <article className="path-row"><span className="path-num">03</span><div><h3>Cancel 3–6 calendar days ahead</h3><p>Cancel between 72 hours and seven calendar days before the scheduled start for a 50% refund. The remaining 50% covers time held and preparation already committed.</p></div><span className="event-result">50% refund</span></article>
  <article className="path-row"><span className="path-num">04</span><div><h3>Late cancellation or no-show</h3><p>Cancellations less than 72 hours before the scheduled start and no-shows are not refundable. The cohort may substitute participants at no charge before the session, provided the maximum of six is not exceeded.</p></div><span className="event-result">Substitution allowed</span></article>
  <article className="path-row"><span className="path-num">05</span><div><h3>Reschedule once</h3><p>One reschedule is available without charge when requested at least 72 hours before the scheduled start. A replacement date must be mutually agreed and completed within 60 days. Later reschedule requests use the cancellation schedule above.</p></div><span className="event-result">One change</span></article>
  <article className="path-row"><span className="path-num">06</span><div><h3>If Aloha AI must cancel</h3><p>The cohort may accept a replacement date or receive a full refund. Aloha AI is not responsible for indirect costs or losses. If a material platform failure prevents delivery, the same replacement-or-full-refund choice applies.</p></div><span className="event-result">Customer chooses</span></article>
 </div><p className="quiet-note">Approved refunds are initiated within five business days to the original payment method. The bank or card issuer controls when the credit appears; <a href="https://docs.stripe.com/refunds" target="_blank" rel="noreferrer">Stripe says this commonly takes another 5–10 business days</a>. Accessibility requests do not reduce refund or rescheduling rights. Aloha AI may make a more favorable exception for emergencies or fairness, but an exception in one case does not change these published terms.</p></section>
 <section className="wrap clinic-intake" id="clinic-inquiry"><div className="section-head"><div><p className="section-label">Private-cohort inquiry</p><h2>Begin with the minimum information needed.</h2></div><p>Payment and Zoom details follow only after written scope and availability confirmation. This prevents a checkout from selling a date or service that has not been accepted.</p></div><ClinicInquiryForm enabled={inquiryEnabled}/></section>
 </main></SiteShell>}
