import Link from "next/link";
import type {Metadata} from "next";
import {SiteShell} from "../../site-shell";

export const metadata:Metadata={title:"AI Opportunity Clinic",description:"Review Aloha AI’s bounded 90-minute small-group clinic for examining one nonconfidential workflow before choosing technology."};
const flow=[["01","Frame","Name one bounded workflow, outcome, accountable owner, and consequence without disclosing confidential information."],["02","Examine","Map current conditions, exceptions, affected people, evidence, uncertainty, and non-AI alternatives."],["03","Test","Apply authority, data, access, review, fallback, measurement, and stop-condition gates."],["04","Record","Leave with a one-page opportunity record and one owner-selected next step; no recommendation or certification is issued."]];
export default function Clinic(){return <SiteShell><main id="main">
 <section className="page-hero wrap"><p className="kicker">Facilitated service · cohort conversations open</p><h1>Opportunity Clinic: <em>examine one workflow before choosing technology.</em></h1><p className="lede">A bounded small-group working session for turning one group-safe situation into an evidence-aware decision path—without treating a questionnaire as a diagnosis or an AI suggestion as a recommendation.</p><div className="actions"><a className="button primary" href="https://www.linkedin.com/in/rn-collins" target="_blank" rel="noreferrer">Discuss a private cohort ↗</a><Link className="button" href="/learning/masterclass">Start with the free masterclass</Link></div></section>
 <section className="event-status"><div className="wrap event-status-grid"><div><span>Format</span><strong>Remote · live</strong></div><div><span>Duration</span><strong>90 minutes</strong></div><div><span>Capacity</span><strong>Up to 6</strong></div><div><span>Price</span><strong>$275 / person</strong></div></div></section>
 <section className="wrap pathways"><div className="section-head"><div><p className="section-label">Clinic protocol</p><h2>One problem. Four moves. A usable record.</h2></div><p>Designed for an existing team or private cohort. Public mixed-cohort registration is not open.</p></div><div className="path-list">{flow.map(x=><article className="path-row" key={x[0]}><span className="path-num">{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div><span className="event-result">Clinic step</span></article>)}</div></section>
 <section className="offer-grid wrap"><article className="offer-card"><p className="section-label">Included</p><h2>Preparation, facilitation, and a portable result.</h2><ul className="scope-list"><li>Pre-session framing guide using nonconfidential information</li><li>90-minute facilitated remote session for up to six people</li><li>Accessible digital working materials supplied at least 48 hours before the session</li><li>One-page group-authored opportunity record and next-step checklist</li><li>Camera-optional participation, live captions where the platform supports them, and one planned break</li></ul><p>The listed price is per participant; a six-person cohort is $1,650. Any different scope requires a separate written agreement.</p></article><aside><p className="section-label">Not included</p><h2>No score, certification, confidential intake, or guaranteed outcome.</h2><p>The Clinic does not provide legal advice, vendor selection, compliance or security review, implementation, procurement, diagnosis, certification, or proof that AI is appropriate. Participants must not share privileged, regulated, security-sensitive, or other confidential material.</p><p className="quiet-note">The LinkedIn link opens a nonconfidential scope conversation; it is not booking, checkout, or secure intake. Do not send health information or detailed accommodation information there. A date is not reserved and no payment is due until scope, access needs, terms, and a secure administrative path are confirmed in writing.</p></aside></section>
 </main></SiteShell>}
