"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
type Answer={label:string;value:number}; type Module={title:string;prompt:string;why:string;answers:Answer[]};
const modules:Module[]=[
{title:"Work signal",prompt:"What brings you here?",why:"Start with the work—not a software catalog.",answers:[{label:"A recurring task or workflow",value:2},{label:"A tool or vendor decision",value:1},{label:"A team or organizational program",value:1},{label:"I am still naming the problem",value:-1}]},
{title:"Bounded example",prompt:"Can you name one specific example without sharing confidential information?",why:"A bounded example is safer and more testable than an entire organization.",answers:[{label:"Yes, one clear example",value:2},{label:"A few related examples",value:1},{label:"Not yet",value:-1}]},
{title:"Frequency",prompt:"How often does this work recur?",why:"Repeated work may justify a reusable intervention.",answers:[{label:"Daily or weekly",value:2},{label:"Monthly or periodically",value:1},{label:"Rarely",value:0}]},
{title:"Current friction",prompt:"What is the clearest current cost?",why:"The intervention should answer an observed problem.",answers:[{label:"Delay or backlog",value:1},{label:"Inconsistency or error",value:1},{label:"Access or comprehension",value:1},{label:"No demonstrated cost yet",value:-1}]},
{title:"Process clarity",prompt:"Is the current process understood and documented?",why:"Automation magnifies a broken or ambiguous process.",answers:[{label:"Yes, end to end",value:2},{label:"Partly",value:0},{label:"No",value:-2}]},
{title:"Human value",prompt:"Where does human judgment matter most?",why:"Some work should remain deliberately human-led.",answers:[{label:"At a defined review point",value:1},{label:"Throughout most of the work",value:-2},{label:"Very little",value:2},{label:"We have not examined this",value:-1}]},
{title:"Relationship",prompt:"Could changing this work affect trust, dignity, or a meaningful relationship?",why:"Efficiency is not the only value at stake.",answers:[{label:"Yes, materially",value:-2},{label:"Possibly",value:-1},{label:"Unlikely",value:1}]},
{title:"Consequence",prompt:"What happens if the output is wrong?",why:"Higher consequences require stronger review or a stop.",answers:[{label:"Safety, rights, livelihood, or legal impact",value:-3},{label:"Material operational harm",value:-1},{label:"Limited and reversible harm",value:2}]},
{title:"Affected people",prompt:"Can affected people understand or contest the result?",why:"Responsible systems need a route to challenge consequential outcomes.",answers:[{label:"Yes",value:1},{label:"Not yet",value:-2},{label:"Not applicable",value:1}]},
{title:"Data source",prompt:"Is the necessary information lawful, appropriate, and available?",why:"A tool cannot repair missing permission or unsuitable data.",answers:[{label:"Yes, with documented permission",value:2},{label:"Partly or uncertain",value:-1},{label:"No",value:-3}]},
{title:"Sensitivity",prompt:"Would the work involve sensitive, confidential, or personal information?",why:"Data sensitivity changes the permissible design.",answers:[{label:"Yes",value:-2},{label:"Possibly",value:-1},{label:"No",value:1}]},
{title:"Evidence",prompt:"Can a person tell whether an output is accurate?",why:"Unverifiable output cannot be responsibly relied upon.",answers:[{label:"Yes, against a trusted source",value:2},{label:"Sometimes",value:0},{label:"No",value:-3}]},
{title:"Baseline",prompt:"Do you know the current time, cost, quality, or error rate?",why:"Without a baseline, improvement claims become guesswork.",answers:[{label:"Yes",value:2},{label:"Partly",value:0},{label:"No",value:-1}]},
{title:"Success measure",prompt:"Is there a measurable definition of better?",why:"A test needs a result that can be evaluated.",answers:[{label:"Yes",value:2},{label:"A qualitative standard",value:1},{label:"Not yet",value:-1}]},
{title:"Reviewer",prompt:"Who has authority and time to review the output?",why:"Human review must be real, not ceremonial.",answers:[{label:"A named, capable reviewer",value:2},{label:"A role, but no protected time",value:0},{label:"No one",value:-3}]},
{title:"Owner",prompt:"Who owns the process after an experiment?",why:"A pilot without an operational owner becomes debris.",answers:[{label:"A named owner",value:2},{label:"A likely team",value:0},{label:"No owner",value:-2}]},
{title:"Capacity",prompt:"Can the team absorb setup, review, correction, and upkeep?",why:"Adoption creates work as well as removing it.",answers:[{label:"Yes",value:2},{label:"Only for a small pilot",value:1},{label:"No",value:-2}]},
{title:"Access",prompt:"Will the people doing the work have equitable access and usable accommodations?",why:"A system that excludes its users is not ready.",answers:[{label:"Yes",value:1},{label:"Needs design work",value:-1},{label:"No",value:-3}]},
{title:"Vendor boundary",prompt:"Can you state what information must never enter an external tool?",why:"A clear boundary must exist before tool selection.",answers:[{label:"Yes",value:2},{label:"Partly",value:0},{label:"No",value:-2}]},
{title:"Fallback",prompt:"Can the work continue safely if the tool fails?",why:"The process needs a viable non-AI route.",answers:[{label:"Yes",value:2},{label:"With delay",value:0},{label:"No",value:-2}]},
{title:"Stop rule",prompt:"Is there a clear condition that would stop the experiment?",why:"Responsible experiments define failure in advance.",answers:[{label:"Yes",value:2},{label:"We could define one",value:0},{label:"No",value:-2}]},
{title:"Smallest test",prompt:"Can the idea be tested with limited scope and reversible consequences?",why:"The smallest useful test creates evidence without overcommitting.",answers:[{label:"Yes",value:2},{label:"Possibly",value:0},{label:"No",value:-2}]},
{title:"Readiness check",prompt:"Which statement is most honest now?",why:"The result should match present capacity, not aspiration.",answers:[{label:"We can run a bounded, reviewed test",value:3},{label:"We need to repair or document the process first",value:-2},{label:"We need more evidence or governance",value:-1},{label:"This should remain human-led",value:-3}]},
];
type Plan={action:string;owner:string;safeInput:string;measure:string;reviewer:string;stop:string;unresolved:string};
const emptyPlan:Plan={action:"",owner:"",safeInput:"",measure:"",reviewer:"",stop:"",unresolved:""};
const planKeys=(Object.keys(emptyPlan) as (keyof Plan)[]);
const readSaved=()=>{if(typeof window==="undefined")return {answers:[] as number[],plan:{...emptyPlan}};try{const raw=localStorage.getItem("aloha-ai-opportunity-record-v1");if(!raw)return {answers:[] as number[],plan:{...emptyPlan}};const parsed=JSON.parse(raw);const answers:number[]=[];if(Array.isArray(parsed?.answers)){for(let i=0;i<Math.min(parsed.answers.length,modules.length);i++){const value=parsed.answers[i];if(!modules[i].answers.some(answer=>answer.value===value))break;answers.push(value)}}const plan={...emptyPlan};if(parsed?.plan&&typeof parsed.plan==="object"){for(const key of planKeys){if(typeof parsed.plan[key]==="string")plan[key]=parsed.plan[key]}}return {answers,plan}}catch{return {answers:[] as number[],plan:{...emptyPlan}}}};
export function Studio(){const [step,setStep]=useState(0);const [answers,setAnswers]=useState<number[]>([]);const [copyStatus,setCopyStatus]=useState("");const [storageStatus,setStorageStatus]=useState("");const [plan,setPlan]=useState<Plan>(emptyPlan);const [handoff,setHandoff]=useState(false);const score=answers.reduce((a,b)=>a+b,0);
const controllingConditions=useMemo(()=>[
  answers[7]===-3&&"A wrong output could affect safety, rights, livelihood, or legal interests.",
  answers[9]===-3&&"The necessary information is not currently lawful, appropriate, and available.",
  answers[11]===-3&&"A person cannot currently verify the output against a trusted source.",
  answers[14]===-3&&"No capable person currently has authority and time to review the output.",
  answers[17]===-3&&"The people doing the work would not have equitable access or usable accommodations.",
].filter((condition):condition is string=>Boolean(condition)),[answers]);
const outcome=useMemo(()=>controllingConditions.length?{key:"repair",title:"Do not test AI under the current conditions",body:"At least one non-negotiable condition is missing. Positive answers elsewhere cannot cancel it out. Repair the conditions below or keep the work human-led."}:score>=21?{key:"test",title:"A bounded experiment may be appropriate",body:"Your answers show enough clarity, review capacity, and reversibility to define a small test. This is not a recommendation for a particular tool."}:score>=7?{key:"prepare",title:"Prepare before you pilot",body:"There is a plausible opportunity, but important operating conditions are incomplete. Repair those conditions before selecting technology."}:score>=-5?{key:"repair",title:"Investigate and repair the process first",body:"The current uncertainty is more important than tool selection. Map the work, evidence, ownership, and review path before testing AI."}:{key:"human",title:"Keep this human-led for now",body:"The consequences, relationship value, information boundaries, or lack of responsible review outweigh the case for an AI test."},[controllingConditions,score]);
useEffect(()=>{const saved=readSaved();queueMicrotask(()=>{setAnswers(saved.answers);setPlan(saved.plan);setStep(saved.answers.length===modules.length?modules.length:saved.answers.length)})},[]);
useEffect(()=>{if(answers.length||Object.values(plan).some(Boolean)){try{localStorage.setItem("aloha-ai-opportunity-record-v1",JSON.stringify({version:"1.0",updated:new Date().toISOString(),answers,plan}));queueMicrotask(()=>setStorageStatus(""))}catch{queueMicrotask(()=>setStorageStatus("This browser could not save the record. Keep this page open and download your brief before leaving."))}}},[answers,plan]);
const selected=modules.map((m,i)=>({module:m.title,question:m.prompt,answer:m.answers.find(a=>a.value===answers[i])?.label??"Not answered"}));
const route=outcome.key==="test"?{title:"Define a small, reviewed experiment",href:"/work/prototype-pilot-sprint",label:"Examine the Prototype & Pilot Sprint"}:outcome.key==="prepare"?{title:"Redesign the workflow before choosing technology",href:"/work/workflow-diagnostic-redesign",label:"Examine the Workflow Diagnostic & Redesign"}:outcome.key==="repair"?{title:"Learn how to examine AI opportunities",href:"/events",label:"See the free monthly masterclass"}:{title:"Protect the human-led work and document why",href:"/insights",label:"Read the evidence-led method"};
const founderBrief=`ALOHA AI — PRIVATE OPPORTUNITY RECORD\nVersion 1.1 · ${new Date().toLocaleDateString()}\n\nFINDING\n${outcome.title}\n${outcome.body}\n\nCONTROLLING CONDITIONS\n${controllingConditions.length?controllingConditions.map(x=>`• ${x}`).join("\n"):"• No non-negotiable stop condition was selected. The directional finding still requires human review."}\n\nWHY THIS RESULT\n${selected.map(x=>`• ${x.module}: ${x.answer}`).join("\n")}\n\nMONDAY PLAN\nAction: ${plan.action||"Not yet defined"}\nOwner: ${plan.owner||"Not yet defined"}\nSafe input: ${plan.safeInput||"Not yet defined"}\nMeasure: ${plan.measure||"Not yet defined"}\nReviewer: ${plan.reviewer||"Not yet defined"}\nStop condition: ${plan.stop||"Not yet defined"}\n\nUNRESOLVED QUESTIONS\n${plan.unresolved||"Not yet recorded"}\n\nLIMITS\nThis is a private working record and decision aid. It is not a certification, legal advice, or a guarantee of savings, safety, compliance, or fitness. No Studio answer was transmitted to Aloha AI.`;
const copyText=async(text:string,label:"brief"|"handoff")=>{try{await navigator.clipboard.writeText(text);setCopyStatus(label==="brief"?"Brief copied.":"Team handoff copied.")}catch{setCopyStatus("Copy was blocked by this browser. Select the visible text and copy it manually.")}};
const download=()=>{const blob=new Blob([founderBrief],{type:"text/plain;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="aloha-ai-private-opportunity-record.txt";a.click();setTimeout(()=>URL.revokeObjectURL(url),0)};
if(step===modules.length)return <section className="studio-shell wrap"><div className="studio-progress"><span>Private result workspace</span><div className="progress-track" role="progressbar" aria-label="Studio progress" aria-valuemin={0} aria-valuemax={23} aria-valuenow={23}><i style={{width:"100%"}}/></div><span>23 / 23</span></div><div className="studio-layout"><aside className="studio-index"><span>Release 01</span><b>R</b><span>private · local</span></aside><div className="studio-card result-card"><p className="kicker">A reasoned starting point</p><h2 className="studio-question">{outcome.title}</h2><p className="lede">{outcome.body}</p><div className="result-band"><span>Directional finding</span><b>{controllingConditions.length?"Stop and repair":score>=21?"Test carefully":score>=7?"Prepare first":score>=-5?"Repair first":"Human-led"}</b></div><div className="quiet-note"><h2>What this result does—and does not—mean</h2><p>It organizes your answers into a next step. It does not certify safety, compliance, accuracy, or fitness for use. Non-negotiable conditions cannot be offset by the score; all other answers remain directional and require human judgment.</p></div>
{controllingConditions.length>0&&<section className="result-section" aria-labelledby="conditions-heading"><p className="section-label">Controlling conditions</p><h2 id="conditions-heading">These answers prevent an AI test for now.</h2><ul className="scope-list">{controllingConditions.map(condition=><li key={condition}>{condition}</li>)}</ul><p>Repairing a condition should trigger a new review. It does not automatically make a tool appropriate.</p></section>}
<section className="result-section" aria-labelledby="record-heading"><p className="section-label">Private Opportunity Record</p><h2 id="record-heading">See the reasoning—not hidden magic.</h2><div className="answer-record">{selected.map((x,i)=><details key={x.module}><summary><span>{String(i+1).padStart(2,"0")} · {x.module}</span><strong>{x.answer}</strong></summary><p>{x.question}</p></details>)}</div></section>
<section className="result-section plan-builder" aria-labelledby="plan-heading"><p className="section-label">Monday Plan</p><h2 id="plan-heading">Define one responsible next action.</h2><p>Complete only what you know. “Not yet defined” remains visible in the exported record.</p><div className="plan-grid">{([['action','One action'],['owner','Owner'],['safeInput','Safe or approved input'],['measure','Measure of usefulness'],['reviewer','Reviewer with authority'],['stop','Stop condition'],['unresolved','Unresolved questions']] as [keyof Plan,string][]).map(([key,label])=><label key={key} className={key==="unresolved"?"wide":""}><span>{label}</span>{key==="unresolved"?<textarea value={plan[key]} onChange={e=>setPlan({...plan,[key]:e.target.value})}/>:<input value={plan[key]} onChange={e=>setPlan({...plan,[key]:e.target.value})}/>}</label>)}</div></section>
<section className="result-section"><p className="section-label">Founder Brief</p><h2>Your dated, readable working record.</h2><textarea className="brief" aria-label="Generated founder brief" readOnly value={founderBrief}/><div className="studio-actions"><button onClick={()=>copyText(founderBrief,"brief")}>Copy brief</button><button onClick={download}>Download .txt</button></div><p className="action-status" role="status" aria-live="polite">{copyStatus}</p></section>
<section className="result-section"><p className="section-label">Optional Team Handoff</p><h2>Share duties—not every private answer.</h2><label className="handoff-toggle"><input type="checkbox" checked={handoff} onChange={e=>setHandoff(e.target.checked)}/><span>Create a bounded handoff from my Monday Plan</span></label>{handoff&&<div className="handoff-card"><p><strong>Assigned work:</strong> {plan.action||"Define the task before sharing."}</p><p><strong>Owner:</strong> {plan.owner||"Not assigned."}</p><p><strong>Review duty:</strong> {plan.reviewer||"Name a reviewer with authority to reject or stop."}</p><p><strong>Acceptance measure:</strong> {plan.measure||"Not defined."}</p><p><strong>Stop condition:</strong> {plan.stop||"Not defined."}</p><p className="quiet-note">Copy only this bounded section when the team does not need the full private record.</p><button onClick={()=>copyText(`TEAM HANDOFF\nTask: ${plan.action}\nOwner: ${plan.owner}\nSafe input: ${plan.safeInput}\nReviewer: ${plan.reviewer}\nMeasure: ${plan.measure}\nStop: ${plan.stop}`,"handoff")}>Copy handoff</button></div>}</section>
<section className="result-section route-card"><p className="section-label">Service Path Router</p><h2>{route.title}</h2><p>This route follows the finding; it does not change it. No purchase is required.</p><Link className="text-link" href={route.href}>{route.label} →</Link><Link className="text-link" href="/work/opportunity-review">Or request a private written judgment when booking opens →</Link></section>
{storageStatus&&<div className="storage-warning" role="alert">{storageStatus}</div>}<div className="booking-state"><strong>Triage submission is intentionally inactive.</strong><br/>Nothing on this page sends your answers to Aloha AI. A future submission route must let you preview and choose the exact subset, assistance requested, and consent before transmission.</div>
<div className="studio-actions"><button className="button-quiet" onClick={()=>setStep(Math.max(0,modules.length-1))}>Review last answer</button><button className="button-quiet" onClick={()=>{setStep(0);setAnswers([]);setPlan(emptyPlan);setHandoff(false);localStorage.removeItem("aloha-ai-opportunity-record-v1")}}>Delete local record &amp; start again</button></div><div className="result-links"><Link href="/policies">Read the Studio boundaries</Link><Link href="/support">Support and accessibility</Link></div></div><aside className="studio-note">A result is a direction—not a certification.</aside></div></section>;
const m=modules[step];return <section className="studio-shell wrap"><div className="studio-progress"><span>{m.title}</span><div className="progress-track" role="progressbar" aria-label="Studio progress" aria-valuemin={0} aria-valuemax={23} aria-valuenow={step}><i style={{width:`${step/23*100}%`}}/></div><span>{String(step+1).padStart(2,"0")} / 23</span></div><div className="studio-layout"><aside className="studio-index"><span>Catalog step</span><b>{String(step+1).padStart(2,"0")}</b><span>of twenty-three</span></aside><div className="studio-card"><p className="kicker">Opportunity Studio</p><h2 className="studio-question">{m.prompt}</h2><p className="lede">{m.why}</p><div className="options">{m.answers.map((a,i)=><button type="button" className="option" key={a.label} onClick={()=>{const next=[...answers];next[step]=a.value;setAnswers(next);setStep(step+1)}}><span className="path-num">{String(i+1).padStart(2,"0")}</span><span><b>{a.label}</b></span></button>)}</div><div className="studio-actions"><span className="privacy-line">Answers stay on this device and are not transmitted.</span><div>{step>0&&<button type="button" className="button-quiet" onClick={()=>setStep(step-1)}>Back</button>}<Link className="leave-link" href="/">Leave</Link></div></div></div><aside className="studio-note">Good questions change the conditions.</aside></div></section>}
