import type {Metadata} from "next";
import Link from "next/link";
import {SiteShell} from "../site-shell";

export const metadata:Metadata={title:"Contact RN",description:"Start a nonconfidential conversation with RN Collins about an AI workflow, research problem, decision, system, learning need, or possible engagement."};
const prompts=[["The work","What keeps recurring, breaking down, taking too long, or depending on knowledge that is difficult to find?"],["The decision","What does someone need to understand, choose, approve, stop, communicate, or build?"],["The people","Who does the work, who is affected by it, and who remains responsible for the final decision?"],["The consequence","What happens if the organization does nothing—or introduces the wrong intervention?"]];

export default function Contact(){return <SiteShell><main id="main">
 <section className="page-hero wrap"><p className="kicker">Contact RN</p><h1>Start with the work—<em>not a polished AI brief.</em></h1><p className="lede">You do not need to know what service to request. Send a short, nonconfidential description of what is happening, what needs to become clearer or easier, and why it matters.</p><div className="actions"><a className="button primary" href="https://www.linkedin.com/in/rn-collins" target="_blank" rel="noreferrer">Message RN on LinkedIn ↗</a><a className="button" href="#message-guide">Use the message guide</a></div></section>
 <section className="trust-section wrap" id="message-guide"><div className="section-head"><p className="section-label">A useful first message</p><div><h2>Four things are enough.</h2><p>Answer only what you know. A first conversation is for understanding the problem and determining whether there is a useful next step.</p></div></div><div className="trust-grid">{prompts.map((item,index)=><article key={item[0]}><span className="path-num">{String(index+1).padStart(2,"0")}</span><h3>{item[0]}</h3><p>{item[1]}</p></article>)}</div></section>
 <section className="offer-grid wrap"><article className="offer-card"><p className="section-label">Copy this structure</p><h2>Message outline</h2><ul className="scope-list"><li>Organization or context</li><li>The recurring work, friction, question, or opportunity</li><li>The people involved or affected</li><li>What you have already tried</li><li>What would become possible if the problem were made concrete</li><li>Your preferred timing for an initial conversation</li></ul></article><aside><p className="section-label">Privacy boundary</p><h2>Keep the first message nonconfidential.</h2><p>Do not send privileged, patient, student, client, employer-restricted, payment, credential, regulated, or security-sensitive information. A LinkedIn message does not create a booking, contract, professional relationship, or obligation to accept work.</p><p className="quiet-note">For the defined private-cohort AI Opportunity Clinic, review its separate scope, price, reservation, cancellation, and refund terms before submitting an inquiry.</p><Link className="text-link" href="/work/ai-opportunity-clinic">Review the Clinic →</Link></aside></section>
 </main></SiteShell>}
