import Link from "next/link";
import type {Metadata} from "next";
import {SiteShell} from "../../site-shell";
import {CourseWorkspace} from "./course-workspace";

export const metadata:Metadata={title:"Citation Verifier course",description:"Take Aloha AI’s complete eighteen-lesson course on trust-safe citation retrieval, support analysis, evaluation, and human review."};

const modules = [
  {title:"Define what verified means",summary:"Separate citation form, source existence, current status, quotation accuracy, and proposition support before choosing technology.",lessons:[
    {title:"The five different citation failures",minutes:35,body:["A citation can be malformed, point to no source, identify the wrong source, quote inaccurately, or fail to support the proposition. Those are different questions and require different evidence.","A structural parser can reject an impossible reporter series. It cannot establish that a well-formed citation exists, remains good law, or supports the sentence."],practice:"Classify ten supplied examples by failure layer and write what evidence would resolve each one."},
    {title:"The verification contract",minutes:45,body:["Define accepted inputs, covered citation families, approved sources, possible verdicts, evidence returned, abstention rules, and the person authorized to release work.","If only existence was checked, the result must not imply proposition support or current precedential status."],practice:"Complete a one-page contract with an explicit non-goal for every promised capability."}
  ]},
  {title:"Design the bounded workspace",summary:"Choose the data boundary, authority hierarchy, record structure, and human roles that govern the build.",lessons:[
    {title:"Choose the data path before the model",minutes:40,body:["Map the document from input through parsing, retrieval, model processing, human review, export, logs, and deletion. Identify every external service and every place confidential material could persist.","Use synthetic or public material until authority, contract, account settings, retention, and supervision are resolved."],practice:"Draw data-flow records for browser-local and connected builds; mark every boundary where information leaves the device."},
    {title:"Create the review-unit schema",minutes:45,body:["Store document ID, claim text, citation string, normalized citation, source snapshot, located passage, verdict, confidence, limitations, reviewer, timestamps, and version.","Keep machine output separate from human disposition. Never overwrite the evidence that produced an earlier result."],practice:"Create one known-good and one known-bad record another reviewer can reproduce."}
  ]},
  {title:"Extract citations and propositions",summary:"Turn a document into review units without pretending pattern matching understands the legal proposition.",lessons:[
    {title:"Build a transparent citation parser",minutes:60,body:["Start with a narrow citation family and deterministic patterns. Return the matched text and parsed fields so a learner can see exactly what the parser recognized.","Unknown formats should become unparsed review items, not disappear. Measure extraction recall on the document types you expect."],practice:"Test a sample plus five boundary cases and record misses without changing the labels."},
    {title:"Bind each citation to the proposition",minutes:55,body:["Capture enough context for review while preserving the exact proposition being tested.","When one sentence contains multiple claims or citations, split the review units or mark the mapping ambiguous. Do not let proximity silently become support."],practice:"Annotate a paragraph with three claims and two citations; explain every mapping boundary."}
  ]},
  {title:"Retrieve and identify the authority",summary:"Resolve a citation against an approved source and preserve the exact result a reviewer inspected.",lessons:[
    {title:"Rank sources by authority and purpose",minutes:45,body:["Use official court or government material when the task requires an authoritative rule or filing. Databases and aggregators have different coverage, licensing, status, and citator boundaries.","Record which source answered which question. A source that establishes existence may not establish current validity."],practice:"Create an approved-source hierarchy for one jurisdiction and define the fallback."},
    {title:"Retrieve, normalize, and preserve",minutes:60,body:["Normalize the query, preserve the original citation, log the source and retrieval time, and return zero, one, or multiple candidates without forcing a match.","Store a permitted snapshot or stable reference. Respect authentication, rate limits, licensing, and redistribution restrictions."],practice:"Design responses for no match, one match, and ambiguous matches."}
  ]},
  {title:"Test proposition support",summary:"Compare the proposition with the passage and distinguish direct support, qualification, conflict, silence, and ambiguity.",lessons:[
    {title:"Locate the supporting passage",minutes:55,body:["Retrieve candidate passages around meaningful terms, quotations, headings, and citations. Preserve page or paragraph locators.","Retrieval is candidate generation. The best-scoring passage is not proof that the proposition is supported."],practice:"Return the strongest candidate and a plausible distractor for three propositions."},
    {title:"Compare claim, qualification, and conflict",minutes:65,body:["Test who, what, when, jurisdiction, conditions, degree, and exceptions. A source may support a narrower proposition while the draft overstates it.","Require quoted source text, identify mismatches, and abstain when context is incomplete."],practice:"Rewrite three overstated claims to the strongest formulation their sources support."}
  ]},
  {title:"Issue bounded verdicts",summary:"Make every verdict inspectable, reversible, and no stronger than the evidence.",lessons:[
    {title:"Use a verdict taxonomy that cannot hide uncertainty",minutes:40,body:["Use labels such as structurally invalid, no source located, identity ambiguous, supported, supported with qualification, contradicted, unsupported, and not verified.","Confidence describes the basis for a provisional result; it does not convert missing evidence into support."],practice:"Assign verdicts to twelve cases and write the permitted next action."},
    {title:"Produce an inspectable review report",minutes:50,body:["Put the proposition, original citation, normalized record, source link, passage, verdict, reason, unresolved issue, reviewer status, and version in one place.","Separate machine suggestion, reviewer decision, and release decision. Make changes traceable."],practice:"Create a one-page report that lets a supervisor disagree without rerunning the system."}
  ]},
  {title:"Build the human gate",summary:"Place named review, confidentiality, escalation, and release controls around the verifier.",lessons:[
    {title:"Keep professional responsibility with the professional",minutes:55,body:["ABA Formal Opinion 512 applies existing competence, confidentiality, communication, supervision, candor, and fee duties to lawyers using generative AI. Rule 11 separately governs representations made by presenting a paper in federal civil litigation.","The verifier assists inquiry. It does not become the lawyer, editor, researcher, or accountable releaser."],practice:"Identify the approver, prohibited inputs, escalation triggers, and release evidence for a high-stakes filing."},
    {title:"Design the audit and change record",minutes:50,body:["Record the document hash or version, tool version, ruleset, sources checked, timestamps, results, overrides, reviewer, and release status.","Log enough to reconstruct the decision without retaining confidential content longer than approved."],practice:"Draft an audit record and retention rule."}
  ]},
  {title:"Evaluate failure, not fluency",summary:"Test representative errors, measure false assurance, and document coverage instead of advertising an unbounded accuracy rate.",lessons:[
    {title:"Build the failure-focused test set",minutes:60,body:["Construct cases for valid citations, malformed forms, nonexistent authorities, wrong metadata, inaccurate quotations, overstatement, contradiction, ambiguous mapping, unavailable sources, and unsupported formats.","Keep test labels independent of the system and document the coverage boundary."],practice:"Create at least twenty labeled cases, including cases designed to expose false passes."},
    {title:"Measure dangerous errors",minutes:55,body:["Report results by failure class. False passes create unwarranted assurance; false flags create review burden and may hide systematic gaps.","Do not publish one accuracy number without the dataset, denominator, labels, version, coverage, and error distribution."],practice:"Calculate a confusion matrix for each verdict family and justify a release decision."}
  ]},
  {title:"Package the verifier and its evidence",summary:"Produce a bounded implementation, evaluation report, audit record, and deployment decision.",lessons:[
    {title:"Choose prototype, pilot, or deployment",minutes:45,body:["A local demonstration, connected research pilot, governed workflow, and institutional system have different evidence, security, integration, and operational requirements.","Release only the capability level actually tested. Document exclusions and conditions required to advance."],practice:"Write a deployment memo with status, permitted users and data, limitations, and rollback trigger."},
    {title:"Defend the system without overselling it",minutes:50,body:["Present the contract, architecture, evidence, test results, limitations, human gate, and change plan. Demonstrate one success and one abstention.","A credible defense explains what the system cannot establish and shows what happens when evidence is missing."],practice:"Record a ten-minute capstone defense using only evidence in the project package."}
  ]}
];

const sources=[
  ["ABA Formal Opinion 512","https://www.americanbar.org/content/dam/aba/administrative/professional_responsibility/ethics-opinions/aba-formal-opinion-512.pdf"],
  ["Federal Rule of Civil Procedure 11","https://www.law.cornell.edu/rules/frcp/rule_11"],
  ["CourtListener documentation","https://www.courtlistener.com/help/api/"],
  ["NIST Generative AI Profile","https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf"],
  ["NIST AI Risk Management Framework 1.0","https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.100-1.pdf"]
];

export default function CitationVerifierCourse(){
  return <SiteShell><main id="main">
    <section className="page-hero wrap"><p className="kicker">Aloha AI University · open course reader</p><h1>Build a Trust-Safe <em>Citation Verifier.</em></h1><p className="lede">Build a bounded, governed system that catches malformed, unidentified, misstated, and unsupported citations before they ship.</p>
      <div className="booking-state"><strong>Open materials; enrollment closed.</strong><br/>All nine modules and eighteen lessons are readable here. Accounts, synced progress, submissions, grading, tutor access, and credentials are not available.</div>
    </section>
    <section className="wrap policy-list" aria-labelledby="curriculum"><p className="section-label">Curriculum · approximately 15 hours</p><h2 id="curriculum">Nine modules. Eighteen evidence-led lessons.</h2>
      {modules.map((module,mi)=><article key={module.title}><span className="path-num">{String(mi+1).padStart(2,"0")}</span><div><h2>{module.title}</h2><p>{module.summary}</p>{module.lessons.map((lesson,li)=><details id={`lesson-${mi*2+li+1}`} className="answer-record lesson-reader" key={lesson.title}><summary><span>Lesson {mi+1}.{li+1} · {lesson.minutes} minutes</span><strong>{lesson.title}</strong></summary><div style={{padding:"0 18px 18px"}}>{lesson.body.map(p=><p key={p}>{p}</p>)}<p><strong>Practice:</strong> {lesson.practice}</p></div></details>)}</div><span className="state-label">Open reader</span></article>)}
    </section>
    <CourseWorkspace/>
    <section className="inside-sprint"><div className="wrap sprint-grid"><div><p className="section-label">Capstone boundary</p><h2>Evidence before assurance.</h2><p>Produce a verification contract, architecture and data-flow record, bounded prototype or executable specification, independently labeled test set, per-class evaluation, audit record, human-review gate, and deployment memo.</p></div><div><h3>No credential is issued</h3><p>This public reader does not accept work, verify identity, grade submissions, or certify mastery. Keep completed work in your own records.</p><p><Link className="button" href="/learning">Return to Learning</Link></p></div></div></section>
    <section className="wrap offer-grid"><article><p className="section-label">Primary and official sources</p><h2>Source desk</h2><ul className="plain-list">{sources.map(([label,href])=><li key={href}><a href={href} rel="noreferrer">{label} ↗</a></li>)}</ul><p>Source links define the course’s governance and research baseline; they do not independently validate any learner-built system.</p></article><aside><p className="section-label">Portable by design</p><h2>Your work stays yours</h2><p>The lab kit is a plain Markdown workbook. The learning record exports as readable JSON with its non-credentialed status embedded, so it remains useful without an Aloha AI account.</p><Link className="text-link" href="/tools">Review current tools →</Link></aside></section>
  </main></SiteShell>
}
