"use client";
import {useEffect,useMemo,useState} from "react";

type GateValue="unresolved"|"pass"|"fail";
type State={title:string;hypothesis:string;scope:string;baseline:string;affectedParties:string;owner:string;reviewers:string;data:string;measures:string;disaggregation:string;monitoring:string;incident:string;stopRule:string;rollback:string;duration:string;endDecision:string;gates:Record<string,GateValue>;gateEvidence:Record<string,string>;uncertainty:string};
const STORAGE_KEY="aloha-ai-pilot-design-v1";
const gates=[
  ["purpose","Bounded purpose and hypothesis","The task, intended benefit, people affected, exclusions, duration, and testable hypothesis are defined."],
  ["evidence","Baseline, measures, and evidence plan","The current baseline, success and harm measures, disaggregation, evidence sources, and monitoring cadence are credible enough to learn."],
  ["authority","Authority, review, and affected-party input","An accountable owner, capable reviewers, and a practical route for affected-party input and contestability are named."],
  ["safeguards","Data, incident, stop, and rollback safeguards","Data authority and limits are documented, and incident, stop, rollback, and fallback paths are usable before testing."],
  ["decision","End-of-pilot decision firewall","A named authority will choose stop, revise and retest, or consider a separate deployment decision; learning value alone cannot excuse failed safeguards."],
] as const;
const blank=Object.fromEntries(gates.map(([key])=>[key,"unresolved"])) as Record<string,GateValue>;
const blankEvidence=Object.fromEntries(gates.map(([key])=>[key,""])) as Record<string,string>;
const empty:State={title:"",hypothesis:"",scope:"",baseline:"",affectedParties:"",owner:"",reviewers:"",data:"",measures:"",disaggregation:"",monitoring:"",incident:"",stopRule:"",rollback:"",duration:"",endDecision:"",gates:blank,gateEvidence:blankEvidence,uncertainty:""};
function safeParse(value:string|null):State{if(!value)return empty;try{const parsed=JSON.parse(value);return {...empty,...parsed,gates:{...blank,...parsed.gates},gateEvidence:{...blankEvidence,...parsed.gateEvidence}}}catch{return empty}}
function download(name:string,content:string,type:string){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=name;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}

export function PilotDesignKit(){
  const [state,setState]=useState<State>(empty);const [ready,setReady]=useState(false);const [message,setMessage]=useState("");
  useEffect(()=>{const restore=window.setTimeout(()=>{setState(safeParse(localStorage.getItem(STORAGE_KEY)));setReady(true)},0);return()=>window.clearTimeout(restore)},[]);
  useEffect(()=>{if(ready)localStorage.setItem(STORAGE_KEY,JSON.stringify(state))},[ready,state]);
  const blocking=useMemo(()=>gates.filter(([key])=>state.gates[key]!=="pass"),[state.gates]);
  const set=(key:keyof State,value:string)=>setState(current=>({...current,[key]:value}));
  const portable={recordType:"Aloha AI pilot design record",schemaVersion:1,exportedAt:new Date().toISOString(),notice:"Self-authored working record; not verified, approved, authorized, certified, or a deployment decision by Aloha AI.",frameworkContext:["NIST AI RMF 1.0","NIST AI RMF Playbook","GAO AI Accountability Framework"],readiness:{status:blocking.length?"DO NOT START":"All gates self-recorded as passed; required authorization and review still apply",blockingGates:blocking.map(([,label])=>label)},state};
  function markdown(){return `# ${state.title||"Untitled pilot design"}\n\n> Self-authored working record; not verified, approved, authorized, certified, or a deployment decision by Aloha AI.\n\n**Readiness:** ${blocking.length?"DO NOT START — failed or unresolved gates remain":"All five gates self-recorded as passed; required authorization and review still apply"}\n\n## Pilot frame\n\n- Hypothesis: ${state.hypothesis||"Not recorded"}\n- Scope, exclusions, and prohibited uses: ${state.scope||"Not recorded"}\n- Current baseline: ${state.baseline||"Not recorded"}\n- Duration and sample: ${state.duration||"Not recorded"}\n- Accountable owner: ${state.owner||"Not recorded"}\n- Required reviewers: ${state.reviewers||"Not recorded"}\n\n## People, evidence, and operations\n\n- Affected-party input and contestability: ${state.affectedParties||"Not recorded"}\n- Data authority and limits: ${state.data||"Not recorded"}\n- Measures: ${state.measures||"Not recorded"}\n- Disaggregation: ${state.disaggregation||"Not recorded"}\n- Monitoring: ${state.monitoring||"Not recorded"}\n- Incident handling: ${state.incident||"Not recorded"}\n\n## Precommitments\n\n- Stop conditions: ${state.stopRule||"Not recorded"}\n- Rollback and fallback: ${state.rollback||"Not recorded"}\n- End-of-pilot decision: ${state.endDecision||"Not recorded"}\n\n## Readiness gates\n\n${gates.map(([key,label])=>`### ${label}\n\n- Status: ${state.gates[key]}\n- Evidence, reviewer, date, and limits: ${state.gateEvidence[key]||"Not recorded"}`).join("\n\n")}\n\n## Uncertainty and dissent\n\n${state.uncertainty||"Not recorded"}\n\n## Deployment firewall\n\nA pilot ending does not authorize deployment. The accountable authority must record a separate decision to stop, revise and retest, or begin a distinct deployment review. Learning value cannot override a failed safeguard.\n`}
  function clear(){if(!window.confirm("Clear this pilot design from this browser?"))return;localStorage.removeItem(STORAGE_KEY);setState(empty);setMessage("Local pilot design cleared.")}
  const field=(key:keyof State,label:string,help:string)=><label className="wide"><span>{label}</span><small>{help}</small><textarea value={String(state[key])} onChange={event=>set(key,event.target.value)}/></label>;
  return <section id="workspace" className="wrap comparison-builder pilot-builder" aria-labelledby="pilot-title">
    <div className="builder-heading"><div><p className="section-label">Private working space</p><h2 id="pilot-title">Design one bounded pilot</h2><p>Nothing entered here is transmitted to Aloha AI. Do not paste confidential, privileged, personal, security-sensitive, or regulated information.</p></div><div className="comparison-rule"><strong>{blocking.length?"Do not start.":"Gates self-recorded."}</strong><span>{blocking.length?`${blocking.length} readiness gate(s) failed or unresolved.`:"Required review and authorization still apply."}</span></div></div>
    <fieldset className="record-section"><legend><span>01</span>Bound the test</legend><div className="record-fields">{field("title","Pilot title","Name one bounded test.")}{field("hypothesis","Testable hypothesis","State what should change, for whom, and what evidence could disconfirm it.")}{field("scope","Scope, exclusions, and prohibited uses","Define users, setting, workflow, consequences, and what the pilot must not do.")}{field("baseline","Current baseline","Record the current process, performance, harms, burden, and comparison method.")}{field("duration","Duration, sample, and end date","Prevent indefinite testing and quiet expansion.")}</div></fieldset>
    <fieldset className="record-section"><legend><span>02</span>Assign authority and voice</legend><div className="record-fields">{field("owner","Accountable owner","Name the person with authority to stop the pilot.")}{field("reviewers","Required reviewers","Identify domain, privacy, security, accessibility, legal, procurement, labor, or other review.")}{field("affectedParties","Affected-party input and contestability","How can affected people shape the design, report harm, challenge outcomes, and receive a response?")}</div></fieldset>
    <fieldset className="record-section"><legend><span>03</span>Precommit evidence and safeguards</legend><div className="record-fields">{field("data","Data authority, minimization, retention, and prohibited data","Record lawful authority, acceptable use, access, deletion, training restrictions, and limits.")}{field("measures","Success, harm, quality, and workload measures","Include benefits, errors, false positives/negatives, human review burden, time, cost, and unintended effects.")}{field("disaggregation","Disaggregation and equity checks","Specify which groups, contexts, or edge cases require separate examination.")}{field("monitoring","Monitoring cadence and evidence owner","Who checks what, using which sources, and how often?")}{field("incident","Incident handling and escalation","Define reporting, containment, notification, investigation, and accountable response.")}{field("stopRule","Stop conditions","Precommit thresholds or events that pause or end the pilot. Learning value cannot override them.")}{field("rollback","Rollback and fallback","Describe how to restore the prior process, preserve continuity, retrieve work, and remediate harm.")}{field("endDecision","End-of-pilot decision","Name the authority and evidence needed to choose stop, revise and retest, or consider a separate deployment review.")}</div></fieldset>
    <fieldset className="record-section"><legend><span>04</span>Readiness gates</legend><p>Every gate must be evidenced as passed before the kit can stop saying “Do not start.” This is still not authorization.</p><div className="gate-list">{gates.map(([key,label,help])=><article key={key}><div><h3>{label}</h3><p>{help}</p></div><label><span>Status</span><select value={state.gates[key]} onChange={event=>setState(current=>({...current,gates:{...current.gates,[key]:event.target.value as GateValue}}))}><option value="unresolved">Unresolved / insufficient evidence</option><option value="pass">Pass for this bounded pilot</option><option value="fail">Fail / unacceptable condition</option></select></label><label className="wide"><span>Evidence, source, date, reviewer, and limits</span><textarea value={state.gateEvidence[key]} onChange={event=>setState(current=>({...current,gateEvidence:{...current.gateEvidence,[key]:event.target.value}}))}/></label></article>)}</div></fieldset>
    <fieldset className="record-section"><legend><span>05</span>Preserve uncertainty</legend><div className="record-fields">{field("uncertainty","Unknowns, conflicting evidence, and dissent","Do not compress disagreement into a score or erase who raised it.")}</div></fieldset>
    <div className="boundary pilot-firewall"><p className="section-label">Deployment firewall</p><div><h2>A pilot is not a quiet path to production.</h2><p>The end state must be stop, revise and retest, or consider a separate deployment decision. Completion, positive averages, or learning value do not erase failed safeguards.</p></div></div>
    <div className="course-actions"><button className="button primary" type="button" onClick={()=>{download("pilot-design-record.md",markdown(),"text/markdown");setMessage("Markdown download started.")}}>Download pilot record</button><button className="button" type="button" onClick={()=>{download("pilot-design-record.json",JSON.stringify(portable,null,2),"application/json");setMessage("JSON download started.")}}>Export portable JSON</button><button className="text-button" type="button" onClick={clear}>Clear local design</button></div><p className="action-status" aria-live="polite">{message}</p>
  </section>
}
