"use client";
import {useEffect,useState} from "react";

type RecordState={title:string;version:string;status:string;owner:string;reviewers:string;decision:string;purpose:string;scope:string;alternatives:string;evidence:string;affected:string;benefits:string;harms:string;data:string;measures:string;stop:string;fallback:string;reviewDate:string;reviewTrigger:string;uncertainty:string};
const STORAGE_KEY="aloha-ai-decision-record-v1";
const empty:RecordState={title:"",version:"1.0",status:"Under review",owner:"",reviewers:"",decision:"",purpose:"",scope:"",alternatives:"",evidence:"",affected:"",benefits:"",harms:"",data:"",measures:"",stop:"",fallback:"",reviewDate:"",reviewTrigger:"",uncertainty:""};
const sections=[
  ["Decision and authority",[["title","Record title","Name this bounded decision."],["version","Version","Use a new version when reasoning or evidence changes."],["status","Current status","For example: under review, paused, rejected, bounded test, or approved by the named owner."],["owner","Accountable owner","Name the person with authority for the decision and its consequences."],["reviewers","Required reviewers","Name capable reviewers and the questions each must examine."],["decision","Decision under consideration","State the exact choice—without assuming AI is the answer."]]],
  ["Context and alternatives",[["purpose","Purpose and intended outcome","What needs to become true, and for whom?"],["scope","Permitted scope and explicit exclusions","Define users, setting, data, duration, and what this decision does not cover."],["alternatives","Alternatives considered","Include the current process, redesign, human-led work, delay, and no-action where relevant."]]],
  ["Evidence and affected people",[["evidence","Evidence register","List each dated source, what proposition it supports, and its limitations. Do not paste confidential material."],["affected","Affected people and participation","Who may benefit, bear error, repair failure, need access, or have relevant knowledge? Record how their views entered the decision."],["benefits","Expected benefits","Describe bounded, observable benefits—not promotional claims."],["harms","Potential negative impacts","Include foreseeable errors, unequal burdens, rights or livelihood effects, and downstream repair work."],["data","Data, permission, and provenance","Identify data classes, sources, authority, quality limits, retention, and prohibited inputs."]]],
  ["Test, stop, and review",[["measures","Measures and evidence needed to proceed","What would be observed, compared, and independently reviewed? State the baseline."],["stop","Stop conditions","What event, threshold, missing permission, failed safeguard, or unexpected impact requires pause or termination?"],["fallback","Fallback and repair path","How will work continue safely, and who repairs harm or incorrect output?"],["reviewDate","Next review date","Use YYYY-MM-DD when a date is known."],["reviewTrigger","Earlier review triggers","List changes in use, people, data, vendor, model, law, performance, incidents, or context that reopen the decision."],["uncertainty","Unresolved questions and dissent","Preserve what is unknown, disputed, or awaiting specialist review."]]],
] as const;
const required=["title","owner","decision","purpose","scope","alternatives","evidence","affected","stop","fallback","reviewTrigger"] as const;

function download(name:string,content:string,type:string){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=name;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function safeParse(value:string|null){if(!value)return empty;try{return {...empty,...JSON.parse(value)}}catch{return empty}}

export function DecisionRecordBuilder(){
  const [record,setRecord]=useState<RecordState>(empty);
  const [ready,setReady]=useState(false);const [message,setMessage]=useState("");
  useEffect(()=>{const restore=window.setTimeout(()=>{setRecord(safeParse(localStorage.getItem(STORAGE_KEY)));setReady(true)},0);return()=>window.clearTimeout(restore)},[]);
  useEffect(()=>{if(ready)localStorage.setItem(STORAGE_KEY,JSON.stringify(record))},[ready,record]);
  const complete=required.filter(key=>record[key].trim()).length;
  const update=(key:keyof RecordState,value:string)=>setRecord(current=>({...current,[key]:value}));
  const portable={recordType:"Aloha AI decision record",schemaVersion:1,exportedAt:new Date().toISOString(),notice:"Self-authored working record; not verified, approved, or certified by Aloha AI.",frameworkContext:["NIST AI RMF 1.0","NIST AI RMF Playbook","GAO-21-519SP"],record};
  function markdown(){return `# ${record.title||"Untitled decision record"}\n\n> Self-authored working record; not verified, approved, or certified by Aloha AI.\n\n- Version: ${record.version}\n- Status: ${record.status}\n- Accountable owner: ${record.owner||"Not recorded"}\n- Required reviewers: ${record.reviewers||"Not recorded"}\n\n${sections.map(([heading,fields])=>`## ${heading}\n\n${fields.map(([key,label])=>`### ${label}\n\n${record[key as keyof RecordState]||"Not recorded"}`).join("\n\n")}`).join("\n\n")}\n\n## Framework context\n\nNIST AI RMF 1.0; NIST AI RMF Playbook; GAO-21-519SP. These sources informed the record structure; this document does not establish conformance.\n`}
  function clear(){if(!window.confirm("Clear this decision record from this browser?"))return;localStorage.removeItem(STORAGE_KEY);setRecord(empty);setMessage("Local decision record cleared.")}
  return <section id="workspace" className="wrap decision-builder" aria-labelledby="builder-title">
    <div className="builder-heading"><div><p className="section-label">Private working space</p><h2 id="builder-title">Build the record</h2><p>Nothing entered here is transmitted to Aloha AI. Avoid confidential, privileged, personal, or regulated information unless your own authority and handling requirements are resolved.</p></div><div className="record-completeness" aria-live="polite"><strong>{complete}/{required.length}</strong><span>core fields recorded</span><progress max={required.length} value={complete}>{complete} of {required.length}</progress><small>Completeness is not quality, approval, safety, or compliance.</small></div></div>
    <form onSubmit={event=>event.preventDefault()}>{sections.map(([heading,fields],sectionIndex)=><fieldset className="record-section" key={heading}><legend><span>{String(sectionIndex+1).padStart(2,"0")}</span>{heading}</legend><div className="record-fields">{fields.map(([key,label,help])=>{const wide=!['version','status','reviewDate'].includes(key);return <label className={wide?"wide":""} key={key}><span>{label}{required.includes(key as typeof required[number])&&<b aria-label="required core field"> *</b>}</span><small>{help}</small>{['version','status','reviewDate','title','owner'].includes(key)?<input type={key==='reviewDate'?'date':'text'} value={record[key as keyof RecordState]} onChange={event=>update(key as keyof RecordState,event.target.value)}/>:<textarea value={record[key as keyof RecordState]} onChange={event=>update(key as keyof RecordState,event.target.value)}/>}</label>})}</div></fieldset>)}</form>
    <div className="course-actions"><button className="button primary" type="button" onClick={()=>{download("decision-record.md",markdown(),"text/markdown");setMessage("Markdown download started.")}}>Download readable record</button><button className="button" type="button" onClick={()=>{download("decision-record.json",JSON.stringify(portable,null,2),"application/json");setMessage("JSON download started.")}}>Export portable JSON</button><button className="text-button" type="button" onClick={clear}>Clear local record</button></div><p className="action-status" aria-live="polite">{message}</p>
  </section>
}
