import Link from "next/link";
import type {Metadata} from "next";
import {SiteShell} from "../../../site-shell";

export const metadata:Metadata={title:"Decision Desk Issue 01 · AI and Client Intake",description:"The flagship Decision Desk release unit on whether a small law firm should use AI to summarize prospective-client intake."};

const deliverables=[
  ["01","Decision Desk article","A release-ready answer that separates authority, evidence, vendor statements, observed results, RN analysis, recommendations, and unknowns."],
  ["02","Auditable Source Desk","Claim, source, pinpoint, search, contradiction, limitation, and freshness records that reconcile with the public finding."],
  ["03","Evaluation Card","Purpose, jurisdiction, matter scope, prohibited uses, authoritative record, data lifecycle, exact configuration, tests, reviewers, thresholds, stop authority, incident path, review date, and disposition."],
  ["04","Product-evidence demonstration","A frozen synthetic test of one exact product/configuration when evidence and access permit—or a transparent no-product finding without invented results."],
  ["05","Sixty-minute masterclass","A complete participatory session using supplied fictional facts, a scored Evaluation Card, safeguards, maintenance, and bounded disposition."],
  ["06","Participant package","Accessible workbook, case packet, completed example, answer key, preparation, follow-up, correction, and alternative formats."],
  ["07","Bounded clinic translation","One screened nonconfidential workflow per participant, explicit exclusions, a bounded decision record, and clear decline/referral routes."],
  ["08","Commercial journey","Discover, assess fit, register, pay, confirm, prepare, attend, receive materials, follow up, cancel/refund, and reach support."],
  ["09","Site integration and release QA","Coherent navigation plus factual, technical, visual, rights, accessibility, privacy, security, responsive, email, payment, support, and rehearsal QA with RN approval."]
];

const sequence=[
  ["0–7","Bound the intake decision","Initial decision statement"],
  ["7–16","Prospective-client duties, data boundaries, and jurisdiction","Risk-and-authority map"],
  ["16–28","Actual workflow, exceptions, handoffs, and authoritative source","Redrawn intake flow"],
  ["28–37","Exact product/configuration evidence and no-product finding","Diligence gaps"],
  ["37–49","Synthetic case and disconfirming-evidence exercise","Scored Evaluation Card"],
  ["49–57","Human review, dissent, accessibility, if–then action, and stop rules","Safeguard and maintenance set"],
  ["57–60","Disposition, owner, next evidence, and review trigger","Bounded decision"]
];

export default function Issue01(){return <SiteShell><main id="main">
  <section className="page-hero wrap"><p className="kicker">Decision Desk · flagship Issue 01</p><h1>Before You Use AI for <em>Client Intake.</em></h1><p className="lede">Should a small law firm use AI to summarize prospective-client intake? Issue 01 is the first full proof of the Decision Desk method: evidence package, product finding, instrument, masterclass, participant system, paired clinic, commercial journey, and release QA.</p><div className="actions"><a className="button primary" href="#release-unit">Inspect the release unit</a><Link className="button" href="/learning/decision-desk">View the twelve-month program</Link></div></section>
  <section className="event-status"><div className="wrap event-status-grid"><div><span>Instrument</span><strong>Intake Evaluation Card</strong></div><div><span>Teaching</span><strong>60-minute participatory class</strong></div><div><span>Evidence</span><strong>51-jurisdiction baseline</strong></div><div><span>Release state</span><strong>Built · gated</strong></div></div></section>
  <section className="wrap pathways"><div className="section-head"><div><p className="section-label">Flagship decision</p><h2>Evaluate one exact workflow and configuration.</h2></div><p>The audience is a small-law-firm owner, operations lead, supervising lawyer, legal technologist, or implementation adviser. The issue does not offer legal advice, endorse a product nationwide, claim a universal safe configuration, or authorize live prospective-client data.</p></div><article className="offer-card"><h3>Current evidence disposition</h3><p>The preserved flagship record contains a jurisdictional authority baseline, configuration dossier, fail-closed vendor/privacy review, preregistered empirical protocol, deterministic decision instrument, and frozen 24-record synthetic benchmark. The named-vendor review did not establish the exact intake feature and freezeable configuration required for nomination. The responsible fallback is a transparent no-product finding—not fabricated testing.</p></article></section>
  <section className="wrap pathways" id="release-unit"><div className="section-head"><div><p className="section-label">Binary completion contract</p><h2>Nine deliverables form one release.</h2></div><p>Individual assets may be complete without making the whole system release-ready. All nine must pass together.</p></div><div className="path-list">{deliverables.map(x=><article className="path-row" key={x[0]}><span className="path-num">{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div><span className="event-result">Required</span></article>)}</div></section>
  <section className="wrap pathways"><div className="section-head"><div><p className="section-label">Masterclass architecture</p><h2>Participants make and revise a decision.</h2></div><p>RN teaches, challenges, and synthesizes. Participants work only with supplied fictional facts and never disclose real client or prospective-client information.</p></div><div className="path-list">{sequence.map((x,i)=><article className="path-row" key={x[0]}><span className="path-num">{x[0]}</span><div><h3>{x[1]}</h3><p><strong>Participant output:</strong> {x[2]}</p></div><span className="event-result">Segment {i+1}</span></article>)}</div></section>
  <section className="offer-grid wrap"><article className="offer-card"><p className="section-label">Evaluation Card outcomes</p><h2>The instrument cannot output “legal clearance.”</h2><ul className="scope-list"><li>Reject the proposed use.</li><li>Redesign the workflow and retest.</li><li>Continue human-led work.</li><li>Authorize a separately governed bounded pilot review.</li></ul><p>The card records authority, scope, prohibited uses, source record, data lifecycle, configuration, representative tests, reviewers, thresholds, stop owner, incident route, and review date.</p></article><aside><p className="section-label">Evidence demonstration boundary</p><h2>Test only what can be frozen and evidenced.</h2><p>Use synthetic records only. Keep vendor claims, observed results, and untested assumptions separate. If evidence, permission, or configuration stability is inadequate, show the diligence and test design and publish the no-product finding.</p></aside></section>
  <section className="wrap boundary"><p className="section-label">Current release decision</p><div><h2>The flagship is built, but public enrollment is not authorized.</h2><p>The original program files include the research record, teaching package, participant assets, clinic rules, commercial specifications, accessibility remediation, visual plan, and QA records. Remaining gates include final reconciliation against one frozen candidate, current operational integrations, observed end-to-end testing, rehearsal, and RN’s explicit go/no-go approval.</p><p>This page preserves the real product and its real state. It does not replace it with a smaller fictional exercise or pretend that existing files automatically equal a safe public launch.</p><div className="actions"><Link className="button primary" href="/tools/decision-record">Open a Decision Record</Link><Link className="button" href="/learning/decision-desk">Return to the annual program</Link></div></div></section>
</main></SiteShell>}
