import Link from "next/link";
import type {Metadata} from "next";
import {SiteShell} from "../../../site-shell";

export const metadata:Metadata={title:"Decision Desk Issue 01 · AI and Client Intake",description:"Inspect the prepared but not yet approved RN-led Decision Desk edition on AI and prospective-client intake."};

const artifacts=[
  ["01","Polished teaching deck","A 36-slide editable release-candidate deck with slide-specific timing, narration notes, source boundaries, and fictional-case labels."],
  ["02","Verbatim RN script","A complete word-for-word 60-minute teaching script. RN supplies every example, answer, transition, and conclusion; delivery never depends on audience participation."],
  ["03","RN move sheet","Slide-by-slide advance, reveal, pause, reset, timing-recovery, failure, and protected-close cues for one controlled solo-RN delivery."],
  ["04","Synthetic Harborlight case","A complete fictional law-firm intake scenario, supporting artifacts, traps, disconfirming evidence, alternative outcome, model reasoning, and answer key."],
  ["05","Intake Evaluation Card","A ten-section decision instrument with fail-closed logic, four bounded outcomes, a completed fictional model, and no legal-clearance output."],
  ["06","Participant files","Editable workbook, blank card, case handout, held model answer, follow-up materials, and accessible HTML, DOCX, and print-PDF candidates."],
  ["07","Evidence and control records","Claim ledger, official-source dossier, legal-review handoff, rights and text-alternative register, controlled-change log, and blocker register."],
  ["08","Delivery support","Setup, shutdown, accessibility, failure, follow-up, transcript, caption, and platform-test materials prepared for execution."],
  ["09","Release controls","Static QA and a versioned approval package. These controls document readiness; they do not substitute for RN review, rehearsal, or real-environment testing."]
];

const sequence=[
  ["0–6","State the bounded question","RN defines the proposed intake-summary use and the limits of the session."],
  ["6–14","Separate duties, authority, and uncertainty","RN explains the general professional-responsibility frame without presenting it as jurisdiction-specific legal advice."],
  ["14–23","Map the fictional workflow","RN walks through Harborlight’s supplied facts, handoffs, source record, and failure points."],
  ["23–31","Inspect evidence and configuration gaps","RN demonstrates why vendor language, assumptions, and tested facts must remain separate."],
  ["31–43","Complete the fictional Evaluation Card","RN works the card aloud, supplies every answer, and shows why blockers cannot be overridden."],
  ["43–53","Compare the model and alternative outcome","RN reveals the prepared reasoning, misconceptions, disconfirming fact, safeguards, and stop conditions."],
  ["53–60","Record the bounded disposition","RN states Outcome C, the next evidence required, the owner, the review trigger, and the protected close."]
];

export default function Issue01(){return <SiteShell><main id="main">
  <section className="page-hero wrap"><p className="kicker">Decision Desk · flagship Issue 01</p><h1>Before You Use AI for <em>Client Intake.</em></h1><p className="lede">Should a small law firm use AI to summarize prospective-client intake? This page records the prepared RN-led edition and its honest boundary: the teaching system exists, but it has not received final RN approval or completed real delivery-environment testing, so enrollment and booking remain closed.</p><div className="actions"><a className="button primary" href="#release-candidate">Inspect what is built</a><Link className="button" href="/learning/decision-desk">View the twelve-month plan</Link></div></section>
  <section className="event-status"><div className="wrap event-status-grid"><div><span>Instrument</span><strong>Intake Evaluation Card</strong></div><div><span>Teaching</span><strong>60-minute solo-RN edition</strong></div><div><span>Audience input</span><strong>Not required</strong></div><div><span>Release state</span><strong>Candidate · not approved</strong></div></div></section>
  <section className="wrap pathways"><div className="section-head"><div><p className="section-label">Flagship decision</p><h2>Evaluate one fictional workflow without inventing evidence.</h2></div><p>The prepared edition is for small-firm owners, operations leads, supervising lawyers, legal technologists, and implementation advisers. It does not give legal advice, endorse a product, claim a universal safe configuration, authorize a pilot, or request real client or prospective-client information.</p></div><article className="offer-card"><h3>Current evidence disposition</h3><p>The release candidate teaches with the fully fictional Harborlight case, a deterministic Evaluation Card, and general or model authority that remains expressly noncontrolling. No jurisdiction, real firm, product configuration, empirical benchmark, or live workflow has been validated. The prepared model therefore continues human-led work while identifying the separate evidence and authorization a bounded pilot review would require.</p></article></section>
  <section className="wrap pathways" id="release-candidate"><div className="section-head"><div><p className="section-label">Prepared release candidate</p><h2>The large teaching package is real.</h2></div><p>These artifacts are complete enough for controlled RN review and rehearsal. They are not yet approved public downloads or proof that a live session can be sold and delivered.</p></div><div className="path-list">{artifacts.map(x=><article className="path-row" key={x[0]}><span className="path-num">{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div><span className="event-result">Prepared</span></article>)}</div></section>
  <section className="wrap pathways"><div className="section-head"><div><p className="section-label">RN-controlled teaching arc</p><h2>RN teaches the entire class.</h2></div><p>Participants may listen or reflect privately, but RN never waits for an answer, calls on anyone, requests a disclosure, or needs audience input to complete the lesson.</p></div><div className="path-list">{sequence.map((x,i)=><article className="path-row" key={x[0]}><span className="path-num">{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div><span className="event-result">Segment {i+1}</span></article>)}</div></section>
  <section className="offer-grid wrap"><article className="offer-card"><p className="section-label">Evaluation Card outcomes</p><h2>The instrument cannot output “legal clearance.”</h2><ul className="scope-list"><li>Reject the proposed use.</li><li>Redesign the workflow and retest.</li><li>Continue human-led work.</li><li>Seek separate authorization for a bounded pilot review.</li></ul><p>The prepared Harborlight model produces “continue human-led work.” Text presence never equals evidence, uncertainty defaults to restraint, and no blocker can silently disappear.</p></article><aside><p className="section-label">What remains before release</p><h2>Human and real-environment gates are still open.</h2><p>RN must approve the exact voice, visuals, and files and complete the timed rehearsal. The final package also needs executed PowerPoint and assistive-technology checks, room or webinar tests, human caption review, legal and policy review, service operations, support ownership, and RN’s dated go/no-go decision.</p></aside></section>
  <section className="wrap boundary"><p className="section-label">Current release decision</p><div><h2>Prepared for RN review. Not available to book.</h2><p>The content and production package are substantial and specific: deck, complete narration, every teaching move, case, instrument, participant files, evidence controls, captions, and delivery plans. What remains cannot honestly be replaced by an agent checking a box—it requires RN judgment, authorized reviewers, and execution in the actual delivery environment.</p><p>No live seat, reservation, checkout, Clinic, or participant download is available from this page.</p><div className="actions"><Link className="button primary" href="/tools/decision-record">Use the public Decision Record</Link><Link className="button" href="/learning/decision-desk">Return to the annual plan</Link></div></div></section>
</main></SiteShell>}
