import Link from "next/link";
import type {Metadata} from "next";
import {SiteShell} from "../site-shell";

export const metadata:Metadata={title:"Ways to work together",description:"Use Aloha AI’s self-directed tools, review the defined Opportunity Clinic, and inspect honest boundaries around candidate facilitated work."};

const paths=[
 {n:"01",name:"Opportunity Clinic",state:"defined · inquiry conditional",when:"An existing team or private cohort has one bounded, group-safe problem for a 90-minute facilitated inquiry.",href:"/work/ai-opportunity-clinic"},
 {n:"02",name:"Decision Record Review",state:"candidate · unavailable",when:"One consequential decision needs evidence, assumptions, ownership, and review preserved.",href:"/work/ai-decision-review"},
 {n:"03",name:"Workflow Conditions Inquiry",state:"candidate · unavailable",when:"A recurring workflow is fragile or unclear and needs examination before technology is chosen.",href:"/work/workflow-diagnostic-redesign"},
 {n:"04",name:"Requirements & Evidence Comparison",state:"candidate · unavailable",when:"A defined use case needs a bounded comparison without automatic ranking or recommendation.",href:"/work/ai-tool-vendor-decision"},
 {n:"05",name:"Pilot Decision Protocol",state:"candidate · unavailable",when:"A bounded intervention may be ready for a test with explicit measures and stop conditions.",href:"/work/prototype-pilot-sprint"},
 {n:"06",name:"AI Operating Partnership",state:"candidate · unavailable",when:"A defined portfolio may require continuing senior judgment and implementation ownership.",href:"/work/ai-operating-partnership"},
 {n:"07",name:"Custom Organizational Program",state:"candidate · unavailable",when:"Two or more independently validated modules may need coordination around one institutional outcome.",href:"/work/custom-organizational-program"},
];

export default function Work(){return <SiteShell><main id="main">
 <section className="page-hero wrap"><p className="kicker">Ways to work together</p><h1>Start with the decision the work requires—<em>not a menu of AI nouns.</em></h1><p className="lede">The Opportunity Clinic has a defined protocol, and private-cohort scope conversations may open when the secure inquiry is configured. Public booking, payment, and every other facilitated service remain unavailable.</p></section>
 <section className="offer-grid wrap"><article className="offer-card"><p className="section-label">Usable now · self-directed</p><h2>Leave with a record you control.</h2><ul className="scope-list"><li><Link href="/learning/masterclass">Free AI decision guide</Link> — five concise prompts and a working guide</li><li><Link href="/studio">Opportunity Studio</Link> — a guided, rule-based prototype for examining one workflow</li><li><Link href="/tools/decision-record">Decision Record Builder</Link> — preserve one accountable decision</li><li><Link href="/tools/vendor-comparison">Tool &amp; Vendor Comparison Builder</Link> — compare three fixed options without erasing safeguards</li><li><Link href="/tools/pilot-design">Pilot Design Kit</Link> — precommit rules for a bounded test</li><li><Link href="/learning/citation-verifier">Citation Verifier reader</Link> — eighteen concise notes and practices</li></ul><Link className="button primary" href="/start">Choose your starting point</Link></article><aside><p className="section-label">Commercial status</p><h2>One defined facilitated offer; no false checkout.</h2><p>The Clinic’s protocol, capacity, duration, deliverables, accessibility practices, price, and cancellation terms are public. Its inquiry begins only a nonconfidential cohort conversation when the form is visibly enabled; public booking and payment remain inactive. The other facilitated records below are candidate concepts, not available services.</p><Link className="text-link" href="/procurement">Review procurement readiness →</Link></aside></section>
 <section className="wrap pathways"><p className="section-label">Facilitated work</p><div className="path-list">{paths.map(path=><article className="path-row" key={path.n}><span className="path-num">{path.n}</span><div><h3>{path.name}</h3><p>{path.when}</p></div><Link href={path.href}>{path.n==="01"?"Review format, price, terms, and inquiry status":"Inspect the candidate record"} <span>→</span></Link></article>)}</div></section>
</main></SiteShell>}
