import Link from "next/link";
import type {Metadata} from "next";
import {SiteShell} from "../site-shell";

export const metadata:Metadata={title:"Work with RN",description:"Bring RN Collins a complex AI, research, workflow, decision, learning, or organizational problem and determine the useful next move."};
const method=[["01","Research and understand","RN examines the entity, the people, the evidence, the context, and how the work actually moves."],["02","Expose the hidden structure","Recurring friction, gaps, dependencies, risks, assumptions, and decisions become concrete and visible."],["03","Choose the useful intervention","The answer may be a strategy, brief, workflow, tool, learning experience, prototype, facilitated session, or a different path entirely."],["04","Build and hand off","The work is made usable, bounded, reviewable, and honest about what remains unresolved."]];

export default function Work(){return <SiteShell><main id="main">
 <section className="page-hero wrap"><p className="kicker">Work with RN</p><h1>Bring the problem.<br/><em>We will determine the work.</em></h1><p className="lede">RN researches the organization and the work, finds the gaps or pressure points, makes them concrete and visible, and then researches, designs, drafts, builds, facilitates, or strategizes what the situation requires.</p><div className="actions"><Link className="button primary" href="/contact">Start a conversation</Link><Link className="button" href="/work/ai-opportunity-clinic">Review the Opportunity Clinic</Link></div></section>
 <section className="trust-section wrap"><div className="section-head"><p className="section-label">How RN works</p><div><h2>The scope follows the problem.</h2><p>You do not have to translate the situation into a predetermined consulting package before reaching out.</p></div></div><div className="trust-grid">{method.map(item=><article key={item[0]}><span className="path-num">{item[0]}</span><h3>{item[1]}</h3><p>{item[2]}</p></article>)}</div></section>
 <section className="offer-grid wrap"><article className="offer-card"><p className="section-label">Use now · self-directed</p><h2>Learn, examine, or preserve a decision.</h2><ul className="scope-list"><li><Link href="/learning/masterclass">AI &amp; Your Work</Link> — complete self-paced flagship masterclass</li><li><Link href="/learning/decision-desk">Decision Desk</Link> — twelve-month plan with issue-level readiness</li><li><Link href="/studio">Opportunity Studio</Link> — examine one workflow</li><li><Link href="/tools/decision-record">Decision Record Builder</Link> — preserve one accountable decision</li><li><Link href="/tools/vendor-comparison">Tool &amp; Vendor Comparison</Link> — compare options without erasing safeguards</li><li><Link href="/tools/pilot-design">Pilot Design Kit</Link> — precommit rules for a bounded test</li><li><Link href="/learning/citation-verifier">Citation Verifier course</Link> — eighteen-lesson system-design curriculum</li></ul><Link className="button primary" href="/start">Choose a public starting point</Link></article><aside><p className="section-label">Commercial status</p><h2>A conversation is not a contract.</h2><p>Contacting RN begins only a nonconfidential conversation about the situation and whether a useful scope exists. The Opportunity Clinic is the only facilitated format with published scope, price, reservation, cancellation, and refund terms. Its secure inquiry and public checkout remain inactive unless the Clinic page visibly says otherwise.</p><Link className="text-link" href="/procurement">Review current procurement information →</Link></aside></section>
 <section className="boundary wrap"><p className="section-label">Developing formats</p><div><h2>The rest of the service architecture is not for sale yet.</h2><p>Decision review, workflow inquiry, vendor comparison, pilot design, continuing partnership, and custom organizational program records remain candidate formats. They are unpriced and unavailable until their evidence, operations, terms, and fulfillment are complete.</p></div></section>
 </main></SiteShell>}
