import Link from "next/link";
import {SiteShell} from "../site-shell";
const paths=[
 {n:"01",name:"Opportunity Clinic",state:"candidate · unavailable",when:"A bounded, group-safe problem may benefit from facilitated inquiry.",href:"/work/ai-opportunity-clinic"},
 {n:"02",name:"Decision Record Review",state:"candidate · unavailable",when:"One consequential decision needs evidence, assumptions, ownership, and review preserved.",href:"/work/ai-decision-review"},
 {n:"03",name:"Workflow Conditions Inquiry",state:"candidate · unavailable",when:"A recurring workflow is fragile or unclear and needs examination before technology is chosen.",href:"/work/workflow-diagnostic-redesign"},
 {n:"04",name:"Requirements & Evidence Comparison",state:"candidate · unavailable",when:"A defined use case needs a bounded comparison without automatic ranking or recommendation.",href:"/work/ai-tool-vendor-decision"},
 {n:"05",name:"Pilot Decision Protocol",state:"candidate · unavailable",when:"A bounded intervention may be ready for a test with explicit measures and stop conditions.",href:"/work/prototype-pilot-sprint"},
 {n:"06",name:"AI Operating Partnership",state:"candidate · unavailable",when:"A defined portfolio may require continuing senior judgment and implementation ownership.",href:"/work/ai-operating-partnership"},
];
export default function Work(){return <SiteShell><main id="main"><section className="page-hero wrap"><p className="kicker">Ways to work together</p><h1>Start with the decision the work requires—<em>not a menu of AI nouns.</em></h1><p className="lede">Aloha AI’s facilitated services are not open for booking yet. You can still make useful progress now with the public tools, course, and evidence records below.</p></section><section className="offer-grid wrap"><article className="offer-card"><p className="section-label">Usable now · self-directed</p><h2>Leave with a record you control.</h2><ul className="scope-list"><li><Link href="/studio">Opportunity Studio</Link> — decide whether AI belongs in one workflow</li><li><Link href="/tools/decision-record">Decision Record Builder</Link> — preserve one accountable decision</li><li><Link href="/tools/vendor-comparison">Tool &amp; Vendor Comparison Builder</Link> — compare options without erasing safeguards</li><li><Link href="/tools/pilot-design">Pilot Design Kit</Link> — precommit the rules for a bounded test</li><li><Link href="/learning/citation-verifier">Citation Verifier course</Link> — learn and practice trust-safe evaluation</li></ul><Link className="button primary" href="/start">Choose your starting point</Link></article><aside><p className="section-label">Commercial status</p><h2>No false booking path.</h2><p>Facilitated scope, capacity, duration, support, pricing, and intake are still being validated. The candidate records below show the work under consideration without implying that it can currently be purchased.</p><Link className="text-link" href="/procurement">Review procurement readiness →</Link></aside></section><section className="wrap pathways"><p className="section-label">Facilitated work under validation</p><div className="path-list">{paths.map(o=><article className="path-row" key={o.n}><span className="path-num">{o.n}</span><div><h3>{o.name}</h3><p>{o.when}</p></div><Link href={o.href}>Review its boundaries <span>→</span></Link></article>)}</div></section></main></SiteShell>}
