import Link from "next/link";
import type {Metadata} from "next";
import {SiteShell} from "../site-shell";

export const metadata:Metadata={title:"Learning",description:"Use the 90-minute Aloha AI flagship masterclass, Citation Verifier course, or inspect the twelve-month Decision Desk program."};

export default function Learning(){return <SiteShell><main id="main">
  <section className="page-hero wrap"><p className="kicker">Learning · flagship curriculum and governed programs</p><h1>Learn before <em>you automate.</em></h1><p className="lede">Take the complete 90-minute AI &amp; Your Work flagship masterclass, study the 15-hour Citation Verifier course, or inspect the canonical twelve-month Decision Desk program and its first flagship issue.</p></section>
  <section className="offer-grid wrap">
    <article className="offer-card"><p className="section-label">Complete open course · 15+ hours</p><h2>Build a Trust-Safe Citation Verifier</h2><p>Eighteen timed lessons and applied practices on citation failure, retrieval, proposition support, bounded verdicts, human review, and failure-focused evaluation.</p><Link className="text-link" href="/learning/citation-verifier">Start the course →</Link><div className="booking-state"><strong>Complete self-directed edition.</strong><br/>Includes a seven-part lab kit, eighteen-question knowledge check, local progress, capstone package, defense prompt, rubric, and portable record. No grading or credential.</div></article>
    <article className="offer-card"><p className="section-label">Complete flagship masterclass · 90 minutes</p><h2>AI &amp; Your Work</h2><p>Examine friction, inputs, judgment, risk, and value through the complete Define → Examine → Decide → Build method and the prepared Kōkua Studio case.</p><Link className="text-link" href="/learning/masterclass">Begin the flagship masterclass →</Link><div className="booking-state"><strong>Completed teaching system.</strong><br/>Includes 24 chapters, the Opportunity Map, fictional case, four findings, intervention ladder, experiment and system design, Hawaiʻi operating context, workbook, Monday Plan, and facilitated-delivery controls.</div></article>
    <article className="offer-card"><p className="section-label">Canonical annual program · Sep 2026–Aug 2027</p><h2>Decision Desk</h2><p>Twelve distinct governed questions, masterclasses, instruments, and paired clinics—from client intake and meeting capture through agent authority, vendor choice, and AI retirement.</p><Link className="text-link" href="/learning/decision-desk">Inspect the twelve-month program →</Link><div className="booking-state"><strong>The architecture is complete; readiness varies.</strong><br/>Issue 01 has a substantial gated flagship package. Issue 02 has partial governed research. Issue 03 has a defined research question. Issues 04–12 remain planned production units.</div></article>
    <aside><p className="section-label">Facilitated service · defined separately</p><h2>Opportunity Clinic</h2><p>A 90-minute remote working session for an existing team or private cohort of up to six people. Price: $275 per participant. It is a service, not a course. Public checkout is not active.</p><Link className="text-link" href="/work/ai-opportunity-clinic">Review the Clinic protocol and terms →</Link></aside>
  </section>
</main></SiteShell>}
