import Link from "next/link";
import type {Metadata} from "next";
import {SiteShell} from "../site-shell";

export const metadata:Metadata={title:"Learning",description:"Use the complete 24-chapter Aloha AI flagship masterclass, Citation Verifier course, or inspect the twelve-month Decision Desk program."};

export default function Learning(){return <SiteShell><main id="main">
  <section className="page-hero wrap"><p className="kicker">Courses and masterclasses</p><h1>Learn before <em>you automate.</em></h1><p className="lede">Take the complete 24-chapter AI &amp; Your Work self-paced flagship masterclass, study the 15-hour Citation Verifier course, or explore the twelve-month Decision Desk plan and see exactly which issues are ready to use.</p></section>
  <section className="offer-grid wrap">
    <article className="offer-card"><p className="section-label">Complete open course · 15+ hours</p><h2>Build a Trust-Safe Citation Verifier</h2><p>Eighteen timed lessons and applied practices on citation failure, retrieval, proposition support, bounded verdicts, human review, and failure-focused evaluation.</p><Link className="text-link" href="/learning/citation-verifier">Start the course →</Link><div className="booking-state"><strong>Complete self-directed edition.</strong><br/>Includes a seven-part lab kit, eighteen-question knowledge check, local progress, capstone package, defense prompt, rubric, and portable record. No grading or credential.</div></article>
    <article className="offer-card"><p className="section-label">Complete self-paced flagship · 24 chapters</p><h2>AI &amp; Your Work</h2><p>Examine friction, inputs, judgment, risk, and value through the complete Define → Examine → Decide → Build method and the prepared Kōkua Studio case.</p><Link className="text-link" href="/learning/masterclass">Begin the flagship masterclass →</Link><div className="booking-state"><strong>Available now: complete self-paced web edition.</strong><br/>Includes 24 chapters totaling 105 minutes of labeled lesson time, the Opportunity Map, fictional case, four findings, intervention ladder, experiment and system design, Hawaiʻi operating context, workbook, and Monday Plan. Allow about two hours. The separate RN-led live edition is still in release review and is not open for booking.</div></article>
    <article className="offer-card"><p className="section-label">Twelve-month learning plan · Sep 2026–Aug 2027</p><h2>Decision Desk</h2><p>Twelve practical AI decisions and reusable instruments—from client intake and meeting capture through agent authority, vendor choice, and AI retirement.</p><Link className="text-link" href="/learning/decision-desk">Inspect the twelve-month program →</Link><div className="booking-state"><strong>The plan is published; live-delivery readiness is separate.</strong><br/>Issue 01 has a prepared 36-slide RN-led release candidate with complete narration and teaching moves, but it is not approved or bookable. Issues 02–11 are complete public self-paced editions with their own decision instruments. Issue 12 remains planned and unbuilt. No live monthly enrollment is open.</div></article>
    <aside><p className="section-label">Facilitated service · defined separately</p><h2>Opportunity Clinic</h2><p>A 90-minute remote working session for an existing team or private cohort of up to six people. Price: $275 per participant. It is a service, not a course. Public checkout is not active.</p><Link className="text-link" href="/work/ai-opportunity-clinic">Review the Clinic protocol and terms →</Link></aside>
  </section>
</main></SiteShell>}
