export type PublicRecord={type:string;title:string;summary:string;status:string;problem:string;href:string};
const issueTitles=["Should a Small Law Firm Use AI for Client Intake?","Before the Bot Joins the Meeting","Should AI Answer Your Customers?","Can Your AI Find the Right Answer?","Should AI Help Choose People?","Can You Prove That AI-Written Claim?","Can People Trust This AI Explanation?","Can You Use Someone’s AI Voice or Image?","What Should Your AI Agent Be Allowed to Do?","What to Check Before Buying an AI Tool","Should AI Review a Student’s Work?","Is It Time to Stop Using This AI?"];
export const publicCatalog:PublicRecord[]=[
 {type:"Start",title:"Start Here",summary:"Choose a course, free tool, or way to work with RN based on the situation you face.",status:"Available",problem:"Find a starting point",href:"/start"},
 {type:"Tool",title:"Opportunity Studio",summary:"A browser-local 23-prompt prototype for examining AI fit and workflow readiness.",status:"Guided prototype",problem:"AI fit and workflow readiness",href:"/studio"},
 {type:"Tool",title:"Decision Record Builder",summary:"Preserve an accountable decision, evidence, uncertainty, fallback, and review date.",status:"Working public builder",problem:"One accountable decision",href:"/tools/decision-record"},
 {type:"Tool",title:"Tool & Vendor Comparison Builder",summary:"Compare a current process and two candidates against gates and weighted criteria.",status:"Working public builder",problem:"Bounded option comparison",href:"/tools/vendor-comparison"},
 {type:"Tool",title:"Pilot Design Kit",summary:"Precommit a pilot hypothesis, baseline, measures, authority, stop conditions, and rollback.",status:"Working public builder",problem:"Bounded pilot planning",href:"/tools/pilot-design"},
 {type:"Learning",title:"AI & Your Work Flagship Masterclass",summary:"The complete 105-minute, 24-chapter flagship with exercises, knowledge check, and local learning record.",status:"Complete flagship curriculum",problem:"Examine work before automation",href:"/learning/masterclass"},
 {type:"Learning",title:"Citation Verifier Course",summary:"A complete 15-hour course with eighteen lessons, lab kit, capstone, rubric, and local progress record.",status:"Complete open edition",problem:"Citation verification system design",href:"/learning/citation-verifier"},
 ...issueTitles.map((title,index)=>({type:"Program",title:`Decision Desk · Issue ${String(index+1).padStart(2,"0")} · ${title}`,summary:"A complete or explicitly gated public learning record for one consequential AI decision.",status:index===0?"Release gated":"Complete public learning edition",problem:"Consequential AI decision",href:`/learning/decision-desk/issue-${String(index+1).padStart(2,"0")}`})),
 {type:"Service",title:"Opportunity Clinic",summary:"A defined 90-minute facilitated session for an existing team or private cohort.",status:"Defined · no public checkout",problem:"Collaborative workflow inquiry",href:"/work/ai-opportunity-clinic"},
 {type:"Organization",title:"Work with RN",summary:"Bring RN a recurring problem, consequential decision, or difficult body of work.",status:"Conversation available",problem:"Organizational AI work",href:"/work"},
 {type:"Evidence",title:"Source Desk",summary:"Twelve method claims and all twelve Decision Desk issues mapped to seventeen official records.",status:"Published evidence register",problem:"Evidence-led AI decisions",href:"/insights"},
 {type:"Standard",title:"Policies",summary:"Plain-language boundaries for local data, inquiries, evidence, accessibility, advice, and commerce.",status:"Current public boundaries",problem:"Rules and privacy",href:"/policies"},
 {type:"Support",title:"Support and Accessibility",summary:"Keyboard, zoom, motion, privacy, recovery, accommodation, and emergency boundaries.",status:"Information only",problem:"Access or site support",href:"/support"},
 {type:"About",title:"About RN Collins and Aloha AI",summary:"The practice method, selected public work, and professional boundaries.",status:"Published profile",problem:"Who built the practice",href:"/about"},
];
