import Link from "next/link";
import type {Metadata} from "next";
import {SiteShell} from "../site-shell";

export const metadata:Metadata={title:"Source Desk",description:"Inspect the official-source register, public claim map, Decision Desk coverage, limits, and review controls behind Aloha AI’s methods, courses, and tools."};

const sources=[
 {id:"S01",name:"NIST AI Risk Management Framework 1.0",issuer:"U.S. National Institute of Standards and Technology",date:"January 2023",use:"Risk governance vocabulary and the Govern–Map–Measure–Manage lifecycle across decision, pilot, monitoring, and retirement records.",limit:"Voluntary, cross-sector framework; it does not certify a system or replace applicable law, contracts, policy, or sector review.",href:"https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-ai-rmf-10"},
 {id:"S02",name:"NIST AI RMF Playbook",issuer:"U.S. National Institute of Standards and Technology",date:"Living resource",use:"Suggested actions and documentation practices for operationalizing AI RMF outcomes through the system lifecycle.",limit:"Illustrative and voluntary; actions must be selected and adapted, and citation does not establish conformance.",href:"https://www.nist.gov/itl/ai-risk-management-framework/nist-ai-rmf-playbook"},
 {id:"S03",name:"Generative AI Profile",issuer:"U.S. National Institute of Standards and Technology",date:"July 2024",use:"Generative-AI risk, measurement, provenance, incident, human-oversight, and uncertainty prompts.",limit:"Cross-sector profile; not a product test, legal safe harbor, or complete control catalog.",href:"https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence"},
 {id:"S04",name:"AI Accountability Framework",issuer:"U.S. Government Accountability Office",date:"June 2021",use:"Governance, data, performance, and monitoring dimensions used in evidence and accountability records.",limit:"Oversight framework; it does not prescribe one implementation or validate user-entered evidence.",href:"https://www.gao.gov/products/gao-21-519sp"},
 {id:"S05",name:"Web Content Accessibility Guidelines 2.2",issuer:"World Wide Web Consortium",date:"October 2023",use:"Public-interface accessibility baseline and affected-user access prompts.",limit:"Conformance requires criterion-specific testing; a worksheet reference is not an accessibility audit.",href:"https://www.w3.org/TR/WCAG22/"},
 {id:"S06",name:"Section 508 Standards",issuer:"U.S. Access Board",date:"Official standards page",use:"Accessibility procurement and ICT context for relevant U.S. federal uses.",limit:"Applicability depends on the setting and authority; Aloha AI tools do not determine coverage.",href:"https://www.access-board.gov/ict/"},
 {id:"S07",name:"Secure by Design",issuer:"U.S. Cybersecurity and Infrastructure Security Agency",date:"Current initiative",use:"Security ownership, safe-default, vulnerability, and supplier-evidence prompts in comparison, agent, and pilot tools.",limit:"General security principles; not a security assessment, threat model, or candidate evaluation.",href:"https://www.cisa.gov/securebydesign"},
 {id:"S08",name:"ABA Formal Opinion 512",issuer:"American Bar Association Standing Committee on Ethics and Professional Responsibility",date:"July 2024",use:"Model-rule professional-responsibility context for the Citation Verifier and fictional legal-intake teaching case.",limit:"Addresses ABA Model Rules; it is not controlling jurisdiction-specific legal advice.",href:"https://www.americanbar.org/content/dam/aba/administrative/professional_responsibility/ethics-opinions/aba-formal-opinion-512.pdf"},
 {id:"S09",name:"Employment Tests and Selection Procedures",issuer:"U.S. Equal Employment Opportunity Commission",date:"December 2007",use:"Federal employment-selection context for job-relatedness, business necessity, disparate treatment, disparate impact, and validation questions.",limit:"Technical assistance with an express nonbinding disclaimer; exact coverage and obligations require authorized review.",href:"https://www.eeoc.gov/laws/guidance/employment-tests-and-selection-procedures"},
 {id:"S10",name:"ADA and Software, Algorithms, and AI in Employment",issuer:"U.S. Equal Employment Opportunity Commission",date:"May 2022",use:"Disability, accommodation, screen-out, and vendor-tool questions in learner- and opportunity-affecting reviews.",limit:"Federal ADA technical assistance; it does not assess a tool, person, job, accommodation, or employment decision.",href:"https://www.eeoc.gov/laws/guidance/americans-disabilities-act-and-use-software-algorithms-and-artificial-intelligence"},
 {id:"S11",name:"Consumer Financial Protection Circular 2022-03",issuer:"U.S. Consumer Financial Protection Bureau",date:"May 2022",use:"A bounded federal credit example showing that complex algorithms do not eliminate a duty to provide specific and accurate adverse-action reasons.",limit:"Credit-specific ECOA and Regulation B context; it does not create a universal explanation rule for every AI use.",href:"https://www.consumerfinance.gov/compliance/circulars/circular-2022-03-adverse-action-notification-requirements-in-connection-with-credit-decisions-based-on-complex-algorithms/"},
 {id:"S12",name:"Final Order Against Workado",issuer:"U.S. Federal Trade Commission",date:"August 2025",use:"Public example of accuracy and efficacy claims requiring competent, reliable support that fits the actual content and use represented.",limit:"Company- and order-specific enforcement record; it is not a universal testing protocol or adjudication of another claim.",href:"https://www.ftc.gov/news-events/news/press-releases/2025/08/ftc-approves-final-order-against-workado-llc-which-misrepresented-accuracy-its-artificial"},
 {id:"S13",name:"Reducing Risks Posed by Synthetic Content",issuer:"U.S. National Institute of Standards and Technology",date:"November 2024; updated April 2026",use:"Provenance, labeling, detection, testing, auditing, and maintenance frame for synthetic-content records.",limit:"Technical overview; provenance and detection tools have limits and do not by themselves establish permission or authenticity.",href:"https://www.nist.gov/publications/reducing-risks-posed-synthetic-content-overview-technical-approaches-digital-content"},
 {id:"S14",name:"Copyright and Artificial Intelligence · Part 1: Digital Replicas",issuer:"U.S. Copyright Office",date:"July 2024",use:"Federal policy context for digital replicas, voice, likeness, and gaps in existing protection.",limit:"Policy report and recommendations; it does not decide ownership, consent, publicity, contract, platform, or jurisdiction-specific rights.",href:"https://www.copyright.gov/AI/"},
 {id:"S15",name:"Artificial Intelligence and the Future of Teaching and Learning",issuer:"U.S. Department of Education, Office of Educational Technology",date:"May 2023",use:"Human-centered teaching, learning, formative assessment, educator responsibility, and research-and-development questions.",limit:"Policy report; it does not approve a classroom tool, determine educational validity, or resolve local and legal requirements.",href:"https://tech.ed.gov/ai-future-of-teaching-and-learning/"},
 {id:"S16",name:"Student Privacy Policy Office",issuer:"U.S. Department of Education",date:"Current office record",use:"Route to current federal FERPA, PPRA, data-governance, disclosure, vendor, and student-privacy guidance.",limit:"Office and guidance collection; applicability depends on the institution, record, role, authority, agreement, and disclosure.",href:"https://www.ed.gov/about/ed-offices/opepd/student-privacy-policy-office"},
 {id:"S17",name:"AI Accountability Policy Report",issuer:"U.S. National Telecommunications and Information Administration",date:"March 2024",use:"Disclosure, documentation, evaluation, audit, access, claim-validation, procurement, and accountability-chain questions.",limit:"Policy recommendations rather than a certification rule; independent evaluation does not replace regulatory or organizational authority.",href:"https://www.ntia.gov/issues/artificial-intelligence/ai-accountability-policy-report"}
];

const claims=[
 ["C01","AI decisions require named governance, context, measurement, and response—not a capability demonstration alone.","S01, S02, S04","Decision records, pilot gates, monitoring, and retirement review.","Completion of a worksheet does not establish readiness or conformance."],
 ["C02","Generative-AI review must preserve uncertainty, provenance, human oversight, incidents, and disconfirming evidence.","S03, S13, S17","Citation, explanation, synthetic-content, agent, and retirement records.","The tools do not independently test truth, performance, permission, or authenticity."],
 ["C03","Accessibility is an operating requirement that must be tested against applicable criteria and affected-user conditions.","S05, S06","Interface QA, procurement prompts, participant formats, and access gates.","No accessibility certification or legal-coverage decision is provided."],
 ["C04","Security and supplier claims require evidence, ownership, safe defaults, incident routes, and exit planning.","S01, S07, S17","Vendor, pilot, agent-authority, and retirement instruments.","No penetration test, threat model, vendor diligence, or security approval is performed."],
 ["C05","Using generative AI does not transfer professional responsibility away from authorized people.","S08","Citation Verifier and the fictional Issue 01 intake case.","Model-rule education only; controlling duties and facts require separate review."],
 ["C06","Selection systems must be examined for relevance, validation, unequal exclusion, disability barriers, accommodation, and accountable human judgment.","S09, S10","Issue 05 opportunity-impact review.","No employment, psychometric, disability, accommodation, or individual decision is evaluated."],
 ["C07","A complex model may still need to produce reasons that are specific, accurate, and connected to the factors actually used where governing authority requires them.","S11","Issue 07 explanation-fidelity teaching and challenge-path prompts.","The cited requirement is credit-specific and is not generalized into universal law."],
 ["C08","Objective AI accuracy and efficacy claims need evidence that fits the represented task, population, content, and conditions.","S12, S17","Issue 06 substantiation gate and vendor-evidence records.","One enforcement order does not supply a universal evidence threshold for every claim."],
 ["C09","Synthetic-media provenance, detection, labeling, permission, and rights are separate questions.","S13, S14","Issue 08 permission and provenance record.","Technical provenance does not prove consent, ownership, legality, or truth."],
 ["C10","AI affecting learning must preserve the learning purpose, educator responsibility, access, privacy, validity, challenge, and support.","S05, S15, S16","Issue 11 learner-affecting use review.","No pedagogical, institutional, privacy, accessibility, or legal approval is provided."],
 ["C11","Documentation and evaluation are accountability inputs; they matter only when connected to owners, decisions, consequences, and continued review.","S01, S04, S17","All public tools and Decision Desk instruments.","A self-assessment is not an independent audit or organizational authorization."],
 ["C12","Continuation should be reopened when purpose, evidence, authority, configuration, harms, dependence, or exit conditions change.","S01, S02, S04, S17","Issue 12 continuation and retirement record.","The course does not execute rollback, preserve records, close vendors, or retire a real system."]
];

const coverage=[
 ["01","Client intake","S01, S03, S05, S08","Model-rule and general governance support only; jurisdiction, firm, matter, product, configuration, data, and authorization remain unresolved."],
 ["02","Meeting capture","S01, S05, S17","Governance, access, and accountability frame only; recording, labor, privacy, privilege, records, sector, agreement, and jurisdiction questions require separate authority."],
 ["03","Customer support","S01, S03, S04, S07, S17","Supports function, authority, data, security, monitoring, and escalation questions—not permission to send or act for a business."],
 ["04","Knowledge answers","S01, S03, S17","Supports source authority, uncertainty, evaluation, and disclosure—not truth verification or access to an internal repository."],
 ["05","Opportunity decisions","S01, S09, S10, S17","Supports selection, disability, validation, impact, and accountability questions—not an employment or opportunity decision."],
 ["06","Public claims","S12, S17","Supports fit-for-purpose substantiation and claim-validation discipline—not a universal advertising-law conclusion."],
 ["07","AI explanations","S03, S11, S17","Supports fidelity, actual-reason, uncertainty, and challenge questions; S11 remains a bounded federal credit example."],
 ["08","Voice and image","S13, S14","Supports provenance, replicas, detection limits, and policy context—not consent, rights clearance, or distribution permission."],
 ["09","AI agents","S01, S03, S07, S17","Supports bounded authority, security, oversight, reversibility, evidence, and accountability—not permission for an agent to act."],
 ["10","AI purchasing","S01, S04, S07, S17","Supports vendor evidence, governance, security, evaluation, disclosure, and exit—not procurement approval or contract review."],
 ["11","Student work","S05, S15, S16","Supports learning, educator, access, and student-privacy questions—not grading, placement, pedagogy, institutional, or legal approval."],
 ["12","Continuation and retirement","S01, S02, S04, S17","Supports lifecycle review, monitoring, evaluation, accountability, and exit questions—not a real rollback or retirement action."]
];

export default function Insights(){return <SiteShell><main id="main">
 <section className="page-hero wrap"><p className="kicker">Source Desk · public evidence and coverage register</p><h1>See what supports each method—<em>and where it stops.</em></h1><p className="lede">The Source Desk connects Aloha AI’s public method claims and all twelve Decision Desk issues to official or first-party records. Every entry states its job, its transfer limit, and the review that still belongs outside this website.</p><div className="actions"><a className="button primary" href="#course-coverage">Check course coverage</a><a className="button" href="#source-register">Open all sources</a></div></section>
 <section className="event-status"><div className="wrap event-status-grid"><div><span>Status</span><strong>Published public register</strong></div><div><span>Sources</span><strong>17 official records</strong></div><div><span>Mapped claims</span><strong>12 method claims</strong></div><div><span>Reviewed</span><strong>August 14, 2026</strong></div></div></section>
 <section className="wrap pathways"><div className="section-head"><div><p className="section-label">What this desk is</p><h2>A public evidence index—not a pile of links.</h2></div><p>A source appears only when it has a defined job. The map shows which public language it supports, how that support is implemented, and why the source cannot carry a broader claim.</p></div><div className="trust-grid"><article><h3>1. Bound the claim</h3><p>Use the smallest proposition needed for the course, tool, or public method.</p></article><article><h3>2. Prefer the source</h3><p>Link the official framework, agency record, original report, standard, or issuing body.</p></article><article><h3>3. Preserve limits</h3><p>Keep context, jurisdiction, population, version, authority, and product limits visible.</p></article><article><h3>4. Reopen review</h3><p>Recheck after revision, broken links, material challenges, product change, or new controlling authority.</p></article></div></section>
 <section className="wrap pathways" id="course-coverage"><div className="section-head"><div><p className="section-label">Decision Desk coverage</p><h2>Every issue has a visible evidence route.</h2></div><p>This is teaching-frame coverage—not proof that a real use is lawful, safe, accurate, accessible, authorized, or ready.</p></div><div className="path-list">{coverage.map(c=><article className="path-row" key={c[0]}><span className="path-num">{c[0]}</span><div><h3>{c[1]}</h3><p><strong>Public support:</strong> {c[2]}</p><p><strong>Remaining boundary:</strong> {c[3]}</p><Link className="text-link" href={`/learning/decision-desk/issue-${c[0]}`}>Open Issue {c[0]} →</Link></div><span className="event-result">Covered</span></article>)}</div></section>
 <section className="wrap pathways" id="claim-map"><div className="section-head"><div><p className="section-label">Claim map</p><h2>Twelve claims used across public courses and tools.</h2></div><p>Support never silently expands into certification, product testing, legal advice, or individualized approval.</p></div><div className="path-list">{claims.map(c=><article className="path-row" key={c[0]}><span className="path-num">{c[0]}</span><div><h3>{c[1]}</h3><p><strong>Support:</strong> {c[2]}</p><p><strong>Implemented as:</strong> {c[3]}</p><p><strong>Boundary:</strong> {c[4]}</p></div><span className="event-result">Mapped</span></article>)}</div></section>
 <section className="wrap pathways" id="source-register"><div className="section-head"><div><p className="section-label">Source register</p><h2>Seventeen records and their exact jobs.</h2></div><p>Open the source before relying on it. Dates describe the record reviewed; living pages and guidance may change.</p></div><div className="path-list">{sources.map(s=><article className="path-row" key={s.id}><span className="path-num">{s.id}</span><div><h3><a href={s.href} target="_blank" rel="noreferrer">{s.name} ↗</a></h3><p>{s.issuer} · {s.date}</p><p><strong>Used for:</strong> {s.use}</p><p><strong>Limit:</strong> {s.limit}</p></div><span className="event-result">Official</span></article>)}</div></section>
 <section className="offer-grid wrap"><article className="offer-card"><p className="section-label">Maintenance record</p><h2>Review and correction controls</h2><ul className="scope-list"><li>Owner: RN Collins</li><li>Routine review: at least quarterly</li><li>Immediate review: source revision, broken link, material product change, credible error report, or new controlling authority</li><li>Correction rule: narrow or remove unsupported language and update the review date</li><li>Course rule: new public instruction must identify its source route and remaining boundary before being called complete</li><li>Retirement rule: remove records that no longer support an active public method or cannot be maintained</li></ul></article><aside><p className="section-label">Consumer boundary</p><h2>The Source Desk supports scrutiny.</h2><p>It does not personalize legal requirements, verify facts entered into tools, rank vendors, test products, certify compliance, or approve a decision. It shows why a question appears, which official record informed it, and where the evidence stops.</p><div className="actions"><Link className="button primary" href="/learning/decision-desk">Use Decision Desk</Link><Link className="button" href="/tools">Open the tools</Link></div></aside></section>
 </main></SiteShell>}
