import Link from "next/link";
import type {Metadata} from "next";
import {SiteShell} from "../site-shell";

export const metadata:Metadata={title:"Source Desk",description:"The maintained evidence register, claim map, limits, and review controls behind Aloha AI’s public methods and tools."};

const sources=[
  {id:"S01",name:"NIST AI Risk Management Framework 1.0",issuer:"U.S. National Institute of Standards and Technology",date:"January 2023",use:"Risk governance vocabulary and Govern–Map–Measure–Manage lifecycle used in decision and pilot records.",limit:"Voluntary framework; does not certify a system or replace sector-specific obligations.",href:"https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.100-1.pdf"},
  {id:"S02",name:"NIST AI RMF Playbook",issuer:"U.S. National Institute of Standards and Technology",date:"Living resource",use:"Suggested actions and documentation practices used to turn framework outcomes into operating questions.",limit:"Illustrative actions must be selected and adapted; citing the Playbook does not establish conformance.",href:"https://airc.nist.gov/airmf-resources/playbook/"},
  {id:"S03",name:"Artificial Intelligence Risk Management Framework: Generative AI Profile",issuer:"U.S. National Institute of Standards and Technology",date:"July 2024",use:"Generative-AI risks, measurement concerns, provenance, incident, and human-oversight prompts.",limit:"Cross-sector profile; not a product evaluation, legal safe harbor, or complete control catalog.",href:"https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf"},
  {id:"S04",name:"AI Accountability Framework",issuer:"U.S. Government Accountability Office",date:"June 2021",use:"Governance, data, performance, and monitoring dimensions used in evidence and accountability records.",limit:"Oversight framework; it does not prescribe one implementation or validate user-entered evidence.",href:"https://www.gao.gov/products/gao-21-519sp"},
  {id:"S05",name:"Web Content Accessibility Guidelines 2.2",issuer:"World Wide Web Consortium",date:"October 2023",use:"Public-interface accessibility baseline and prompts for affected-user access review.",limit:"Conformance requires testing against applicable criteria; a reference in a worksheet is not an accessibility audit.",href:"https://www.w3.org/TR/WCAG22/"},
  {id:"S06",name:"Section 508 Standards",issuer:"U.S. Access Board",date:"Official standards page",use:"Accessibility procurement and information-and-communications-technology context for relevant U.S. federal uses.",limit:"Applicability depends on setting and authority; the tools do not determine legal coverage.",href:"https://www.access-board.gov/ict/"},
  {id:"S07",name:"Secure by Design",issuer:"Cybersecurity and Infrastructure Security Agency",date:"Current initiative",use:"Security ownership, safe defaults, vulnerability, and supplier-evidence prompts in comparison and pilot tools.",limit:"General security principles; not a security assessment of any candidate or deployment.",href:"https://www.cisa.gov/securebydesign"},
  {id:"S08",name:"ABA Formal Opinion 512",issuer:"American Bar Association Standing Committee on Ethics and Professional Responsibility",date:"July 2024",use:"Professional-responsibility context for the Citation Verifier and the fictional legal-intake case.",limit:"Addresses ABA Model Rules and is not jurisdiction-specific legal advice; controlling duties may differ.",href:"https://www.americanbar.org/content/dam/aba/administrative/professional_responsibility/ethics-opinions/aba-formal-opinion-512.pdf"}
];
const claims=[
  ["C01","AI decisions need named governance, context, measurement, and response—not a capability demo alone.","S01, S02, S04","Shapes Studio, Decision Record, and Pilot Design Kit prompts.","Aloha AI does not infer readiness or conformance from worksheet completion."],
  ["C02","Generative-AI evaluation must preserve uncertainty, provenance, human oversight, and incident response.","S03","Shapes Citation Verifier verdicts, evidence records, and abstention rules.","The tools do not independently test model performance or source truth."],
  ["C03","Accessibility must be treated as an operating requirement and tested with relevant users and criteria.","S05, S06","Creates accessibility gates and affected-party prompts.","No automated or manual accessibility certification is provided."],
  ["C04","Security claims require evidence, ownership, incident paths, and acceptable defaults.","S01, S07","Creates security and incident gates in vendor and pilot records.","No penetration test, threat model, or vendor due diligence is performed."],
  ["C05","For legal work, use of generative AI does not transfer professional responsibility away from authorized people.","S08","Constrains Citation Verifier and Decision Desk Issue 01.","General education only; obtain jurisdiction- and matter-specific advice."]
];

export default function Insights(){return <SiteShell><main id="main">
  <section className="page-hero wrap"><p className="kicker">Source Desk · maintained public evidence register</p><h1>See what supports the method—<em>and what does not.</em></h1><p className="lede">This desk maps public method claims to primary or official sources, states how each source is used, preserves transfer limits, and identifies when review must reopen.</p><div className="actions"><a className="button primary" href="#claim-map">Inspect the claim map</a><a className="button" href="#source-register">Open the source register</a></div></section>
  <section className="event-status"><div className="wrap event-status-grid"><div><span>Status</span><strong>Published register</strong></div><div><span>Sources</span><strong>8 official records</strong></div><div><span>Mapped claims</span><strong>5 method claims</strong></div><div><span>Reviewed</span><strong>August 12, 2026</strong></div></div></section>
  <section className="wrap pathways"><div className="section-head"><div><p className="section-label">Evidence method</p><h2>Claim → source → limit → review.</h2></div><p>A source is included only when it supports a specific public method choice. Inclusion is not endorsement, legal applicability, certification, or proof that a user’s decision is sound.</p></div><div className="trust-grid"><article><h3>1. State the claim</h3><p>Write the smallest proposition the public language needs—without promotional expansion.</p></article><article><h3>2. Prefer authority</h3><p>Use the controlling document, official framework, original research, or creator documentation.</p></article><article><h3>3. Record transfer limits</h3><p>Say what the source cannot establish across context, jurisdiction, population, version, or workflow.</p></article><article><h3>4. Maintain the record</h3><p>Recheck on scheduled review, source revision, broken link, product change, material correction, or credible challenge.</p></article></div></section>
  <section className="wrap pathways" id="claim-map"><div className="section-head"><div><p className="section-label">Claim map</p><h2>Five claims used across the public tools.</h2></div><p>Each record shows support, implementation, and the boundary that prevents the source from becoming an unsupported product claim.</p></div><div className="path-list">{claims.map(c=><article className="path-row" key={c[0]}><span className="path-num">{c[0]}</span><div><h3>{c[1]}</h3><p><strong>Support:</strong> {c[2]}</p><p><strong>Implemented as:</strong> {c[3]}</p><p><strong>Boundary:</strong> {c[4]}</p></div><span className="event-result">Mapped</span></article>)}</div></section>
  <section className="wrap pathways" id="source-register"><div className="section-head"><div><p className="section-label">Source register</p><h2>Official records and their exact jobs.</h2></div><p>Open the source itself before relying on it. Dates describe the cited record; living resources may change between reviews.</p></div><div className="path-list">{sources.map(s=><article className="path-row" key={s.id}><span className="path-num">{s.id}</span><div><h3><a href={s.href} target="_blank" rel="noreferrer">{s.name} ↗</a></h3><p>{s.issuer} · {s.date}</p><p><strong>Used for:</strong> {s.use}</p><p><strong>Limit:</strong> {s.limit}</p></div><span className="event-result">Official</span></article>)}</div></section>
  <section className="offer-grid wrap"><article className="offer-card"><p className="section-label">Maintenance record</p><h2>Review and correction controls</h2><ul className="scope-list"><li>Owner: RN Collins</li><li>Routine review: at least quarterly</li><li>Immediate review: source revision, broken link, material product change, credible error report, or new controlling authority</li><li>Correction rule: narrow or remove unsupported language; preserve the reason and review date</li><li>Retirement rule: remove records that no longer support an active public method or cannot be maintained</li></ul></article><aside><p className="section-label">Consumer boundary</p><h2>The Source Desk supports scrutiny.</h2><p>It does not personalize legal requirements, verify facts entered into tools, rank vendors, certify compliance, or approve a decision. It lets you inspect why a question appears and where the evidence stops.</p><div className="actions"><Link className="button primary" href="/tools">Use the tools</Link><Link className="button" href="/learning">Open learning</Link></div></aside></section>
</main></SiteShell>}
