import Link from "next/link";
import type {Metadata} from "next";
import {SiteShell} from "../site-shell";

export const metadata:Metadata={title:"Free decision tools",description:"Use four standalone Aloha AI decision tools and eleven course-linked Decision Desk instruments. All are browser-local, guided, and exportable."};

const standalone=[
 {release:"01",state:"Complete standalone v1",name:"Opportunity Studio",description:"Examine whether AI belongs in one bounded piece of work and see which conditions control the next move.",features:["23 guided prompts across the decision path","Transparent rule-based disposition","Private browser session","Copyable working brief","Explicit evidence and review boundary"],href:"/studio",action:"Use the Studio"},
 {release:"02",state:"Complete standalone v1",name:"Decision Record Builder",description:"Preserve the owner, alternatives, evidence, affected people, stop conditions, fallback, uncertainty, and review triggers for one decision.",features:["Four guided sections and 20 fields","Core-field completeness indicator","Browser-local autosave","Markdown and portable JSON","Verification and approval boundary"],href:"/tools/decision-record",action:"Build a decision record"},
 {release:"03",state:"Complete standalone v1",name:"Tool & Vendor Comparison Builder",description:"Compare the current process and two candidates without allowing features or price to erase unresolved safeguards.",features:["Current process plus two candidates","Five controlling evidence gates","Evidence required for every score","Markdown and JSON exports","Blocking gates cannot be averaged away"],href:"/tools/vendor-comparison",action:"Compare options"},
 {release:"04",state:"Complete standalone v1",name:"Pilot Design Kit",description:"Precommit the hypothesis, baseline, affected-party input, evidence plan, authority, stop, rollback, and end-of-pilot decision for one test.",features:["Five controlling readiness gates","Benefit, harm, workload, and equity measures","Stop, incident, rollback, and fallback plans","Markdown and JSON exports","Deployment decision firewall"],href:"/tools/pilot-design",action:"Design a pilot"}
];

const instruments=[
 ["02","Meeting Capture Permission and Record Map","Decide whether an AI meeting bot belongs in one meeting class and separate raw media, transcript, summary, actions, and the human-approved record.","/learning/decision-desk/issue-02#instrument"],
 ["03","Support Automation Authority Map","Bound which customer-support messages AI may classify, retrieve, draft, send, or act on—and which must remain human-owned.","/learning/decision-desk/issue-03#instrument"],
 ["04","Knowledge Answerability and Source-Authority Test","Test whether one internal question class can be answered from an approved source collection for defined users.","/learning/decision-desk/issue-04#instrument"],
 ["05","Human Opportunity Decision Impact Map","Review one proposed AI role in hiring, selection, access, or another human opportunity without transferring consequential judgment.","/learning/decision-desk/issue-05#instrument"],
 ["06","Public-Claim Substantiation Gate","Connect an AI-assisted public claim to the evidence, scope, audience, review, and correction route needed before publication.","/learning/decision-desk/issue-06#instrument"],
 ["07","High-Stakes Explanation Fidelity Test","Check whether an AI explanation preserves authority, meaning, uncertainty, limitations, review, and a real challenge path.","/learning/decision-desk/issue-07#instrument"],
 ["08","Synthetic Media Permission and Provenance Record","Record permission, purpose, source assets, transformations, provenance, distribution, withdrawal, correction, and retirement for an AI voice or image.","/learning/decision-desk/issue-08#instrument"],
 ["09","Agent Action Authority and Reversibility Matrix","Bound what an AI agent may send, spend, change, move, schedule, or trigger—and whether every consequential action can be stopped or reversed.","/learning/decision-desk/issue-09#instrument"],
 ["10","AI Vendor Evidence and Contract Dossier","Compare product evidence, data terms, security, accessibility, implementation, monitoring, contract conditions, and exit readiness before purchase.","/learning/decision-desk/issue-10#instrument"],
 ["11","Learner-Affecting AI Use Review","Evaluate one educational use against learning purpose, work and data authority, access, validity, educator review, challenge, and monitoring.","/learning/decision-desk/issue-11#instrument"],
 ["12","AI Continuation and Retirement Decision Record","Decide whether one exact AI use should continue, pause for repair, roll back, be replaced, or retire.","/learning/decision-desk/issue-12#instrument"]
];

export default function Tools(){return <SiteShell><main id="main">
 <section className="page-hero wrap"><p className="kicker">Free tools · fifteen complete browser-local releases</p><h1>Choose the decision in front of you—<em>then make it inspectable.</em></h1><p className="lede">Use four standalone builders for general AI work or choose one of eleven Decision Desk instruments for a specific question. No account is required, Aloha AI does not receive what you enter, and every tool provides a portable record.</p><div className="actions"><a className="button primary" href="#standalone">Use a standalone tool</a><a className="button" href="#decision-desk-tools">Find a specific instrument</a></div></section>
 <section className="event-status"><div className="wrap event-status-grid"><div><span>Standalone tools</span><strong>4 complete</strong></div><div><span>Course instruments</span><strong>11 complete</strong></div><div><span>Account</span><strong>Not required</strong></div><div><span>Data location</span><strong>Your browser</strong></div></div></section>
 <section className="wrap pathways"><div className="section-head"><div><p className="section-label">Two ways to begin</p><h2>General work or one governed question.</h2></div><p>The four standalone tools help structure an opportunity, decision, vendor comparison, or pilot. Decision Desk instruments sit inside complete self-paced courses so you can learn the governing distinctions before completing the record.</p></div><div className="trust-grid"><article><h3>Use a standalone builder</h3><p>Best when you already understand the context and need a structured, portable working record.</p><a className="text-link" href="#standalone">See four builders →</a></article><article><h3>Learn and use an instrument</h3><p>Best when the decision involves a specific risk, authority, evidence, or affected-person question.</p><a className="text-link" href="#decision-desk-tools">See eleven instruments →</a></article></div></section>
 <section className="service-cards wrap" id="standalone">{standalone.map(tool=><article key={tool.release}><p className="section-label">Release {tool.release} · {tool.state}</p><h2>{tool.name}</h2><p>{tool.description}</p><ul className="scope-list">{tool.features.map(feature=><li key={feature}>{feature}</li>)}</ul><Link className="button primary" href={tool.href}>{tool.action}</Link></article>)}</section>
 <section className="wrap pathways" id="decision-desk-tools"><div className="section-head"><div><p className="section-label">Decision Desk instrument library</p><h2>Eleven specific questions. Eleven distinct records.</h2></div><p>Each link opens the instrument inside its complete public course. Work with fictional or nonsensitive information, then export anything you need to retain.</p></div><div className="path-list">{instruments.map(x=><article className="path-row" key={x[0]}><span className="path-num">{x[0]}</span><div><p className="section-label">Decision Desk Issue {x[0]}</p><h3>{x[1]}</h3><p>{x[2]}</p><Link className="text-link" href={x[3]}>Learn and use the instrument →</Link></div><span className="event-result">Complete</span></article>)}</div></section>
 <section className="offer-grid wrap"><article className="offer-card"><p className="section-label">What every public tool provides</p><h2>A private working record you can keep.</h2><ul className="scope-list"><li>Guided prompts, gates, or transparent bounded logic</li><li>Browser-local persistence without an Aloha AI account</li><li>A visible boundary against sensitive or confidential input</li><li>A portable Markdown, JSON, or copyable export</li><li>A local reset or deletion control</li><li>A clear statement of what completion does not authorize</li></ul></article><aside><p className="section-label">Before you rely on a result</p><h2>The tool structures judgment; it does not replace it.</h2><p>Aloha AI does not verify the evidence you enter, determine applicable law or policy, test a product, certify compliance, authorize action, synchronize devices, or manage organizational approval. Export the record, involve the right people, and obtain the review the real context requires.</p><div className="actions"><Link className="button primary" href="/insights">Inspect the Source Desk</Link><Link className="button" href="/learning/decision-desk">Browse Decision Desk</Link></div></aside></section>
 </main></SiteShell>}
