"use client";
import {useEffect,useMemo,useState} from "react";

type GateValue="unresolved"|"pass"|"fail";
type Option={name:string;kind:string;gates:Record<string,GateValue>;gateEvidence:Record<string,string>;scores:Record<string,string>;scoreEvidence:Record<string,string>};
type State={decision:string;outcome:string;scope:string;owner:string;reviewers:string;weights:Record<string,string>;options:Option[];uncertainty:string;nextStep:string};
const STORAGE_KEY="aloha-ai-vendor-comparison-v1";
const gates=[
  ["privacy","Privacy, data authority, and acceptable use","The information, permissions, retention, model-training terms, and uses are lawful and acceptable for this bounded context."],
  ["security","Security and incident response","Required security controls, vulnerability handling, incident notice, and responsible ownership are evidenced."],
  ["accessibility","Accessibility and equitable access","The option can meet applicable access needs, accommodations, and procurement requirements without shifting burdens to users."],
  ["verification","Evidence and output verification","Claims and outputs can be tested against trusted sources by capable reviewers before consequential use."],
  ["exit","Exit, portability, and continuity","Data and work can be retrieved; lock-in, deletion, transition, and service-failure paths are understood and acceptable."],
] as const;
const criteria=[
  ["fit","Bounded task fit","Does the option support the stated outcome within scope?"],
  ["operability","Operational fit","Can the responsible team review, maintain, support, and govern it?"],
  ["cost","Total burden","Consider money, implementation, review, training, remediation, switching, and ongoing work."],
] as const;
const blankOption=(name:string,kind:string):Option=>({name,kind,gates:Object.fromEntries(gates.map(([key])=>[key,"unresolved"])),gateEvidence:Object.fromEntries(gates.map(([key])=>[key,""])),scores:Object.fromEntries(criteria.map(([key])=>[key,""])),scoreEvidence:Object.fromEntries(criteria.map(([key])=>[key,""]))});
const empty:State={decision:"",outcome:"",scope:"",owner:"",reviewers:"",weights:{fit:"5",operability:"3",cost:"2"},options:[blankOption("Current process","Baseline"),blankOption("Candidate A","Candidate"),blankOption("Candidate B","Candidate")],uncertainty:"",nextStep:""};
function safeParse(value:string|null):State{if(!value)return empty;try{const parsed=JSON.parse(value);return {...empty,...parsed,weights:{...empty.weights,...parsed.weights},options:empty.options.map((fallback,index)=>({...fallback,...parsed.options?.[index],gates:{...fallback.gates,...parsed.options?.[index]?.gates},gateEvidence:{...fallback.gateEvidence,...parsed.options?.[index]?.gateEvidence},scores:{...fallback.scores,...parsed.options?.[index]?.scores},scoreEvidence:{...fallback.scoreEvidence,...parsed.options?.[index]?.scoreEvidence}}))}}catch{return empty}}
function download(name:string,content:string,type:string){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=name;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const numeric=(value:string,min:number,max:number)=>{const number=Number(value);return Number.isFinite(number)?Math.min(max,Math.max(min,number)):0};

export function VendorComparisonBuilder(){
  const [state,setState]=useState<State>(empty);const [ready,setReady]=useState(false);const [message,setMessage]=useState("");
  useEffect(()=>{const restore=window.setTimeout(()=>{setState(safeParse(localStorage.getItem(STORAGE_KEY)));setReady(true)},0);return()=>window.clearTimeout(restore)},[]);
  useEffect(()=>{if(ready)localStorage.setItem(STORAGE_KEY,JSON.stringify(state))},[ready,state]);
  const results=useMemo(()=>state.options.map(option=>{const blocking=gates.filter(([key])=>option.gates[key]!=="pass").map(([key,label])=>({key,label,status:option.gates[key]}));const total=criteria.reduce((sum,[key])=>sum+numeric(option.scores[key],0,5)*numeric(state.weights[key],0,5),0);const possible=criteria.reduce((sum,[key])=>sum+5*numeric(state.weights[key],0,5),0);return {blocking,total,possible,percent:possible?Math.round(total/possible*100):0}}),[state]);
  const updateOption=(index:number,group:"gates"|"gateEvidence"|"scores"|"scoreEvidence",key:string,value:string)=>setState(current=>({...current,options:current.options.map((option,i)=>i===index?{...option,[group]:{...option[group],[key]:value}}:option)}));
  const portable={recordType:"Aloha AI tool and vendor comparison",schemaVersion:1,exportedAt:new Date().toISOString(),notice:"Self-authored working comparison; vendor claims and evidence are not verified, approved, recommended, or certified by Aloha AI.",frameworkContext:["NIST AI RMF 1.0","NIST SP 800-218","CISA Secure by Design","U.S. Access Board Section 508 Standards"],state,results};
  function markdown(){return `# ${state.decision||"Untitled tool and vendor comparison"}\n\n> Self-authored working comparison; vendor claims and evidence are not verified, approved, recommended, or certified by Aloha AI.\n\n- Intended outcome: ${state.outcome||"Not recorded"}\n- Scope and exclusions: ${state.scope||"Not recorded"}\n- Accountable owner: ${state.owner||"Not recorded"}\n- Required reviewers: ${state.reviewers||"Not recorded"}\n\n${state.options.map((option,index)=>`## ${option.name} — ${option.kind}\n\n**Gate result:** ${results[index].blocking.length?"DO NOT ADVANCE — unresolved or failed gates":"All five gates recorded as passed; specialist review may still be required."}\n\n${gates.map(([key,label])=>`### ${label}\n\n- Status: ${option.gates[key]}\n- Evidence and limits: ${option.gateEvidence[key]||"Not recorded"}`).join("\n\n")}\n\n### Weighted criteria\n\n${criteria.map(([key,label])=>`- ${label}: ${option.scores[key]||"Not scored"}/5 × weight ${state.weights[key]||"0"}; evidence: ${option.scoreEvidence[key]||"Not recorded"}`).join("\n")}\n\nArithmetic summary: ${results[index].percent}% (${results[index].total}/${results[index].possible}). This score cannot override a gate.`).join("\n\n")}\n\n## Uncertainty and dissent\n\n${state.uncertainty||"Not recorded"}\n\n## Owner-selected next step\n\n${state.nextStep||"Not recorded"}\n\n## Framework context\n\nNIST AI RMF 1.0; NIST SP 800-218; CISA Secure by Design; U.S. Access Board Section 508 Standards. These sources informed the questions; this record does not establish conformity.\n`}
  function clear(){if(!window.confirm("Clear this comparison from this browser?"))return;localStorage.removeItem(STORAGE_KEY);setState(empty);setMessage("Local comparison cleared.")}
  return <section id="workspace" className="wrap comparison-builder" aria-labelledby="comparison-title">
    <div className="builder-heading"><div><p className="section-label">Private working space</p><h2 id="comparison-title">Frame one comparison</h2><p>Nothing entered here is transmitted to Aloha AI. Do not paste confidential, privileged, personal, security-sensitive, or regulated information.</p></div><div className="comparison-rule"><strong>Gates control.</strong><span>A high weighted score never cancels an unresolved or failed gate.</span></div></div>
    <div className="record-fields comparison-frame"><label className="wide"><span>Decision to be made</span><small>State one bounded choice; do not assume buying a tool is the answer.</small><textarea value={state.decision} onChange={event=>setState({...state,decision:event.target.value})}/></label><label className="wide"><span>Outcome and baseline</span><small>What should improve, for whom, and compared with what current result?</small><textarea value={state.outcome} onChange={event=>setState({...state,outcome:event.target.value})}/></label><label className="wide"><span>Scope and exclusions</span><small>Define users, setting, data, duration, consequences, and prohibited uses.</small><textarea value={state.scope} onChange={event=>setState({...state,scope:event.target.value})}/></label><label><span>Accountable owner</span><small>Name the person with decision authority.</small><input value={state.owner} onChange={event=>setState({...state,owner:event.target.value})}/></label><label><span>Required reviewers</span><small>Identify privacy, security, access, legal, procurement, domain, or affected-party review.</small><input value={state.reviewers} onChange={event=>setState({...state,reviewers:event.target.value})}/></label></div>
    <fieldset className="record-section"><legend><span>01</span>Criterion weights</legend><p>Weight each criterion from 0–5 before comparing. Arithmetic organizes your judgments; it does not make them objective.</p><div className="weight-grid">{criteria.map(([key,label,help])=><label key={key}><span>{label}</span><small>{help}</small><input type="number" min="0" max="5" value={state.weights[key]} onChange={event=>setState(current=>({...current,weights:{...current.weights,[key]:event.target.value}}))}/></label>)}</div></fieldset>
    {state.options.map((option,index)=><fieldset className="record-section comparison-option" key={index}><legend><span>{String(index+2).padStart(2,"0")}</span>{option.name}</legend><div className="option-name-row"><label><span>Option name</span><input value={option.name} onChange={event=>setState(current=>({...current,options:current.options.map((item,i)=>i===index?{...item,name:event.target.value}:item)}))}/></label><label><span>Option type</span><input value={option.kind} onChange={event=>setState(current=>({...current,options:current.options.map((item,i)=>i===index?{...item,kind:event.target.value}:item)}))}/></label></div><div className={`gate-summary ${results[index].blocking.length?"blocked":"clear"}`} aria-live="polite"><strong>{results[index].blocking.length?"Do not advance":"No unresolved gates recorded"}</strong><span>{results[index].blocking.length?`${results[index].blocking.length} gate(s) failed or unresolved. Repair and obtain required review before ranking controls a decision.`:"All gates are marked passed; this is not verification, certification, or approval."}</span></div><div className="gate-list">{gates.map(([key,label,help])=><article key={key}><div><h3>{label}</h3><p>{help}</p></div><label><span>Status</span><select value={option.gates[key]} onChange={event=>updateOption(index,"gates",key,event.target.value)}><option value="unresolved">Unresolved / insufficient evidence</option><option value="pass">Pass for this bounded use</option><option value="fail">Fail / unacceptable condition</option></select></label><label className="wide"><span>Evidence, source, date, reviewer, and limits</span><textarea value={option.gateEvidence[key]} onChange={event=>updateOption(index,"gateEvidence",key,event.target.value)}/></label></article>)}</div><div className="criteria-grid">{criteria.map(([key,label,help])=><article key={key}><h3>{label}</h3><p>{help}</p><label><span>User-authored score (0–5)</span><input type="number" min="0" max="5" value={option.scores[key]} onChange={event=>updateOption(index,"scores",key,event.target.value)}/></label><label><span>Evidence and limitations</span><textarea value={option.scoreEvidence[key]} onChange={event=>updateOption(index,"scoreEvidence",key,event.target.value)}/></label></article>)}</div><p className="arithmetic-summary"><strong>{results[index].percent}%</strong> weighted arithmetic summary ({results[index].total}/{results[index].possible}). This summary is not comparable unless the same scope, evidence standard, reviewers, and weights apply—and it never overrides a gate.</p></fieldset>)}
    <fieldset className="record-section"><legend><span>05</span>Preserve uncertainty and ownership</legend><div className="record-fields"><label className="wide"><span>Uncertainty, conflicting evidence, and dissent</span><textarea value={state.uncertainty} onChange={event=>setState({...state,uncertainty:event.target.value})}/></label><label className="wide"><span>Owner-selected next step and conditions</span><textarea value={state.nextStep} onChange={event=>setState({...state,nextStep:event.target.value})}/></label></div></fieldset>
    <div className="course-actions"><button className="button primary" type="button" onClick={()=>{download("tool-vendor-comparison.md",markdown(),"text/markdown");setMessage("Markdown download started.")}}>Download readable comparison</button><button className="button" type="button" onClick={()=>{download("tool-vendor-comparison.json",JSON.stringify(portable,null,2),"application/json");setMessage("JSON download started.")}}>Export portable JSON</button><button className="text-button" type="button" onClick={clear}>Clear local comparison</button></div><p className="action-status" aria-live="polite">{message}</p>
  </section>
}
