import Link from "next/link";
import type {Metadata} from "next";
import {SiteShell} from "../../site-shell";

export const metadata:Metadata={title:"Decision Desk · Twelve-Month Learning Plan",description:"Explore twelve real AI decisions, ten complete public self-paced editions, their reusable instruments, and the separate readiness of future live masterclasses and Clinics."};

const issues=[
 ["01","Sep 2026","Before You Use AI for Client Intake","Should a small law firm use AI to summarize prospective-client intake?","Intake Summarization Evaluation Card","RN-led release candidate prepared; not approved for delivery","/learning/decision-desk/issue-01"],
 ["02","Oct 2026","Before the Bot Joins the Meeting","Should an AI meeting bot enter one defined meeting class?","Meeting Capture Permission and Record Map","Public self-paced edition open; live delivery not approved","/learning/decision-desk/issue-02"],
 ["03","Nov 2026","Should AI Answer Your Customers?","Which support functions and message classes may AI classify, retrieve, draft, send, or act on?","Support Automation Authority Map","Public self-paced edition open; live delivery not approved","/learning/decision-desk/issue-03"],
 ["04","Dec 2026","Can Your AI Find the Right Answer?","Which internal questions may AI answer from which sources for which users?","Knowledge Answerability and Source-Authority Test","Public self-paced edition open; live delivery not approved","/learning/decision-desk/issue-04"],
 ["05","Jan 2027","Should AI Help Choose People?","May AI assist at one defined stage of an opportunity process?","Human Opportunity Decision Impact Map","Public self-paced edition open; live delivery not approved","/learning/decision-desk/issue-05"],
 ["06","Feb 2027","Can You Prove That AI-Written Claim?","May AI draft a defined public-claim class for one channel?","Public-Claim Substantiation Gate","Public self-paced edition open; live delivery not approved","/learning/decision-desk/issue-06"],
 ["07","Mar 2027","Can People Trust This AI Explanation?","When may AI translate complex authoritative information without becoming individualized advice?","High-Stakes Explanation Fidelity Test","Public self-paced edition open; live delivery not approved","/learning/decision-desk/issue-07"],
 ["08","Apr 2027","Can You Use Someone’s AI Voice or Image?","When may an organization create and distribute one bounded synthetic voice, likeness, performance, or documentary-style asset?","Synthetic Media Permission and Provenance Record","Public self-paced edition open; live delivery not approved","/learning/decision-desk/issue-08"],
 ["09","May 2027","What Should Your AI Agent Be Allowed to Do?","When may an AI agent send, spend, change records, move data, schedule work, or act in another system?","Agent Action Authority and Reversibility Matrix","Public self-paced edition open; live delivery not approved","/learning/decision-desk/issue-09"],
 ["10","Jun 2027","What to Check Before Buying an AI Tool","How should a small organization evaluate, contract for, implement, and remain able to leave one exact AI product?","AI Vendor Evidence and Contract Dossier","Public self-paced edition open; live delivery not approved","/learning/decision-desk/issue-10"],
 ["11","Jul 2027","Should AI Review a Student’s Work?","When may an educator use AI to support feedback, assessment, personalization, or intervention while remaining responsible?","Learner-Affecting AI Use Review","Public self-paced edition open; live delivery not approved","/learning/decision-desk/issue-11"],
 ["12","Aug 2027","Is It Time to Stop Using This AI?","When should an organization pause, roll back, replace, or retire AI?","AI Continuation and Retirement Decision Record","Planned; not built","#program-boundary"]
];

const edition=[
 ["A real decision","Each issue begins with one bounded question people face when AI enters actual work."],
 ["A complete lesson sequence","The public editions explain the problem, relevant evidence, failure modes, and decision boundaries."],
 ["A reusable instrument","Each open edition includes a browser-local tool or structured record for working through the decision."],
 ["An honest status","Self-paced availability, live-teaching readiness, Clinic availability, and enrollment are stated separately."]
];

export default function DecisionDesk(){return <SiteShell><main id="main">
 <section className="page-hero wrap"><p className="kicker">Decision Desk · twelve-month learning plan</p><h1>Twelve decisions. <em>Twelve distinct instruments.</em></h1><p className="lede">Decision Desk is a twelve-part curriculum about the choices people face when AI enters real work. Issues 02–11 are open as complete self-paced web editions. Issue 01 has a prepared RN-led release candidate but is not approved for delivery. Issue 12 remains planned and unbuilt.</p><div className="actions"><a className="button primary" href="#calendar">Choose an issue</a><Link className="button" href="/learning/decision-desk/issue-02">Start with Issue 02</Link></div></section>
 <section className="event-status"><div className="wrap event-status-grid"><div><span>Plan window</span><strong>Sep 2026–Aug 2027</strong></div><div><span>Open self-paced</span><strong>Issues 02–11</strong></div><div><span>Prepared, not open</span><strong>Issue 01</strong></div><div><span>Live enrollment</span><strong>Closed</strong></div></div></section>
 <section className="trust-section wrap"><div className="section-head"><p className="section-label">What each public edition provides</p><div><h2>Learn the issue. Use the instrument. Keep your own record.</h2><p>You can use an open edition without an account and without waiting for a live event.</p></div></div><div className="trust-grid">{edition.map((item,index)=><article key={item[0]}><span className="path-num">{String(index+1).padStart(2,"0")}</span><h3>{item[0]}</h3><p>{item[1]}</p></article>)}</div></section>
 <section className="wrap pathways" id="calendar"><div className="section-head"><div><p className="section-label">Twelve-month curriculum</p><h2>From intake boundaries to retirement decisions.</h2></div><p>Choose the question closest to the work in front of you. The dates organize the plan; they are not promises of a live monthly event.</p></div><div className="path-list">{issues.map(issue=><article className="path-row" key={issue[0]}><span className="path-num">{issue[0]}</span><div><p className="section-label">{issue[1]} · {issue[5]}</p><h3>{issue[2]}</h3><p><strong>Decision:</strong> {issue[3]}</p><p><strong>Instrument:</strong> {issue[4]}</p><Link className="text-link" href={issue[6]}>{issue[0]==="01"?"Open the flagship record →":issue[0]==="12"?"See what remains planned →":"Open the self-paced edition →"}</Link></div><span className="event-result">Issue {issue[0]}</span></article>)}</div></section>
 <section className="offer-grid wrap"><article className="offer-card"><p className="section-label">How to use an open edition</p><h2>Work privately and at your own pace.</h2><ol><li>Choose one issue and read its lesson sequence.</li><li>Use the supplied fictional examples before applying the method to your own work.</li><li>Keep confidential, privileged, regulated, or sensitive information out of the browser tool.</li><li>Export any record you need to retain; Aloha AI cannot recover browser-local data.</li><li>Treat the result as a structured decision aid—not legal clearance, professional advice, or permission to deploy AI.</li></ol></article><aside><p className="section-label">Separate release gates</p><h2>Public self-paced editions are not live masterclasses.</h2><p>A web edition can be complete while its final presentation deck, RN-approved verbatim script, rehearsal, accessibility testing, operational setup, live Clinic, booking, payment, or support system remains unfinished.</p><p>No Decision Desk live class, Clinic seat, monthly enrollment, public schedule, or checkout is active.</p></aside></section>
 <section className="wrap boundary" id="program-boundary"><p className="section-label">Current readiness</p><div><h2>Ten self-paced editions are open. Live delivery is not.</h2><p>Issue 01 has a 36-slide RN-led release candidate, complete verbatim narration, a slide-by-slide move sheet, a fictional teaching case, an Evaluation Card, participant-file candidates, and delivery controls. It remains closed pending RN approval, rehearsal, real-environment accessibility and platform tests, authorized review, and final go/no-go. Issues 02–11 have complete public self-paced lessons and their own browser-local decision instruments. Issue 12 still requires research, lessons, an instrument, testing, and release review.</p><p>Future live teaching and Clinics require separate RN approval. A public page does not create a seat, reservation, price, or promise of delivery.</p><Link className="button primary" href="/learning/decision-desk/issue-02">Open Issue 02</Link></div></section>
 </main></SiteShell>}
