import Link from "next/link";
import type {Metadata} from "next";
import {SiteShell} from "../../site-shell";

export const metadata:Metadata={title:"Decision Desk · Twelve-Month Program",description:"The canonical twelve-month Decision Desk masterclass and paired-clinic program, with accurate readiness for all twelve issues."};

const issues=[
  ["01","Sep 2026","Before You Use AI for Client Intake","Should a small law firm use AI to summarize prospective-client intake?","Intake Summarization Evaluation Card","Flagship package built; release gates remain","/learning/decision-desk/issue-01"],
  ["02","Oct 2026","Before the Bot Joins the Meeting","Should an AI meeting bot enter one defined meeting class?","Meeting Capture Permission and Record Map","Complete public learning edition; operational release gated","/learning/decision-desk/issue-02"],
  ["03","Nov 2026","Should AI Answer Your Customers?","Which support functions and message classes may AI classify, retrieve, draft, send, or act on?","Support Automation Authority Map","Complete public learning edition; operational release gated","/learning/decision-desk/issue-03"],
  ["04","Dec 2026","Can Your AI Find the Right Answer?","Which internal questions may AI answer from which sources for which users?","Knowledge Answerability and Source-Authority Test","Complete public learning edition; operational release gated","/learning/decision-desk/issue-04"],
  ["05","Jan 2027","Should AI Help Choose People?","May AI assist at one defined stage of an opportunity process?","Human Opportunity Decision Impact Map","Complete public learning edition; operational release gated","/learning/decision-desk/issue-05"],
  ["06","Feb 2027","Can You Prove That AI-Written Claim?","May AI draft a defined public-claim class for one governed channel?","Public-Claim Substantiation Gate","Complete public learning edition; operational release gated","/learning/decision-desk/issue-06"],
  ["07","Mar 2027","Can People Trust This AI Explanation?","When may AI translate complex authoritative information without becoming individualized advice?","High-Stakes Explanation Fidelity Test","Complete public learning edition; operational release gated","/learning/decision-desk/issue-07"],
  ["08","Apr 2027","Can You Use Someone’s AI Voice or Image?","When may an organization create and distribute one bounded synthetic voice, likeness, performance, or documentary-style asset?","Synthetic Media Permission and Provenance Record","Complete public learning edition; operational release gated","/learning/decision-desk/issue-08"],
  ["09","May 2027","What Should Your AI Agent Be Allowed to Do?","When may an AI agent send, spend, change records, move data, schedule work, or act in another system?","Agent Action Authority and Reversibility Matrix","Complete public learning edition; operational release gated","/learning/decision-desk/issue-09"],
  ["10","Jun 2027","What to Check Before Buying an AI Tool","How should a small organization choose and contract for an AI vendor?","AI Vendor Evidence and Contract Dossier","Planned production unit","#program-boundary"],
  ["11","Jul 2027","Should AI Review a Student’s Work?","Should an educator use AI to assess, respond to, or personalize learner work?","Learner-Affecting AI Use Review","Planned production unit","#program-boundary"],
  ["12","Aug 2027","Is It Time to Stop Using This AI?","When should an organization pause, roll back, replace, or retire AI?","AI Continuation and Retirement Decision Record","Planned production unit","#program-boundary"]
];

const unit=["Governed question and defined audience","Claim-level evidence package with contradictions and limits","Decision Desk article and public Source Desk","One reusable issue-specific decision instrument","Exact product/configuration evaluation or transparent no-product finding","Complete 60-minute teaching package","Accessible participant, preparation, follow-up, and correction materials","Complete paired clinic","Visitor, commercial, and communications specification","Visual evidence and rights records","Observed technical, editorial, accessibility, operational, and rehearsal QA","RN go/no-go approval"];

export default function DecisionDesk(){return <SiteShell><main id="main">
  <section className="page-hero wrap"><p className="kicker">Decision Desk · canonical annual program</p><h1>Twelve decisions. <em>Twelve distinct instruments.</em></h1><p className="lede">A twelve-month case-based learning and evidence program: one free governed masterclass in the first week of each month, followed by the same bounded clinic for separate small cohorts in the remaining weeks.</p><div className="actions"><a className="button primary" href="#calendar">Inspect the twelve issues</a><Link className="button" href="/learning/decision-desk/issue-01">Open flagship Issue 01</Link></div></section>
  <section className="event-status"><div className="wrap event-status-grid"><div><span>Program window</span><strong>Sep 2026–Aug 2027</strong></div><div><span>Public learning</span><strong>12 free masterclasses</strong></div><div><span>Applied continuation</span><strong>Paired bounded clinics</strong></div><div><span>Current release state</span><strong>Program plan—not enrollment</strong></div></div></section>
  <section className="wrap pathways"><div className="section-head"><div><p className="section-label">The program—not a content calendar</p><h2>Every month is a complete governed release unit.</h2></div><p>The annual architecture is authorized for internal production. It is not a subscription, public schedule, sale, or claim that Issues 02–12 are finished. Each month must independently pass evidence, product, teaching, accessibility, clinic, commerce, rehearsal, and RN approval gates.</p></div><div className="trust-grid">{unit.map((x,i)=><article key={x}><h3>{String(i+1).padStart(2,"0")}</h3><p>{x}</p></article>)}</div></section>
  <section className="wrap pathways" id="calendar"><div className="section-head"><div><p className="section-label">Twelve-month curriculum</p><h2>From intake boundaries to retirement decisions.</h2></div><p>The progression moves from information crossing a boundary, through consequential representation and delegated power, to institutional lifecycle control.</p></div><div className="path-list">{issues.map(x=><article className="path-row" key={x[0]}><span className="path-num">{x[0]}</span><div><p className="section-label">{x[1]} · {x[5]}</p><h3>{x[2]}</h3><p><strong>Governed question:</strong> {x[3]}</p><p><strong>Reusable instrument:</strong> {x[4]}</p><Link className="text-link" href={x[6]}>{x[0]==="01"?"Open the complete flagship record →":"Review the readiness boundary ↓"}</Link></div><span className="event-result">Issue {x[0]}</span></article>)}</div></section>
  <section className="offer-grid wrap"><article className="offer-card"><p className="section-label">Standard 60-minute teaching architecture</p><h2>Participants produce a decision—not notes about AI.</h2><ol><li><strong>0–7:</strong> private opening view and assumption</li><li><strong>7–16:</strong> authority, affected people, and data map</li><li><strong>16–28:</strong> actual workflow, exceptions, handoffs, and sources</li><li><strong>28–37:</strong> exact product/configuration evidence and disconfirming test</li><li><strong>37–49:</strong> supplied fictional or synthetic exercise using the month’s instrument</li><li><strong>49–57:</strong> safeguards, if–then action, stop authority, and maintenance</li><li><strong>57–60:</strong> bounded disposition, owner, next evidence, and review trigger</li></ol></article><aside><p className="section-label">Paired clinic</p><h2>The same instrument moves into bounded real work.</h2><p>Weeks 2–5 repeat one clinic for separate screened cohorts. Each participant applies the month’s instrument to one nonconfidential workflow. Clinic repetitions are not new products and may not expand scope, capacity, evidence claims, or data boundaries.</p><p>The governing internal assumptions are $295 per participant, a separate $750 private Decision Review, and a $2,800 private team clinic for up to four screened colleagues. No date, seat, checkout, or public price becomes active until the month’s release gate passes and RN approves it.</p></aside></section>
  <section className="wrap pathways"><div className="section-head"><div><p className="section-label">Rolling production system</p><h2>Twelve weeks from activation to delivery.</h2></div><p>At least three states remain visible: current delivery, next-month build, and following-month research.</p></div><div className="path-list">{[["M−12","Activate the issue; approve audience, decision, completion contract, displacement, and owner."],["M−10","Freeze research protocol, source classes, affected-person evidence plan, and product-access decision."],["M−8","Resolve unsupported claims, legal-review need, visual permissions, and evidence gaps."],["M−6","Freeze article thesis, instrument, fictional case, and no-product fallback."],["M−4","Complete teaching, participant, clinic, visitor, and communications drafts."],["M−3","Reconcile facts, editorial boundaries, and accessible formats."],["M−2","Run commercial test mode, browser/accessibility inspection, and rehearsal one."],["M−1","Correct defects, run rehearsal two, confirm support/incident readiness, and obtain RN go/no-go."],["M+2","Send approved follow-up and maintain the correction path."],["M+10","Complete retrospective and scope the next controlled correction."]].map(x=><article className="path-row" key={x[0]}><span className="path-num">{x[0]}</span><div><h3>{x[1]}</h3></div><span className="event-result">Control</span></article>)}</div></section>
  <section className="wrap boundary" id="program-boundary"><p className="section-label">Truthful readiness boundary</p><div><h2>The plan is complete. Most monthly products are not.</h2><p>Issue 01 has a substantial flagship package and finite open gates. Issue 02 has partial governed research. Issue 03 has a bounded research question. Issues 04–12 have approved questions, audiences, learning arcs, instruments, evidence burdens, fictional exercise concepts, and disconfirmation rules—but still require the full production contract before release.</p><p>A missed month triggers defer, reuse of a still-current completed issue, an approved reserve unit, or a dark month. It never authorizes thin research, invented testing, inaccessible materials, or false readiness.</p><Link className="button primary" href="/learning/decision-desk/issue-01">Inspect Issue 01</Link></div></section>
</main></SiteShell>}
