import Link from "next/link";
import type {Metadata} from "next";
import {SiteShell} from "../../site-shell";

export const metadata:Metadata={title:"Decision Desk · Issue 01",description:"A complete case-based decision lab on AI-assisted prospective-client intake."};

const exhibits=[
  ["A","Sponsor request","A managing partner asks whether a generative-AI intake assistant can reduce delays and improve consistency before the next growth campaign."],
  ["B","Workflow observations","Coordinators receive web forms, calls, and referrals; clarify conflicts and deadlines; check jurisdictions and opposing parties; route urgent matters; and record attorney decisions."],
  ["C","Four-week baseline","240 inquiries; median first response 9 business hours; 18% required missing-information follow-up; 7 urgent matters; 31% not in a served practice area; no reliable measure of incorrect routing."],
  ["D","Affected perspectives","Prospective clients want clarity and human contact; coordinators fear hidden rework; attorneys need accurate conflict/deadline escalation; accessibility review has not occurred."],
  ["E","Candidate concept","A browser form drafts follow-up questions and a routing suggestion. It must not give legal advice, decide representation, perform final conflict checks, or suppress access to a person."],
  ["F","Open evidence gaps","No labeled routing set, unresolved retention terms, no accessibility test, no bilingual workflow study, and no measured baseline for coordinator correction time."]
];
const rounds=[
  ["Frame","Write the decision without naming AI. Name owner, affected people, target outcome, and non-negotiable qualities."],
  ["Interrogate","For every exhibit, separate source fact, stakeholder report, generated assumption, and unknown. Identify missing voices."],
  ["Map","Draw the real intake workflow. Mark professional judgment, urgent escalation, conflict screening, repair work, and decisions the system may not make."],
  ["Compare","Evaluate process repair, human-led improvement, investigation, no new intervention, and bounded AI assistance using the same criteria."],
  ["Control","Define permitted data, notice, access, human review, monitoring, incident response, fallback, and measurable stop conditions."],
  ["Decide","Issue one disposition with owner, evidence, dissent, advance conditions, stop evidence, and review date."]
];

export default function DecisionDesk(){return <SiteShell><main id="main">
  <section className="page-hero wrap"><p className="kicker">Decision Desk · Issue 01 · complete open case</p><h1>Should AI assist <em>prospective-client intake?</em></h1><p className="lede">A complete 75–90 minute case-based decision lab. Examine fictional evidence, make the workflow visible, compare five paths, and defend a bounded disposition.</p><div className="actions"><a className="button primary" href="#case-file">Open the case file</a><Link className="button" href="/tools/decision-record">Open a Decision Record</Link></div></section>
  <section className="event-status"><div className="wrap event-status-grid"><div><span>Issue</span><strong>01 · Intake</strong></div><div><span>Length</span><strong>75–90 minutes</strong></div><div><span>Materials</span><strong>6 exhibits + 6 rounds</strong></div><div><span>Finish line</span><strong>Defensible disposition</strong></div></div></section>
  <section className="wrap pathways"><div className="section-head"><div><p className="section-label">Briefing</p><h2>Your role and decision.</h2></div><p>You are the inquiry lead supporting a fictional small law firm. You may recommend process repair, human-led improvement, investigation, no new intervention, or a bounded test. You may not assume the sponsor’s proposed tool is the answer.</p></div><article className="offer-card"><h3>Decision due</h3><p>The accountable partner wants a recommendation in ten working days. Your record must protect prospective clients, preserve attorney authority, avoid unauthorized advice, and explain how urgent, inaccessible, ambiguous, and conflicted matters are handled.</p><p><strong>Case rule:</strong> all organizations, people, metrics, and events are fictional. The case is general education, not legal advice or a model for any jurisdiction.</p></article></section>
  <section className="wrap pathways" id="case-file"><div className="section-head"><div><p className="section-label">Case file</p><h2>Six exhibits. Uneven evidence.</h2></div><p>Do not treat every exhibit as equally reliable. Record what each one establishes, what it does not establish, and what would verify important claims.</p></div><div className="path-list">{exhibits.map((x)=><article className="path-row" key={x[0]}><span className="path-num">{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div><span className="event-result">Exhibit</span></article>)}</div></section>
  <section className="wrap pathways"><div className="section-head"><div><p className="section-label">Exercise sequence</p><h2>Six decision rounds.</h2></div><p>Use the Decision Record Builder or your own document. Spend 8–12 minutes per round and preserve disagreements rather than forcing consensus.</p></div><div className="path-list">{rounds.map((x,i)=><article className="path-row" key={x[0]}><span className="path-num">{String(i+1).padStart(2,"0")}</span><div><h3>{x[0]}</h3><p>{x[1]}</p></div><span className="event-result">Exercise</span></article>)}</div></section>
  <section className="offer-grid wrap"><article className="offer-card"><p className="section-label">Expert analysis · reveal after deciding</p><h2>A responsible answer is likely “repair and investigate first.”</h2><details><summary>Reveal the reasoning</summary><p>The evidence supports a service problem, but not the candidate intervention. Conflicting goals, missing quality measures, professional-judgment boundaries, retention uncertainty, absent accessibility testing, and an unlabeled routing dataset prevent a responsible pilot.</p><p>A proportionate next step is to improve intake instructions, define urgent escalation, measure routing and correction, resolve data handling, involve affected users, and create a labeled test set. Only then should the owner reconsider a tightly bounded drafting experiment with mandatory coordinator review and explicit exclusions.</p></details><h3>What could change that answer?</h3><p>Verified data showing a narrow, repetitive drafting task; resolved authority and retention; accessible design; capable review capacity; representative testing; a working fallback; and stop thresholds could justify a limited test. They would not authorize deployment.</p></article><aside><p className="section-label">Assessment</p><h2>Score the reasoning—not the conclusion.</h2><ul className="scope-list"><li>Decision is product-neutral and owned</li><li>Claims are tied to exhibits and limits</li><li>Missing voices and consequences are visible</li><li>All five paths receive fair comparison</li><li>Professional judgment boundaries are explicit</li><li>Controls and stop conditions are operational</li><li>Dissent and unknowns remain in the record</li><li>Next action and review trigger are dated</li></ul><p>A complete submission addresses all eight. A different disposition can be strong if its evidence and conditions support it.</p></aside></section>
  <section className="wrap boundary"><p className="section-label">Facilitation guide</p><div><h2>Run it solo or with a group.</h2><p><strong>Solo:</strong> decide before revealing the analysis, then write what changed. <strong>Group:</strong> assign sponsor, intake coordinator, prospective client/access advocate, attorney, and privacy/security reviewer roles; deliberate for 45 minutes; require each role to name one condition and one stop trigger; then issue a joint record with preserved dissent.</p><div className="actions"><Link className="button primary" href="/tools/decision-record">Start the record</Link><Link className="button" href="/learning">Return to Learning</Link></div></div></section>
</main></SiteShell>}
