export type MasterclassChapter={number:string;title:string;minutes:string;teaching:string[];practice:string;evidence:string};

const c=(number:string,title:string,minutes:string,teaching:string[],practice:string,evidence:string):MasterclassChapter=>({number,title,minutes,teaching,practice,evidence});
export const masterclassChapters:MasterclassChapter[]=[
c("01","The work beneath the tool request","3 min",["Choose one recurring piece of work that consumes more attention than it should. Keep the example private and nonconfidential. You need an observable process, not a product idea.","The finish line is a defensible next move—including redesign, human-led work, or more investigation—not an automatic AI recommendation."],"Name one recurring process without names, records, credentials, or confidential facts.","A recurring process—not a product category."),
c("02","AI is not the starting point","3 min",["Tool-first thinking compresses several decisions into one purchase. Ask what is happening in the work, where it is actually stuck, and what—if anything—technology should do next.","Novelty, vendor preference, and competitive pressure are not diagnosis. Automation is one possible intervention, not the objective."],"Replace ‘We need AI for ___’ with ‘The work stalls when ___, causing ___.’","A trigger, breakdown, and consequence."),
c("03","What the masterclass gives—and does not","3 min",["This public course teaches the complete decision method through a prepared fictional case. It does not diagnose a confidential case or authorize implementation.","Individualized assessment, case research, collaborative construction, and client-specific outputs belong in the Clinic or a private Decision Review."],"Classify your question as general education, a bounded nonconfidential case, or private review.","The correct service boundary."),
c("04","Privacy and professional boundaries","3 min",["Describe the shape of work, not sensitive contents. Do not enter names, employee or health records, payment data, passwords, tax records, trade secrets, privileged material, or confidential information.","A model does not replace authoritative sources or qualified professionals. Professional decisions retain their professional boundaries."],"List the data classes touched, using categories only; mark confidential, regulated, privileged, or credentialed data.","A prohibited-data and escalation list."),
c("05","Adoption evidence needs context","5 min",["Adoption statistics do not create an implementation mandate. Definition, wording, firm size, sample, date, and self-report limits travel with every claim.","Uneven adoption means urgency cannot substitute for a clear work problem and testable value hypothesis."],"For one AI statistic, record source, date, population, definition, and a limitation—or mark it unverified.","A contextualized evidence claim."),
c("06","Pressure is real; AI is not automatically the answer","5 min",["Customer demand, capacity, hiring difficulty, and rising costs justify examining work; they do not prove AI caused or will solve the problem.","Choose a constraint important enough to fix, bounded enough to test, and safe enough to learn from."],"State why the constraint matters, how it can be bounded, and what makes a test unsafe.","Importance, test boundary, and safety boundary."),
c("07","Translate the tool request into a work problem","4 min",["‘We need a chatbot’ says almost nothing. ‘Qualified inquiries stall because nobody owns the handoff after the first call’ names trigger, failure, and consequence.","‘Automate proposals’ becomes examinable only when approved notes, drafting, scope/price review, owner, and time burden are visible."],"Write trigger → current steps → breakdown → consequence.","An observable process statement."),
c("08","Define → Examine → Decide → Build","5 min",["Define the work and desired change. Examine friction, inputs, judgment, risk, value, capacity, and context. Decide among four legitimate findings. Build the smallest safe next action.","Build comes last. Understanding and deciding earn the right to build."],"Name your current stage and the evidence required to move forward.","A stage and evidence requirement."),
c("09","The five-part Opportunity Map","6 min",["Friction locates recurring loss. Inputs identify what correct performance requires and who may use it. Judgment names decisions involving interpretation, approval, empathy, negotiation, taste, duty, or responsibility.","Risk identifies possible harm and detection. Value defines observable improvement before a demonstration can impress you."],"Write one sentence each for Friction, Inputs, Judgment, Risk, and Value.","A five-lens map with no vendor selected."),
c("10","Meet Kōkua Studio","3 min",["Kōkua Studio is a fictional two-person Hawaiʻi service studio. Its owner spends about six hours each week converting discovery-call notes into customized proposals.","The tempting answer—use AI to write proposals—is held back while the work is examined. This is not a client story or claimed result."],"Predict the cause of delay, labeling it as a hypothesis rather than a fact.","A clearly labeled hypothesis."),
c("11","Friction is not the same as cause","4 min",["The process is: call ends → notes scattered → services checked → price checked → draft written → owner reviews → proposal sent. Six hours and delay are symptoms.","Causes may be scattered notes, unclear ownership, excess variants, stale language, tacit pricing, or drafting. Faster text can move instability downstream."],"Map each step and circle where delay or rework first enters.","A process map and cause hypothesis."),
c("12","Inputs require permission and authority","4 min",["Correct work needs an approved call summary, current services, real availability, pricing rules, and approved language. Existence does not establish currency, completeness, authority, or tool permission.","A safe first test uses fabricated or deliberately redacted inputs and controlled approved references. Convenience is not permission."],"For every input record source, owner, freshness, permission, completeness, and test eligibility.","An approved-input register."),
c("13","Preserve the judgments that make work true","4 min",["The owner decides client fit, realistic scope, price, supportable promises, exceptions, and final send. Her value is not typing sentences.","These judgments are the responsibility structure. AI may organize or draft but must not silently inherit undelegated authority."],"Mark each decision assistable, review-required, or human-owned; name the authorized owner.","A judgment and authority map."),
c("14","Design risk detection—not only prevention","4 min",["Failures include exposed notes, invented deliverables, stale prices, omitted limits, and polished unapproved promises. Reduce likelihood and design detection before harm.","‘A human reviews it’ is incomplete without a reviewer, checklist, evidence, escalation route, and missed-error consequence."],"For three failures, add prevention, detection, reviewer, and stop condition.","A failure-and-detection table."),
c("15","Define value before the demonstration","4 min",["Kōkua Studio’s baseline is about six owner-hours weekly plus current turnaround. Measure draft time, correction rate, turnaround, and unapproved scope, prices, or promises.","Time saved is not success if substantive errors rise. Precommit the baseline, measure, and guardrail."],"Write one baseline, target measure, quality guardrail, and observation method.","A precommitted evaluation rule."),
c("16","Four findings are legitimate","5 min",["The map permits four equal findings: bounded experiment; redesign first; keep human-led; or insufficient information.","‘No AI’ and ‘not yet’ are successful when evidence supports them. The method evaluates work; it does not force adoption."],"Choose a provisional finding, cite supporting evidence, and name what could change it.","A finding and reconsideration condition."),
c("17","Choose the lowest sufficient intervention","5 min",["Move only as far as needed: ownership → template/checklist → ordinary automation → AI-assisted step → integrated workflow → custom system.","Complexity creates setup, testing, training, maintenance, security, and exit costs. Do not buy architecture because a demo hides labor."],"Name the lowest sufficient rung; explain why the one below fails and the one above is unnecessary.","A proportionate intervention choice."),
c("18","Build Kōkua Studio’s bounded experiment","5 min",["Test ten fabricated or redacted historical cases against an approved source packet. Produce drafts only; the owner checks fit, scope, price, promises, missing facts, and prohibited language.","Compare time and correction burden with baseline. Stop for confidential input, an unapproved promise surviving review, or correction burden erasing the benefit."],"Define cases, inputs, output status, checklist, comparison, fallback, and stop rule.","A reversible experiment charter."),
c("19","A reliable workflow is more than a prompt","4 min",["Connect an input boundary, approved references, structured instruction, output, review checklist, decision owner, destination, evidence log, and maintenance owner.","A prompt can create a moment. A workflow must survive ordinary use, exceptions, turnover, vendor change, and wrong output."],"Draw the chain, name every handoff owner, and mark missing components.","An end-to-end operating workflow."),
c("20","Place is an operating condition","4 min",["Hawaiʻi context can change tax, licensing, shipping, staffing, infrastructure, bandwidth, relationships, and failure consequences. These are requirements, not decoration.","Route jurisdictional questions to current authoritative sources and qualified review. Generic generated checklists must not flatten distinct obligations."],"List three place-specific conditions and the authoritative source or reviewer for each.","A place-aware source map."),
c("21","Build the Monday Plan","4 min",["Document trigger, owner, inputs, steps, decisions, exceptions, destination, and time. Mark sensitive inputs and human judgment. Define one reversible improvement with fabricated, historical, or non-sensitive material.","Before buying, name user, permitted data, output, reviewer, total cost, measure, stop evidence, and review date."],"Write first action, owner, proceed evidence, stop evidence, and review date.","A specific Monday Plan."),
c("22","Choose the continuation path","3 min",["Use the public method independently when you can own a bounded analysis. Use the Clinic for collaborative construction around a nonconfidential case.","Use private Decision Review for confidentiality, research, jurisdictional evidence, or written recommendations. Paid value is individualized judgment and build work—not withheld education."],"Choose independent use, Clinic, or private review and state why.","A route matched to the case boundary."),
c("23","Ask questions without manufacturing certainty","12 min",["General questions address the method, evidence, or fictional case. If an answer depends on missing facts, identify needed information rather than inventing certainty.","Response frame: the general problem is ___. AI may help with ___, while ___ stays human-owned. A safe test requires ___. The main risk or missing fact is ___."],"Answer one general, nonconfidential question with the response frame.","A bounded answer naming uncertainty."),
c("24","Examine the work before you automate it","3 min",["Find one worthwhile constraint. Protect people and information. Preserve judgments carrying responsibility. Run one bounded test—and keep permission to stop.","Completion means you can defend a next move with evidence. It does not make AI win, authorize deployment, or replace professional review."],"Read your Map, finding, intervention, experiment, and Monday Plan together; resolve contradictions.","A coherent, reviewable decision record.")];

export const checkQuestions=[
{prompt:"Which comes first?",options:["Choose a vendor","Define the recurring work","Write a prompt"],answer:1,reason:"Work and desired change are defined before tools."},
{prompt:"What makes human review operational?",options:["A reviewer, checklist, evidence, escalation, and consequence","A general promise","A final glance"],answer:0,reason:"Review must name responsibility and detection mechanics."},
{prompt:"Which is a legitimate finding?",options:["AI adoption only","Experiment, redesign, human-led, or insufficient information","Whatever the demo suggests"],answer:1,reason:"All four findings receive equal weight."},
{prompt:"What is Kōkua Studio’s safest first test?",options:["Automate live proposals","Ten fabricated/redacted cases with approved sources and owner review","Paste raw notes into a public tool"],answer:1,reason:"The test is bounded, reversible, and separated from live work."},
{prompt:"What is success?",options:["An impressive output","Time saved regardless of errors","Predefined improvement without violating the guardrail"],answer:2,reason:"Value is judged against baseline and guardrail."},
{prompt:"When is no AI successful?",options:["Never","When evidence supports human-led work or a lower intervention","Only after buying a tool"],answer:1,reason:"The method does not force adoption."}];
