"use client";
import {useEffect,useMemo,useState} from "react";
import {checkQuestions,masterclassChapters} from "./course-data";
const KEY="aloha-ai:flagship-masterclass:v1";
type State={completed:number[];answers:Record<number,number>;notes:Record<string,string>};
const blank:State={completed:[],answers:{},notes:{}};
export function MasterclassWorkspace(){
 const [state,setState]=useState<State>(blank),[ready,setReady]=useState(false),[message,setMessage]=useState("Your work stays in this browser.");
 useEffect(()=>{const restore=window.setTimeout(()=>{try{const saved=localStorage.getItem(KEY);if(saved)setState(JSON.parse(saved))}catch{}setReady(true)},0);return()=>window.clearTimeout(restore)},[]);
 useEffect(()=>{if(ready)localStorage.setItem(KEY,JSON.stringify(state))},[ready,state]);
 const score=useMemo(()=>checkQuestions.filter((q,i)=>state.answers[i]===q.answer).length,[state.answers]);
 const next=masterclassChapters.findIndex((_,i)=>!state.completed.includes(i)),percent=Math.round(state.completed.length/24*100);
 function toggle(i:number){setState(s=>({...s,completed:s.completed.includes(i)?s.completed.filter(x=>x!==i):[...s.completed,i].sort((a,b)=>a-b)}))}
 function download(name:string,content:string){const url=URL.createObjectURL(new Blob([content],{type:"text/markdown"})),a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);setMessage(`${name} downloaded.`)}
 function exportRecord(){download("aloha-ai-masterclass-learning-record.md",`# AI & Your Work — self-directed learning record\n\nExported: ${new Date().toISOString()}\n\nLearner-controlled record; not a grade, certification, credential, implementation approval, or professional advice.\n\n## Progress\n${state.completed.map(i=>`- [x] ${masterclassChapters[i].number}. ${masterclassChapters[i].title}`).join("\n")}\n\n## Working notes\n${Object.entries(state.notes).filter(([,v])=>v.trim()).map(([k,v])=>`### ${k}\n${v}`).join("\n\n")}\n\n## Knowledge check\nScore at export: ${score}/${checkQuestions.length}.\n`)}
 function clear(){if(!confirm("Delete all masterclass progress, notes, and answers from this browser?"))return;localStorage.removeItem(KEY);setState(blank);setMessage("Local masterclass record deleted.")}
 return <><section className="wrap masterclass-dashboard" id="course-workspace"><p className="section-label">Self-paced course workspace · saved locally</p><div className="section-head"><div><h2>Your complete masterclass record.</h2><p>No account, submission, grading, or credential. Progress and notes remain only in this browser.</p></div><div className="masterclass-meter"><strong>{percent}%</strong><span>{state.completed.length} of 24 chapters</span><progress max="24" value={state.completed.length}/></div></div><div className="course-resume"><div><strong>{ready?next<0?"All chapters marked complete.":`Next: Chapter ${masterclassChapters[next].number}`:"Restoring your work…"}</strong><span>{next<0?"Review any chapter or export your record.":masterclassChapters[next]?.title}</span></div><a className="button" href={next<0?"#chapter-01":`#chapter-${masterclassChapters[next]?.number}`}>{next<0?"Review course":"Resume course"}</a></div></section>
 <section className="wrap masterclass-reader" id="curriculum"><div className="section-head"><div><p className="section-label">Complete teaching sequence</p><h2>Twenty-four taught chapters—not an outline.</h2></div><p>Read in order, complete the practice, and mark each chapter when its evidence output exists.</p></div>{masterclassChapters.map((chapter,i)=><details className="masterclass-chapter" id={`chapter-${chapter.number}`} key={chapter.number} open={i===0}><summary><span>{chapter.number}</span><div><small>{chapter.minutes}</small><h3>{chapter.title}</h3></div><strong>{state.completed.includes(i)?"Complete":"Open"}</strong></summary><div className="chapter-body"><div className="chapter-teaching"><p className="section-label">Teaching</p>{chapter.teaching.map(p=><p key={p}>{p}</p>)}</div><aside><p className="section-label">Practice</p><p>{chapter.practice}</p><label>Private working note<textarea value={state.notes[chapter.title]||""} onChange={e=>setState(s=>({...s,notes:{...s.notes,[chapter.title]:e.target.value}}))} placeholder="Use categories and nonconfidential language only."/></label><p><strong>Evidence to continue:</strong> {chapter.evidence}</p><label className="chapter-complete"><input type="checkbox" checked={state.completed.includes(i)} onChange={()=>toggle(i)}/> I completed the reading and created the evidence output.</label></aside></div></details>)}</section>
 <section className="wrap knowledge-lab"><div className="section-head"><div><p className="section-label">Final knowledge check</p><h2>Can you defend the method?</h2></div><p>Immediate feedback is educational. It is not a grade or credential.</p></div>{checkQuestions.map((q,i)=><fieldset className="knowledge-question" key={q.prompt}><legend>{i+1}. {q.prompt}</legend>{q.options.map((o,j)=><label key={o}><input type="radio" name={`mc-${i}`} checked={state.answers[i]===j} onChange={()=>setState(s=>({...s,answers:{...s.answers,[i]:j}}))}/>{o}</label>)}{state.answers[i]!==undefined&&<p className={state.answers[i]===q.answer?"feedback correct":"feedback review"}><strong>{state.answers[i]===q.answer?"Correct.":"Review this."}</strong> {q.reason}</p>}</fieldset>)}<p className="knowledge-score">Current result: <strong>{score}/{checkQuestions.length}</strong></p><div className="course-actions workspace-actions"><button className="button primary" onClick={exportRecord}>Export learning record</button><a className="button" href="/aloha-ai-masterclass-working-guide.md" download>Download workbook</a><button className="text-button danger-action" onClick={clear}>Delete local course record</button></div><p className="action-status" aria-live="polite">{message}</p></section></>}
