import Link from "next/link";
import type {Metadata} from "next";
import {SiteShell} from "../../site-shell";

export const metadata:Metadata={title:"AI & Your Work · Flagship Masterclass",description:"The complete 90-minute Aloha AI flagship masterclass for examining work before automating it."};

const chapters=[
  ["01","AI is not the starting point","Begin with a decision class and the recurring work—not a tool parade."],
  ["02","The knowledge is public; the build is paid","Separate complete public education from case-specific diagnosis, design, and implementation."],
  ["03","Privacy and professional boundaries","Use no client names, credentials, health, payment, tax, employee, privileged, or confidential records."],
  ["04","Adoption evidence needs context","Definitions, firm size, survey design, and self-report limits travel with every adoption claim."],
  ["05","Pressure is real; technology is not automatically the answer","Customer demand, capacity, rising input costs, and labor pressure establish a need to examine—not a mandate to automate."],
  ["06","Translate the tool request into a work problem","Replace “we need a chatbot” with the stalled outcome, broken handoff, missing authority, or recurring constraint underneath it."],
  ["07","Define → Examine → Decide → Build","State the work, make the system visible, choose a finding, and build only the smallest next action."],
  ["08","Examine five things before selecting a tool","Map friction, inputs, judgment, risk, and value."],
  ["09","Meet Kōkua Studio","Use a fictional two-person Hawaiʻi service studio whose customized proposals consume twelve owner-hours each week."],
  ["10","Friction is not the same as cause","Trace calls, scattered notes, service and price checks, drafting, review, and delivery before selecting an intervention."],
  ["11","Inputs require permission and authority","Distinguish available information from approved, current, complete, and appropriately usable information."],
  ["12","Preserve the judgments that make work true","Client fit, scope, price, promises, exceptions, and final responsibility remain owned decisions."],
  ["13","Design risk detection—not only prevention","Define how confidential input, invented deliverables, stale prices, missing limitations, and unsupported confidence will be caught."],
  ["14","Define value before the demonstration impresses you","Record baseline time, turnaround, correction burden, and a guardrail against more substantive errors."],
  ["15","Four findings are legitimate","A bounded experiment, redesign first, keep human-led, and insufficient information receive equal weight."],
  ["16","Choose the lowest sufficient intervention","Move only as far as necessary: ownership, template, checklist, ordinary automation, AI assistance, integrated workflow, or custom system."],
  ["17","Design a bounded experiment","Use fabricated or redacted historical cases, approved sources, draft-only output, owner review, baseline comparison, and a stop rule."],
  ["18","A reliable workflow is more than a prompt","Connect input boundary, references, structured instruction, draft, review checklist, owner, destination, and evidence log."],
  ["19","Place is an operating condition","Hawaiʻi tax, licensing, infrastructure, staffing, shipping, bandwidth, relationships, and consequences cannot be flattened into decorative locality."],
  ["20","Begin before any purchase","Document one process, mark judgment and sensitive inputs, and define one reversible test and measure."],
  ["21","Build the Monday Plan","Name the owner, first action, evidence required to proceed, stop evidence, and review date."],
  ["22","Know the continuation paths","Use the public method independently, bring a bounded case to an Opportunity Clinic, or use a private Decision Review when confidentiality or written analysis is required."],
  ["23","Ask general questions without disclosing a case","Questions may address the method, evidence, or fictional example; missing facts produce a request for evidence, not invented certainty."],
  ["24","Examine the work before you automate it","Find one worthwhile constraint, protect the people and information involved, preserve responsible judgment, and run one test you can learn from."]
];

const map=[
  ["Friction","Where time, attention, money, capacity, or trust repeatedly leaks—and what may actually cause it."],
  ["Inputs","What correct work requires, where it lives, whether it is current, and who may use it."],
  ["Judgment","Interpretation, approval, empathy, negotiation, taste, duty, or responsibility a person must own."],
  ["Risk","How people, information, obligations, access, or outcomes could be harmed or misrepresented."],
  ["Value","The observable improvement that would justify changing the system, defined before the test."]
];

export default function Masterclass(){return <SiteShell><main id="main">
  <section className="page-hero wrap"><p className="kicker">Aloha AI flagship masterclass · complete 90-minute edition</p><h1>AI &amp; Your Work: <em>Examine the Work Before You Automate It.</em></h1><p className="lede">The complete flagship learning experience for deciding whether recurring work calls for AI, ordinary automation, process redesign, human judgment, or more investigation.</p><div className="actions"><a className="button primary" href="#masterclass">Begin the masterclass</a><a className="button" href="/aloha-ai-masterclass-working-guide.md" download>Download the participant workbook</a></div></section>
  <section className="event-status"><div className="wrap event-status-grid"><div><span>Length</span><strong>90 minutes</strong></div><div><span>Teaching sequence</span><strong>24 chapters</strong></div><div><span>Method</span><strong>Define · Examine · Decide · Build</strong></div><div><span>Case</span><strong>Fictional Kōkua Studio</strong></div></div></section>
  <section className="wrap pathways"><div className="section-head"><div><p className="section-label">The completed product</p><h2>The live masterclass and the web edition share one curriculum.</h2></div><p>The original delivery package contains the complete slide deck, word-for-word execution script, timing, source ledger, Kōkua Studio demonstration, Q&amp;A response bank, participant handout, accessibility and privacy controls, contingency routes, and rehearsal gates. This web edition translates that finished teaching into a public, self-directed experience; it does not substitute a new five-lesson course.</p></div><article className="offer-card"><h3>By the end, you can:</h3><ul className="scope-list"><li>translate a tool request into a work problem;</li><li>map friction, inputs, judgment, risk, and value;</li><li>reach one of four legitimate findings without forcing AI to win;</li><li>choose the lowest sufficient intervention;</li><li>design human review, a measure, and a stop rule; and</li><li>leave with a Monday Plan rather than a product recommendation.</li></ul></article></section>
  <section className="wrap pathways" id="masterclass"><div className="section-head"><div><p className="section-label">Opportunity Map</p><h2>Five lenses control the inquiry.</h2></div><p>Complete these in the workbook while holding one recurring, nonconfidential process in mind.</p></div><div className="path-list">{map.map((x,i)=><article className="path-row" key={x[0]}><span className="path-num">{String(i+1).padStart(2,"0")}</span><div><h3>{x[0]}</h3><p>{x[1]}</p></div><span className="event-result">Map</span></article>)}</div></section>
  <section className="wrap pathways"><div className="section-head"><div><p className="section-label">Complete teaching sequence</p><h2>Twenty-four cumulative chapters.</h2></div><p>The sequence moves from evidence and boundaries through the full fictional case, decision, experiment, system design, place-aware application, and Monday action.</p></div><div className="path-list">{chapters.map(x=><article className="path-row" key={x[0]}><span className="path-num">{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div><span className="event-result">Chapter</span></article>)}</div></section>
  <section className="offer-grid wrap"><article className="offer-card"><p className="section-label">Prepared case disposition</p><h2>Kōkua Studio starts with a bounded experiment.</h2><p>Assuming its inputs can be stabilized, the studio tests ten fabricated or deliberately redacted historical cases against an approved source packet. The system drafts only. The owner reviews fit, scope, price, promises, exceptions, missing facts, and prohibited language. Time and correction burden are compared with baseline.</p><p><strong>Stop:</strong> confidential material enters the system, an unapproved promise survives review, or correction burden eliminates the time benefit.</p></article><aside><p className="section-label">Four legitimate findings</p><h2>The method does not force adoption.</h2><ol><li>Run a bounded experiment.</li><li>Redesign the process first.</li><li>Keep the work human-led.</li><li>Record that information is insufficient.</li></ol><p>“No AI” and “not yet” are successful findings when the evidence supports them.</p></aside></section>
  <section className="wrap boundary"><p className="section-label">Your finish line</p><div><h2>Leave with a Monday Plan.</h2><p>Document one recurring process exactly as it happens. Mark every point containing sensitive inputs or human judgment. Define one reversible improvement using appropriate material. Name the baseline, measure, reviewer, guardrail, stop rule, owner, and review date before buying anything.</p><div className="actions"><a className="button primary" href="/aloha-ai-masterclass-working-guide.md" download>Complete the workbook</a><Link className="button" href="/studio">Use Opportunity Studio</Link><Link className="button" href="/work/ai-opportunity-clinic">Apply it in a Clinic</Link></div></div></section>
  <section className="offer-grid wrap"><article><p className="section-label">Public learning boundary</p><h2>Education—not case diagnosis.</h2><p>Do not submit client, employee, health, financial, tax, payment, credential, security-sensitive, privileged, proprietary, or other confidential information. The masterclass does not recommend a vendor, authorize implementation, establish compliance, or provide individualized legal, security, clinical, financial, employment, accounting, or investment advice.</p></article><aside><p className="section-label">Evidence maintenance</p><h2>Sources must remain current.</h2><p>The original delivery package includes a claim-level source ledger. Time-sensitive adoption, vendor, tax, licensing, and policy claims must be rechecked before each facilitated delivery. The enduring method remains public; dated evidence is never silently treated as current.</p><Link className="text-link" href="/insights">Inspect the Source Desk →</Link></aside></section>
</main></SiteShell>}
