import Link from "next/link";
import type {Metadata} from "next";
import {SiteShell} from "../../site-shell";

export const metadata:Metadata={title:"Free Aloha AI Masterclass",description:"Complete a free, self-paced masterclass for deciding where AI belongs before choosing a tool or launching a pilot."};
const lessons=[
  ["01","Name the decision—not the technology","Write one sentence that identifies the work, the people affected, the accountable owner, and the outcome that matters. If the sentence begins with a product name, rewrite it.","What decision would still exist if every AI product disappeared tomorrow?"],
  ["02","Make the current work visible","Map the trigger, inputs, judgment points, exceptions, handoffs, evidence, delays, and consequences. Include the unofficial work people do to keep the process functioning.","Where does the current process rely on context, trust, discretion, or repair?"],
  ["03","Keep four paths open","Compare AI assistance with process repair, human-led work, a smaller investigation, and no action. A responsible inquiry does not assume automation must win.","Which non-AI change could produce most of the desired benefit with fewer new risks?"],
  ["04","Test the operating conditions","Check authority, appropriate data, affected-party input, accessibility, privacy, security, review capacity, fallback, measurement, incident response, and stop conditions.","Which missing condition would make a pilot irresponsible even if the tool performed well?"],
  ["05","Choose the smallest honest next step","Select one outcome: keep the work human-led; repair the process; gather missing evidence; compare options; or design a bounded, reversible pilot.","What evidence would justify advancing—and what evidence would make you stop?"],
];
export default function Masterclass(){return <SiteShell><main id="main">
  <section className="page-hero wrap"><p className="kicker">Free Aloha AI Masterclass · open now</p><h1>What should we <em>actually use AI for?</em></h1><p className="lede">A complete, self-paced text masterclass for examining the work before choosing a tool—and recognizing when redesign, human-led work, or more investigation is the responsible result.</p><div className="actions"><a className="button primary" href="/aloha-ai-masterclass-working-guide.md" download>Download the working guide</a><Link className="button" href="/studio">Open Opportunity Studio</Link></div></section>
  <section className="event-status"><div className="wrap event-status-grid"><div><span>Price</span><strong>Free</strong></div><div><span>Time</span><strong>45–60 minutes</strong></div><div><span>Format</span><strong>Self-paced text</strong></div><div><span>Account</span><strong>Not required</strong></div></div></section>
  <section className="wrap pathways"><div className="section-head"><div><p className="section-label">The complete masterclass</p><h2>Decide before deploying.</h2></div><p>Read each lesson, answer its working question in the guide, and leave with one bounded next step. “No AI,” “not yet,” and “redesign first” are valid findings.</p></div><div className="path-list">{lessons.map(x=><article className="path-row" key={x[0]}><span className="path-num">{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p><p><strong>Working question:</strong> {x[3]}</p></div><span className="event-result">Lesson</span></article>)}</div></section>
  <section className="offer-grid wrap"><article className="offer-card"><p className="section-label">Your finish line</p><h2>Leave with a decision path—not an AI recommendation.</h2><p>Your completed guide should name the decision, current workflow, affected people, evidence gaps, non-AI alternatives, controlling conditions, and next review point.</p><div className="actions"><a className="button primary" href="/aloha-ai-masterclass-working-guide.md" download>Get the guide</a><Link className="button" href="/tools">Use a decision tool</Link></div></article><aside><p className="section-label">Public boundary</p><h2>General education—not individualized advice.</h2><p>The masterclass uses general prompts and does not diagnose your work, recommend a vendor, provide legal advice, certify readiness, or establish that AI belongs in a workflow. Do not put confidential or sensitive information in the guide.</p><Link className="text-link" href="/work/ai-opportunity-clinic">Need collaborative application? Review the Clinic →</Link></aside></section>
</main></SiteShell>}
