import Link from "next/link";
import type {Metadata} from "next";
import {SiteShell} from "../../site-shell";

export const metadata:Metadata={
  title:"What Should We Actually Use AI For? · Free Masterclass",
  description:"A complete 45–60 minute masterclass for making an evidence-led AI opportunity decision."
};

const lessons=[
  {n:"01",minutes:"10 min",title:"Name the decision—not the technology",outcome:"Turn an AI request into a decision statement with an owner, affected people, and a measurable outcome.",teach:[
    ["Separate the request from the need","“We need a chatbot” is a proposed intervention. The need might be faster answers, fewer repeated questions, or better access. Removing the product name exposes the decision you actually own."],
    ["Name who carries the consequences","Identify the accountable owner, the people doing the work, and everyone affected by errors or delays. A benefit for one group can become hidden work or risk for another."],
    ["Define an observable outcome","Use a comparison and a time boundary: reduce unresolved requests after one contact from the current baseline, without lowering accessibility or increasing staff rework, during a defined test period."]
  ],check:"Which is the strongest decision statement?",options:["Should we buy an AI chatbot?","How can we improve first-contact answers for students while preserving accessible human escalation?","Which vendor has the best model?","How quickly can IT deploy AI?"],answer:"How can we improve first-contact answers for students while preserving accessible human escalation? It names the work and guardrail without preselecting a tool.",exercise:"Write a one-sentence decision statement: We must decide how to ___ for ___, owned by ___, so that ___ improves from ___ to ___ by ___, while preserving ___."},
  {n:"02",minutes:"12 min",title:"Make the current work visible",outcome:"Map the real workflow, including judgment, exceptions, unofficial repair work, and the evidence you do not yet have.",teach:[
    ["Follow one real case","Map trigger, inputs, actions, handoffs, judgment points, exceptions, evidence, and outcome. A policy diagram is not enough; follow what people actually do."],
    ["Look for invisible labor","People translate unclear requests, reconstruct missing context, calm frustrated users, and repair system mistakes. Automation can displace this work rather than remove it."],
    ["Distinguish facts from assumptions","Label each important claim as observed, measured, reported, inferred, or unknown. If the case for AI depends on an unknown, investigation—not procurement—is the next step."]
  ],check:"What should you do when the official process differs from the work people actually perform?",options:["Use the official process only","Treat the difference as noise","Map both and investigate why the workaround exists","Automate the official steps immediately"],answer:"Map both and investigate why the workaround exists. The workaround may contain essential context, judgment, or repair work.",exercise:"Map one representative case from trigger to outcome. Mark each judgment point J, exception E, handoff H, repair R, and evidence gap ?."},
  {n:"03",minutes:"10 min",title:"Keep five paths open",outcome:"Compare AI with process repair, human-led improvement, investigation, and no new intervention.",teach:[
    ["Start with process repair","Remove duplicate intake, clarify ownership, improve source material, or simplify a rule. Many apparent AI problems are process or information problems."],
    ["Protect human-led and no-action paths","Human judgment may be the service. Doing nothing new can be responsible when the current process is acceptable or change would create disproportionate risk."],
    ["Make AI earn its place","Compare every path against the same outcome, evidence, burden, reversibility, and failure consequences. Do not give AI a lower standard because it is novel."]
  ],check:"A team has inconsistent answers because its policy pages conflict. What is the best first path?",options:["Train a chatbot on all pages","Repair and govern the source material","Remove human review","Buy a larger model"],answer:"Repair and govern the source material. AI would reproduce or obscure the underlying conflict.",exercise:"Score five paths—process repair, human-led improvement, investigation, no new intervention, bounded AI assistance—on benefit, evidence, burden, reversibility, and failure impact."},
  {n:"04",minutes:"12 min",title:"Test the operating conditions",outcome:"Identify the controls, capabilities, and stop conditions required before a responsible pilot.",teach:[
    ["Conditions are not aspirations","“We will have human review” is not a control until the reviewer, authority, response time, escalation rule, and capacity are defined."],
    ["Design for affected people","Test accessibility, language, notice, consent where relevant, contestability, and access to a human path. Include affected people before the design is locked."],
    ["Plan failure before launch","Define monitoring, incident ownership, rollback, records, fallback service, and stop thresholds. If stopping is operationally impossible, the pilot is not reversible."]
  ],check:"Which is a testable stop condition?",options:["Stop if it feels risky","Stop if leadership is concerned","Pause within one business day if unsupported answers exceed 3% in the reviewed sample","Stop if users dislike AI"],answer:"Pause within one business day if unsupported answers exceed 3% in the reviewed sample. It specifies a metric, threshold, and response time.",exercise:"For authority, data, affected-party input, accessibility, privacy, security, review, measurement, incident response, fallback, and stop conditions, mark present/missing/uncertain and cite evidence."},
  {n:"05",minutes:"10 min",title:"Choose the smallest honest next step",outcome:"Issue a reasoned disposition and a Monday-morning action without overstating readiness.",teach:[
    ["Choose a disposition","Select human-led, process repair, investigate, compare options, bounded pilot, or stop. “Not yet” is a decision when it names the missing evidence and review point."],
    ["Bound any pilot","Specify users, tasks, data, duration, authority, human review, success measures, exclusions, fallback, and stop rules. A pilot tests a claim; it is not a quiet launch."],
    ["Create a decision record","Record evidence, assumptions, alternatives, dissent, owner, date, conditions, and next review. The record lets others challenge and revisit the decision."]
  ],check:"When is a bounded pilot the right next step?",options:["Whenever a vendor offers a trial","When the decision is politically popular","When the claim is testable, prerequisites exist, exposure is bounded, and rollback is real","When the team has no baseline"],answer:"When the claim is testable, prerequisites exist, exposure is bounded, and rollback is real. A baseline and named controls are part of those prerequisites.",exercise:"Complete the final Decision Record and name the first action, owner, due date, evidence to advance, and evidence that requires stopping."}
];

export default function Masterclass(){return <SiteShell><main id="main">
  <section className="page-hero wrap"><p className="kicker">Free masterclass · complete open edition</p><h1>What should we <em>actually use AI for?</em></h1><p className="lede">A complete, self-paced 45–60 minute course for moving from an AI request to a defensible decision—without assuming AI must be the answer.</p><div className="actions"><a className="button primary" href="/aloha-ai-masterclass-working-guide.md" download>Download the workbook</a><a className="button" href="#lesson-1">Start lesson 1</a></div></section>
  <section className="event-status"><div className="wrap event-status-grid"><div><span>Price</span><strong>Free</strong></div><div><span>Length</span><strong>45–60 minutes</strong></div><div><span>Includes</span><strong>5 lessons + worked case</strong></div><div><span>Assessment</span><strong>5 checks + Decision Record</strong></div></div></section>
  <section className="wrap pathways"><div className="section-head"><div><p className="section-label">How to use it</p><h2>Learn, check, apply, decide.</h2></div><p>Download the workbook. Complete each teaching section, answer its knowledge check before revealing the reasoning, and apply the exercise to one real or fictional workflow. Do not enter confidential or regulated information.</p></div>
  <article className="offer-card"><p className="section-label">Learning objectives</p><h2>By the end, you can:</h2><ul><li>reframe a technology request as an owned operational decision;</li><li>separate evidence from assumptions in a real workflow;</li><li>compare five intervention paths on equal terms;</li><li>test whether responsible operating conditions exist; and</li><li>document a justified disposition and smallest next step.</li></ul></article></section>
  {lessons.map((l,i)=><section className="wrap pathways" id={`lesson-${i+1}`} key={l.n}><div className="section-head"><div><p className="section-label">Lesson {l.n} · {l.minutes}</p><h2>{l.title}</h2></div><p><strong>Outcome:</strong> {l.outcome}</p></div><div className="path-list">{l.teach.map((t,j)=><article className="path-row" key={t[0]}><span className="path-num">{j+1}</span><div><h3>{t[0]}</h3><p>{t[1]}</p></div><span className="event-result">Teach</span></article>)}</div><div className="offer-grid"><article className="offer-card"><p className="section-label">Knowledge check</p><h3>{l.check}</h3><ol>{l.options.map(o=><li key={o}>{o}</li>)}</ol><details><summary>Reveal answer and reasoning</summary><p>{l.answer}</p></details></article><aside><p className="section-label">Workbook exercise</p><h3>Apply the lesson</h3><p>{l.exercise}</p></aside></div></section>)}
  <section className="wrap pathways"><div className="section-head"><div><p className="section-label">Worked case · 8 minutes</p><h2>A university service chatbot request</h2></div><p>Use this fictional case to see the full reasoning chain. It is illustrative, not a recommendation for education settings.</p></div><div className="path-list">{[
    ["Request","“Deploy an AI chatbot to reduce student-service email.”"],["Reframe","Decide how to improve timely, accessible answers to routine questions while preserving human escalation and correct handling of individual cases."],["Evidence","Email volume is measured; the share answerable from approved sources is unknown; policy pages conflict; staff perform substantial clarification and repair."],["Comparison","Source governance and intake repair address root causes first. A chatbot cannot yet earn preference over those paths."],["Disposition","Process repair + investigation. Assign policy owners, resolve conflicts, sample 200 inquiries, establish baseline accuracy and escalation needs, then review whether a bounded retrieval-only test is justified."]
  ].map((x,i)=><article className="path-row" key={x[0]}><span className="path-num">{i+1}</span><div><h3>{x[0]}</h3><p>{x[1]}</p></div><span className="event-result">Case</span></article>)}</div></section>
  <section className="offer-grid wrap"><article className="offer-card"><p className="section-label">Final assessment</p><h2>Complete a defensible Decision Record.</h2><p>You are complete when your workbook names the decision and owner; maps a representative workflow; labels evidence and assumptions; compares all five paths; evaluates every operating condition; selects one disposition; and gives a dated next action, advance evidence, and stop evidence.</p><p><strong>Self-check:</strong> another person should be able to disagree with your conclusion while still understanding exactly how you reached it.</p><div className="actions"><a className="button primary" href="/aloha-ai-masterclass-working-guide.md" download>Complete the workbook</a><Link className="button" href="/tools/decision-record">Open Decision Record</Link></div></article><aside><p className="section-label">What this does not do</p><h2>Education is not authorization.</h2><p>Completion does not verify your evidence, approve a vendor, authorize a pilot, certify compliance, or establish that AI belongs in the workflow. Obtain appropriate legal, privacy, security, accessibility, procurement, labor, and domain review.</p><Link className="text-link" href="/work/ai-opportunity-clinic">Need facilitated application? Review the Clinic →</Link></aside></section>
</main></SiteShell>}
