import Link from "next/link";
import {notFound,redirect} from "next/navigation";
import {SiteShell} from "../../site-shell";
import {offerBySlug} from "../offer-data";

export function generateStaticParams(){return [...Object.keys(offerBySlug),"workflow-redesign-intensive","tool-and-vendor-evaluation","responsible-build-sprint","fractional-ai-strategy-implementation","organizational-ai-program"].map(offer=>({offer}));}

export default async function OfferPage({params}:{params:Promise<{offer:string}>}){
  const {offer:slug}=await params; const legacy:Record<string,string>={"workflow-redesign-intensive":"workflow-diagnostic-redesign","tool-and-vendor-evaluation":"ai-tool-vendor-decision","responsible-build-sprint":"prototype-pilot-sprint","fractional-ai-strategy-implementation":"ai-operating-partnership","organizational-ai-program":"custom-organizational-program"}; if(legacy[slug]) redirect(`/work/${legacy[slug]}`); const offer=offerBySlug[slug]; if(!offer) notFound();
  return <SiteShell><main id="main"><section className="page-hero wrap"><p className="kicker">Bounded service · {offer.price}</p><h1>{offer.name}: <em>{offer.promise}</em></h1><p className="lede"><strong>For:</strong> {offer.buyer}</p></section><section className="boundary wrap"><p className="section-label">Choose this when</p><div><h2>{offer.trigger}</h2><p><strong>What happens next:</strong> {offer.next}</p></div></section><section className="offer-grid wrap"><article className="offer-card"><p className="section-label">Accepted scope</p><h2>What enters the engagement.</h2><ul className="scope-list">{offer.included.map(x=><li key={x}>{x}</li>)}</ul><h3>How the work moves</h3><ol className="scope-list">{offer.process.map(x=><li key={x}>{x}</li>)}</ol></article><aside><p className="section-label">Commercial boundary</p><h2>{offer.price}</h2><p>{offer.operation}</p><h3>Explicitly excluded</h3><ul className="plain-list">{offer.excluded.map(x=><li key={x}>{x}</li>)}</ul></aside></section><section className="wrap pathways"><div className="section-head"><div><p className="section-label">What the buyer receives</p><h2>Named artifacts—not vague transformation.</h2></div></div><div className="synthesis-grid">{offer.deliverables.map((x,i)=><article key={x}><strong>{String(i+1).padStart(2,"0")}</strong><p>{x}</p></article>)}</div><div className="booking-state"><strong>This named package is not bookable yet.</strong><br/>Its package-specific inquiry or qualification process is inactive. You may still bring RN the underlying problem for a separate, nonconfidential fit conversation. Any resulting work would receive its own written scope, deliverables, boundaries, timing, and price before it begins.</div><p className="quiet-note">Aloha AI provides consulting and education, not legal representation, professional certification, or guaranteed outcomes.</p><div className="actions"><Link className="button primary" href="/contact">Bring RN the underlying problem</Link><Link className="button" href="/work">Compare all ways to work together</Link></div></section></main></SiteShell>
}
